name: Bug Report
description: Report a bug in Flarial
title: "[BUG] "
labels: ["dll","launcher"]

body:
  # - type: Markdown
  #   attributes:
  #     value: |
  #       **Before you submit a bug report, please make sure you have done the following:**
  - type: checkboxes
    id: checklist
    attributes: 
      label: Checklist
      description: |
        **Before you submit a bug report, please make sure you have done the following:**
      options:
        - label: |
            I have checked the [FAQ](https://ptb.discord.com/channels/1049946152092586054/1135112998453788672)
          required: true
        - label: |
            I have searched the [issues](https://github.com/flarialmc/dll/issues?q=is%3Aissue+is%3Aopen) of this repository and believe that this is not a duplicate
          required: true
  - type: textarea
    id: bug
    attributes:
      # render: Markdown
      label: Bug description
      description: A clear and concise description of what the bug is.
      placeholder: I was trying to [...] but [...]
  
  - type: textarea
    id: expected
    attributes:
      # render: Markdown
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected [...]

  - type: textarea
    id: actual
    attributes:
      # render: Markdown
      label: Actual behavior
      description: A clear and concise description of what actually happened.
      placeholder: Instead [...]

  - type: textarea
    id: steps
    attributes:
      # render: Markdown
      label: Steps to reproduce
      description: |
        Please provide detailed steps for reproducing the issue.
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
  
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows 10
        - Windows 11
  
  - type: textarea
    id: osversion
    attributes:
      # render: Markdown
      label: OS Version
      description: What version of the operating system are you using?
      placeholder: 21H1, 21H2, 22H1, etc.
  
  - type: textarea
    id: additional
    attributes:
      label: Additional notes
      # render: Markdown
      description: |
        Add any other context about the problem here.
        If applicable, add screenshots to help explain your problem.
      placeholder: |
        - Screenshots
        - Logs
        - etc.



