#pragma once

#include <vector>

inline std::vector<std::string> acacia_logs = {
    "acacia_log",
    "acacia_wood",
    "stripped_acacia_log",
    "stripped_acacia_wood"
};

inline std::vector<std::string> air = {
    "air",
    "void_air",
    "cave_air"
};

inline std::vector<std::string> all_hanging_signs = {
    "oak_hanging_sign",
    "spruce_hanging_sign",
    "birch_hanging_sign",
    "acacia_hanging_sign",
    "cherry_hanging_sign",
    "jungle_hanging_sign",
    "dark_oak_hanging_sign",
    "pale_oak_hanging_sign",
    "crimson_hanging_sign",
    "warped_hanging_sign",
    "mangrove_hanging_sign",
    "bamboo_hanging_sign",
    "oak_wall_hanging_sign",
    "spruce_wall_hanging_sign",
    "birch_wall_hanging_sign",
    "acacia_wall_hanging_sign",
    "cherry_wall_hanging_sign",
    "jungle_wall_hanging_sign",
    "dark_oak_wall_hanging_sign",
    "pale_oak_wall_hanging_sign",
    "crimson_wall_hanging_sign",
    "warped_wall_hanging_sign",
    "mangrove_wall_hanging_sign",
    "bamboo_wall_hanging_sign"
};

inline std::vector<std::string> all_signs = {
    "oak_sign",
    "spruce_sign",
    "birch_sign",
    "acacia_sign",
    "jungle_sign",
    "dark_oak_sign",
    "pale_oak_sign",
    "crimson_sign",
    "warped_sign",
    "mangrove_sign",
    "bamboo_sign",
    "cherry_sign",
    "oak_wall_sign",
    "spruce_wall_sign",
    "birch_wall_sign",
    "acacia_wall_sign",
    "jungle_wall_sign",
    "dark_oak_wall_sign",
    "pale_oak_wall_sign",
    "crimson_wall_sign",
    "warped_wall_sign",
    "mangrove_wall_sign",
    "bamboo_wall_sign",
    "cherry_wall_sign",
    "oak_hanging_sign",
    "spruce_hanging_sign",
    "birch_hanging_sign",
    "acacia_hanging_sign",
    "cherry_hanging_sign",
    "jungle_hanging_sign",
    "dark_oak_hanging_sign",
    "pale_oak_hanging_sign",
    "crimson_hanging_sign",
    "warped_hanging_sign",
    "mangrove_hanging_sign",
    "bamboo_hanging_sign",
    "oak_wall_hanging_sign",
    "spruce_wall_hanging_sign",
    "birch_wall_hanging_sign",
    "acacia_wall_hanging_sign",
    "cherry_wall_hanging_sign",
    "jungle_wall_hanging_sign",
    "dark_oak_wall_hanging_sign",
    "pale_oak_wall_hanging_sign",
    "crimson_wall_hanging_sign",
    "warped_wall_hanging_sign",
    "mangrove_wall_hanging_sign",
    "bamboo_wall_hanging_sign"
};

inline std::vector<std::string> ancient_city_replaceable = {
    "deepslate",
    "deepslate_bricks",
    "deepslate_tiles",
    "deepslate_brick_slab",
    "deepslate_tile_slab",
    "deepslate_brick_stairs",
    "deepslate_tile_wall",
    "deepslate_brick_wall",
    "cobbled_deepslate",
    "cracked_deepslate_bricks",
    "cracked_deepslate_tiles",
    "gray_wool"
};

inline std::vector<std::string> animals_spawnable_on = {
    "grass_block"
};

inline std::vector<std::string> anvil = {
    "anvil",
    "chipped_anvil",
    "damaged_anvil"
};

inline std::vector<std::string> armadillo_spawnable_on = {
    "grass_block",
    "terracotta",
    "white_terracotta",
    "yellow_terracotta",
    "orange_terracotta",
    "red_terracotta",
    "brown_terracotta",
    "light_gray_terracotta",
    "red_sand",
    "coarse_dirt"
};

inline std::vector<std::string> axolotls_spawnable_on = {
    "clay"
};

inline std::vector<std::string> azalea_grows_on = {
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots",
    "sand",
    "red_sand",
    "suspicious_sand",
    "terracotta",
    "white_terracotta",
    "orange_terracotta",
    "magenta_terracotta",
    "light_blue_terracotta",
    "yellow_terracotta",
    "lime_terracotta",
    "pink_terracotta",
    "gray_terracotta",
    "light_gray_terracotta",
    "cyan_terracotta",
    "purple_terracotta",
    "blue_terracotta",
    "brown_terracotta",
    "green_terracotta",
    "red_terracotta",
    "black_terracotta",
    "snow_block",
    "powder_snow"
};

inline std::vector<std::string> azalea_root_replaceable = {
    "stone",
    "granite",
    "diorite",
    "andesite",
    "tuff",
    "deepslate",
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots",
    "terracotta",
    "white_terracotta",
    "orange_terracotta",
    "magenta_terracotta",
    "light_blue_terracotta",
    "yellow_terracotta",
    "lime_terracotta",
    "pink_terracotta",
    "gray_terracotta",
    "light_gray_terracotta",
    "cyan_terracotta",
    "purple_terracotta",
    "blue_terracotta",
    "brown_terracotta",
    "green_terracotta",
    "red_terracotta",
    "black_terracotta",
    "red_sand",
    "clay",
    "gravel",
    "sand",
    "snow_block",
    "powder_snow"
};

inline std::vector<std::string> badlands_terracotta = {
    "terracotta",
    "white_terracotta",
    "yellow_terracotta",
    "orange_terracotta",
    "red_terracotta",
    "brown_terracotta",
    "light_gray_terracotta"
};

inline std::vector<std::string> bamboo_blocks = {
    "bamboo_block",
    "stripped_bamboo_block"
};

inline std::vector<std::string> bamboo_plantable_on = {
    "sand",
    "red_sand",
    "suspicious_sand",
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots",
    "bamboo",
    "bamboo_sapling",
    "gravel",
    "suspicious_gravel"
};

inline std::vector<std::string> banners = {
    "white_banner",
    "orange_banner",
    "magenta_banner",
    "light_blue_banner",
    "yellow_banner",
    "lime_banner",
    "pink_banner",
    "gray_banner",
    "light_gray_banner",
    "cyan_banner",
    "purple_banner",
    "blue_banner",
    "brown_banner",
    "green_banner",
    "red_banner",
    "black_banner",
    "white_wall_banner",
    "orange_wall_banner",
    "magenta_wall_banner",
    "light_blue_wall_banner",
    "yellow_wall_banner",
    "lime_wall_banner",
    "pink_wall_banner",
    "gray_wall_banner",
    "light_gray_wall_banner",
    "cyan_wall_banner",
    "purple_wall_banner",
    "blue_wall_banner",
    "brown_wall_banner",
    "green_wall_banner",
    "red_wall_banner",
    "black_wall_banner"
};

inline std::vector<std::string> base_stone_nether = {
    "netherrack",
    "basalt",
    "blackstone"
};

inline std::vector<std::string> base_stone_overworld = {
    "stone",
    "granite",
    "diorite",
    "andesite",
    "tuff",
    "deepslate"
};

inline std::vector<std::string> bats_spawnable_on = {
    "stone",
    "granite",
    "diorite",
    "andesite",
    "tuff",
    "deepslate"
};

inline std::vector<std::string> beacon_base_blocks = {
    "netherite_block",
    "emerald_block",
    "diamond_block",
    "gold_block",
    "iron_block"
};

inline std::vector<std::string> beds = {
    "red_bed",
    "black_bed",
    "blue_bed",
    "brown_bed",
    "cyan_bed",
    "gray_bed",
    "green_bed",
    "light_blue_bed",
    "light_gray_bed",
    "lime_bed",
    "magenta_bed",
    "orange_bed",
    "pink_bed",
    "purple_bed",
    "white_bed",
    "yellow_bed"
};

inline std::vector<std::string> beehives = {
    "bee_nest",
    "beehive"
};

inline std::vector<std::string> bee_attractive = {
    "dandelion",
    "open_eyeblossom",
    "poppy",
    "blue_orchid",
    "allium",
    "azure_bluet",
    "red_tulip",
    "orange_tulip",
    "white_tulip",
    "pink_tulip",
    "oxeye_daisy",
    "cornflower",
    "lily_of_the_valley",
    "wither_rose",
    "torchflower",
    "sunflower",
    "lilac",
    "peony",
    "rose_bush",
    "pitcher_plant",
    "flowering_azalea_leaves",
    "flowering_azalea",
    "mangrove_propagule",
    "cherry_leaves",
    "pink_petals",
    "wildflowers",
    "chorus_flower",
    "spore_blossom",
    "cactus_flower"
};

inline std::vector<std::string> bee_growables = {
    "beetroots",
    "carrots",
    "potatoes",
    "wheat",
    "melon_stem",
    "pumpkin_stem",
    "torchflower_crop",
    "pitcher_crop",
    "sweet_berry_bush",
    "cave_vines",
    "cave_vines_plant"
};

inline std::vector<std::string> big_dripleaf_placeable = {
    "clay",
    "moss_block",
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "mud",
    "muddy_mangrove_roots",
    "farmland"
};

inline std::vector<std::string> birch_logs = {
    "birch_log",
    "birch_wood",
    "stripped_birch_log",
    "stripped_birch_wood"
};

inline std::vector<std::string> blocks_wind_charge_explosions = {
    "barrier",
    "bedrock"
};

inline std::vector<std::string> buttons = {
    "oak_button",
    "spruce_button",
    "birch_button",
    "jungle_button",
    "acacia_button",
    "dark_oak_button",
    "pale_oak_button",
    "crimson_button",
    "warped_button",
    "mangrove_button",
    "bamboo_button",
    "cherry_button",
    "stone_button",
    "polished_blackstone_button"
};

inline std::vector<std::string> camels_spawnable_on = {
    "sand",
    "red_sand",
    "suspicious_sand"
};

inline std::vector<std::string> camel_sand_step_sound_blocks = {
    "sand",
    "red_sand",
    "suspicious_sand",
    "white_concrete_powder",
    "orange_concrete_powder",
    "magenta_concrete_powder",
    "light_blue_concrete_powder",
    "yellow_concrete_powder",
    "lime_concrete_powder",
    "pink_concrete_powder",
    "gray_concrete_powder",
    "light_gray_concrete_powder",
    "cyan_concrete_powder",
    "purple_concrete_powder",
    "blue_concrete_powder",
    "brown_concrete_powder",
    "green_concrete_powder",
    "red_concrete_powder",
    "black_concrete_powder"
};

inline std::vector<std::string> campfires = {
    "campfire",
    "soul_campfire"
};

inline std::vector<std::string> candles = {
    "candle",
    "white_candle",
    "orange_candle",
    "magenta_candle",
    "light_blue_candle",
    "yellow_candle",
    "lime_candle",
    "pink_candle",
    "gray_candle",
    "light_gray_candle",
    "cyan_candle",
    "purple_candle",
    "blue_candle",
    "brown_candle",
    "green_candle",
    "red_candle",
    "black_candle"
};

inline std::vector<std::string> candle_cakes = {
    "candle_cake",
    "white_candle_cake",
    "orange_candle_cake",
    "magenta_candle_cake",
    "light_blue_candle_cake",
    "yellow_candle_cake",
    "lime_candle_cake",
    "pink_candle_cake",
    "gray_candle_cake",
    "light_gray_candle_cake",
    "cyan_candle_cake",
    "purple_candle_cake",
    "blue_candle_cake",
    "brown_candle_cake",
    "green_candle_cake",
    "red_candle_cake",
    "black_candle_cake"
};

inline std::vector<std::string> cauldrons = {
    "cauldron",
    "water_cauldron",
    "lava_cauldron",
    "powder_snow_cauldron"
};

inline std::vector<std::string> cave_vines = {
    "cave_vines_plant",
    "cave_vines"
};

inline std::vector<std::string> ceiling_hanging_signs = {
    "oak_hanging_sign",
    "spruce_hanging_sign",
    "birch_hanging_sign",
    "acacia_hanging_sign",
    "cherry_hanging_sign",
    "jungle_hanging_sign",
    "dark_oak_hanging_sign",
    "pale_oak_hanging_sign",
    "crimson_hanging_sign",
    "warped_hanging_sign",
    "mangrove_hanging_sign",
    "bamboo_hanging_sign"
};

inline std::vector<std::string> cherry_logs = {
    "cherry_log",
    "cherry_wood",
    "stripped_cherry_log",
    "stripped_cherry_wood"
};

inline std::vector<std::string> climbable = {
    "ladder",
    "vine",
    "scaffolding",
    "weeping_vines",
    "weeping_vines_plant",
    "twisting_vines",
    "twisting_vines_plant",
    "cave_vines",
    "cave_vines_plant"
};

inline std::vector<std::string> coal_ores = {
    "coal_ore",
    "deepslate_coal_ore"
};

inline std::vector<std::string> combination_step_sound_blocks = {
    "white_carpet",
    "orange_carpet",
    "magenta_carpet",
    "light_blue_carpet",
    "yellow_carpet",
    "lime_carpet",
    "pink_carpet",
    "gray_carpet",
    "light_gray_carpet",
    "cyan_carpet",
    "purple_carpet",
    "blue_carpet",
    "brown_carpet",
    "green_carpet",
    "red_carpet",
    "black_carpet",
    "moss_carpet",
    "pale_moss_carpet",
    "snow",
    "nether_sprouts",
    "warped_roots",
    "crimson_roots",
    "resin_clump"
};

inline std::vector<std::string> completes_find_tree_tutorial = {
    "dark_oak_log",
    "dark_oak_wood",
    "stripped_dark_oak_log",
    "stripped_dark_oak_wood",
    "pale_oak_log",
    "pale_oak_wood",
    "stripped_pale_oak_log",
    "stripped_pale_oak_wood",
    "oak_log",
    "oak_wood",
    "stripped_oak_log",
    "stripped_oak_wood",
    "acacia_log",
    "acacia_wood",
    "stripped_acacia_log",
    "stripped_acacia_wood",
    "birch_log",
    "birch_wood",
    "stripped_birch_log",
    "stripped_birch_wood",
    "jungle_log",
    "jungle_wood",
    "stripped_jungle_log",
    "stripped_jungle_wood",
    "spruce_log",
    "spruce_wood",
    "stripped_spruce_log",
    "stripped_spruce_wood",
    "mangrove_log",
    "mangrove_wood",
    "stripped_mangrove_log",
    "stripped_mangrove_wood",
    "cherry_log",
    "cherry_wood",
    "stripped_cherry_log",
    "stripped_cherry_wood",
    "crimson_stem",
    "stripped_crimson_stem",
    "crimson_hyphae",
    "stripped_crimson_hyphae",
    "warped_stem",
    "stripped_warped_stem",
    "warped_hyphae",
    "stripped_warped_hyphae",
    "jungle_leaves",
    "oak_leaves",
    "spruce_leaves",
    "pale_oak_leaves",
    "dark_oak_leaves",
    "acacia_leaves",
    "birch_leaves",
    "azalea_leaves",
    "flowering_azalea_leaves",
    "mangrove_leaves",
    "cherry_leaves",
    "nether_wart_block",
    "warped_wart_block"
};

inline std::vector<std::string> concrete_powder = {
    "white_concrete_powder",
    "orange_concrete_powder",
    "magenta_concrete_powder",
    "light_blue_concrete_powder",
    "yellow_concrete_powder",
    "lime_concrete_powder",
    "pink_concrete_powder",
    "gray_concrete_powder",
    "light_gray_concrete_powder",
    "cyan_concrete_powder",
    "purple_concrete_powder",
    "blue_concrete_powder",
    "brown_concrete_powder",
    "green_concrete_powder",
    "red_concrete_powder",
    "black_concrete_powder"
};

inline std::vector<std::string> convertable_to_mud = {
    "dirt",
    "coarse_dirt",
    "rooted_dirt"
};

inline std::vector<std::string> copper_ores = {
    "copper_ore",
    "deepslate_copper_ore"
};

inline std::vector<std::string> corals = {
    "tube_coral",
    "brain_coral",
    "bubble_coral",
    "fire_coral",
    "horn_coral",
    "tube_coral_fan",
    "brain_coral_fan",
    "bubble_coral_fan",
    "fire_coral_fan",
    "horn_coral_fan"
};

inline std::vector<std::string> coral_blocks = {
    "tube_coral_block",
    "brain_coral_block",
    "bubble_coral_block",
    "fire_coral_block",
    "horn_coral_block"
};

inline std::vector<std::string> coral_plants = {
    "tube_coral",
    "brain_coral",
    "bubble_coral",
    "fire_coral",
    "horn_coral"
};

inline std::vector<std::string> crimson_stems = {
    "crimson_stem",
    "stripped_crimson_stem",
    "crimson_hyphae",
    "stripped_crimson_hyphae"
};

inline std::vector<std::string> crops = {
    "beetroots",
    "carrots",
    "potatoes",
    "wheat",
    "melon_stem",
    "pumpkin_stem",
    "torchflower_crop",
    "pitcher_crop"
};

inline std::vector<std::string> crystal_sound_blocks = {
    "amethyst_block",
    "budding_amethyst"
};

inline std::vector<std::string> dampens_vibrations = {
    "white_wool",
    "orange_wool",
    "magenta_wool",
    "light_blue_wool",
    "yellow_wool",
    "lime_wool",
    "pink_wool",
    "gray_wool",
    "light_gray_wool",
    "cyan_wool",
    "purple_wool",
    "blue_wool",
    "brown_wool",
    "green_wool",
    "red_wool",
    "black_wool",
    "white_carpet",
    "orange_carpet",
    "magenta_carpet",
    "light_blue_carpet",
    "yellow_carpet",
    "lime_carpet",
    "pink_carpet",
    "gray_carpet",
    "light_gray_carpet",
    "cyan_carpet",
    "purple_carpet",
    "blue_carpet",
    "brown_carpet",
    "green_carpet",
    "red_carpet",
    "black_carpet"
};

inline std::vector<std::string> dark_oak_logs = {
    "dark_oak_log",
    "dark_oak_wood",
    "stripped_dark_oak_log",
    "stripped_dark_oak_wood"
};

inline std::vector<std::string> deepslate_ore_replaceables = {
    "deepslate",
    "tuff"
};

inline std::vector<std::string> diamond_ores = {
    "diamond_ore",
    "deepslate_diamond_ore"
};

inline std::vector<std::string> dirt = {
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots"
};

inline std::vector<std::string> does_not_block_hoppers = {
    "bee_nest",
    "beehive"
};

inline std::vector<std::string> doors = {
    "oak_door",
    "spruce_door",
    "birch_door",
    "jungle_door",
    "acacia_door",
    "dark_oak_door",
    "pale_oak_door",
    "crimson_door",
    "warped_door",
    "mangrove_door",
    "bamboo_door",
    "cherry_door",
    "copper_door",
    "exposed_copper_door",
    "weathered_copper_door",
    "oxidized_copper_door",
    "waxed_copper_door",
    "waxed_exposed_copper_door",
    "waxed_weathered_copper_door",
    "waxed_oxidized_copper_door",
    "iron_door"
};

inline std::vector<std::string> dragon_immune = {
    "barrier",
    "bedrock",
    "end_portal",
    "end_portal_frame",
    "end_gateway",
    "command_block",
    "repeating_command_block",
    "chain_command_block",
    "structure_block",
    "jigsaw",
    "moving_piston",
    "obsidian",
    "crying_obsidian",
    "end_stone",
    "iron_bars",
    "respawn_anchor",
    "reinforced_deepslate",
    "test_block",
    "test_instance_block"
};

inline std::vector<std::string> dragon_transparent = {
    "light",
    "fire",
    "soul_fire"
};

inline std::vector<std::string> dripstone_replaceable_blocks = {
    "stone",
    "granite",
    "diorite",
    "andesite",
    "tuff",
    "deepslate"
};

inline std::vector<std::string> dry_vegetation_may_place_on = {
    "sand",
    "red_sand",
    "suspicious_sand",
    "terracotta",
    "white_terracotta",
    "orange_terracotta",
    "magenta_terracotta",
    "light_blue_terracotta",
    "yellow_terracotta",
    "lime_terracotta",
    "pink_terracotta",
    "gray_terracotta",
    "light_gray_terracotta",
    "cyan_terracotta",
    "purple_terracotta",
    "blue_terracotta",
    "brown_terracotta",
    "green_terracotta",
    "red_terracotta",
    "black_terracotta",
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots",
    "farmland"
};

inline std::vector<std::string> edible_for_sheep = {
    "short_grass",
    "short_dry_grass",
    "tall_dry_grass",
    "fern"
};

inline std::vector<std::string> emerald_ores = {
    "emerald_ore",
    "deepslate_emerald_ore"
};

inline std::vector<std::string> enchantment_power_provider = {
    "bookshelf"
};

inline std::vector<std::string> enchantment_power_transmitter = {
    "air",
    "water",
    "lava",
    "short_grass",
    "fern",
    "dead_bush",
    "bush",
    "short_dry_grass",
    "tall_dry_grass",
    "seagrass",
    "tall_seagrass",
    "fire",
    "soul_fire",
    "snow",
    "vine",
    "glow_lichen",
    "resin_clump",
    "light",
    "tall_grass",
    "large_fern",
    "structure_void",
    "void_air",
    "cave_air",
    "bubble_column",
    "warped_roots",
    "nether_sprouts",
    "crimson_roots",
    "leaf_litter",
    "hanging_roots"
};

inline std::vector<std::string> enderman_holdable = {
    "dandelion",
    "open_eyeblossom",
    "poppy",
    "blue_orchid",
    "allium",
    "azure_bluet",
    "red_tulip",
    "orange_tulip",
    "white_tulip",
    "pink_tulip",
    "oxeye_daisy",
    "cornflower",
    "lily_of_the_valley",
    "wither_rose",
    "torchflower",
    "closed_eyeblossom",
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots",
    "sand",
    "red_sand",
    "gravel",
    "brown_mushroom",
    "red_mushroom",
    "tnt",
    "cactus",
    "clay",
    "pumpkin",
    "carved_pumpkin",
    "melon",
    "crimson_fungus",
    "crimson_nylium",
    "crimson_roots",
    "warped_fungus",
    "warped_nylium",
    "warped_roots",
    "cactus_flower"
};

inline std::vector<std::string> fall_damage_resetting = {
    "ladder",
    "vine",
    "scaffolding",
    "weeping_vines",
    "weeping_vines_plant",
    "twisting_vines",
    "twisting_vines_plant",
    "cave_vines",
    "cave_vines_plant",
    "sweet_berry_bush",
    "cobweb"
};

inline std::vector<std::string> features_cannot_replace = {
    "bedrock",
    "spawner",
    "chest",
    "end_portal_frame",
    "reinforced_deepslate",
    "trial_spawner",
    "vault"
};

inline std::vector<std::string> fences = {
    "oak_fence",
    "acacia_fence",
    "dark_oak_fence",
    "pale_oak_fence",
    "spruce_fence",
    "birch_fence",
    "jungle_fence",
    "crimson_fence",
    "warped_fence",
    "mangrove_fence",
    "bamboo_fence",
    "cherry_fence",
    "nether_brick_fence"
};

inline std::vector<std::string> fence_gates = {
    "acacia_fence_gate",
    "birch_fence_gate",
    "dark_oak_fence_gate",
    "pale_oak_fence_gate",
    "jungle_fence_gate",
    "oak_fence_gate",
    "spruce_fence_gate",
    "crimson_fence_gate",
    "warped_fence_gate",
    "mangrove_fence_gate",
    "bamboo_fence_gate",
    "cherry_fence_gate"
};

inline std::vector<std::string> fire = {
    "fire",
    "soul_fire"
};

inline std::vector<std::string> flowers = {
    "dandelion",
    "open_eyeblossom",
    "poppy",
    "blue_orchid",
    "allium",
    "azure_bluet",
    "red_tulip",
    "orange_tulip",
    "white_tulip",
    "pink_tulip",
    "oxeye_daisy",
    "cornflower",
    "lily_of_the_valley",
    "wither_rose",
    "torchflower",
    "closed_eyeblossom",
    "sunflower",
    "lilac",
    "peony",
    "rose_bush",
    "pitcher_plant",
    "flowering_azalea_leaves",
    "flowering_azalea",
    "mangrove_propagule",
    "cherry_leaves",
    "pink_petals",
    "wildflowers",
    "chorus_flower",
    "spore_blossom",
    "cactus_flower"
};

inline std::vector<std::string> flower_pots = {
    "flower_pot",
    "potted_open_eyeblossom",
    "potted_closed_eyeblossom",
    "potted_poppy",
    "potted_blue_orchid",
    "potted_allium",
    "potted_azure_bluet",
    "potted_red_tulip",
    "potted_orange_tulip",
    "potted_white_tulip",
    "potted_pink_tulip",
    "potted_oxeye_daisy",
    "potted_dandelion",
    "potted_oak_sapling",
    "potted_spruce_sapling",
    "potted_birch_sapling",
    "potted_jungle_sapling",
    "potted_acacia_sapling",
    "potted_dark_oak_sapling",
    "potted_pale_oak_sapling",
    "potted_red_mushroom",
    "potted_brown_mushroom",
    "potted_dead_bush",
    "potted_fern",
    "potted_cactus",
    "potted_cornflower",
    "potted_lily_of_the_valley",
    "potted_wither_rose",
    "potted_bamboo",
    "potted_crimson_fungus",
    "potted_warped_fungus",
    "potted_crimson_roots",
    "potted_warped_roots",
    "potted_azalea_bush",
    "potted_flowering_azalea_bush",
    "potted_mangrove_propagule",
    "potted_cherry_sapling",
    "potted_torchflower"
};

inline std::vector<std::string> foxes_spawnable_on = {
    "grass_block",
    "snow",
    "snow_block",
    "podzol",
    "coarse_dirt"
};

inline std::vector<std::string> frogs_spawnable_on = {
    "grass_block",
    "mud",
    "mangrove_roots",
    "muddy_mangrove_roots"
};

inline std::vector<std::string> frog_prefer_jump_to = {
    "lily_pad",
    "big_dripleaf"
};

inline std::vector<std::string> geode_invalid_blocks = {
    "bedrock",
    "water",
    "lava",
    "ice",
    "packed_ice",
    "blue_ice"
};

inline std::vector<std::string> goats_spawnable_on = {
    "grass_block",
    "stone",
    "snow",
    "snow_block",
    "packed_ice",
    "gravel"
};

inline std::vector<std::string> gold_ores = {
    "gold_ore",
    "nether_gold_ore",
    "deepslate_gold_ore"
};

inline std::vector<std::string> guarded_by_piglins = {
    "gold_block",
    "barrel",
    "chest",
    "ender_chest",
    "gilded_blackstone",
    "trapped_chest",
    "raw_gold_block",
    "shulker_box",
    "black_shulker_box",
    "blue_shulker_box",
    "brown_shulker_box",
    "cyan_shulker_box",
    "gray_shulker_box",
    "green_shulker_box",
    "light_blue_shulker_box",
    "light_gray_shulker_box",
    "lime_shulker_box",
    "magenta_shulker_box",
    "orange_shulker_box",
    "pink_shulker_box",
    "purple_shulker_box",
    "red_shulker_box",
    "white_shulker_box",
    "yellow_shulker_box",
    "gold_ore",
    "nether_gold_ore",
    "deepslate_gold_ore"
};

inline std::vector<std::string> happy_ghast_avoids = {
    "sweet_berry_bush",
    "cactus",
    "wither_rose",
    "magma_block",
    "fire",
    "pointed_dripstone"
};

inline std::vector<std::string> hoglin_repellents = {
    "warped_fungus",
    "potted_warped_fungus",
    "nether_portal",
    "respawn_anchor"
};

inline std::vector<std::string> ice = {
    "ice",
    "packed_ice",
    "blue_ice",
    "frosted_ice"
};

inline std::vector<std::string> impermeable = {
    "glass",
    "white_stained_glass",
    "orange_stained_glass",
    "magenta_stained_glass",
    "light_blue_stained_glass",
    "yellow_stained_glass",
    "lime_stained_glass",
    "pink_stained_glass",
    "gray_stained_glass",
    "light_gray_stained_glass",
    "cyan_stained_glass",
    "purple_stained_glass",
    "blue_stained_glass",
    "brown_stained_glass",
    "green_stained_glass",
    "red_stained_glass",
    "black_stained_glass",
    "tinted_glass"
};

inline std::vector<std::string> incorrect_for_diamond_tool = {};

inline std::vector<std::string> incorrect_for_gold_tool = {
    "obsidian",
    "crying_obsidian",
    "netherite_block",
    "respawn_anchor",
    "ancient_debris",
    "diamond_block",
    "diamond_ore",
    "deepslate_diamond_ore",
    "emerald_ore",
    "deepslate_emerald_ore",
    "emerald_block",
    "gold_block",
    "raw_gold_block",
    "gold_ore",
    "deepslate_gold_ore",
    "redstone_ore",
    "deepslate_redstone_ore",
    "iron_block",
    "raw_iron_block",
    "iron_ore",
    "deepslate_iron_ore",
    "lapis_block",
    "lapis_ore",
    "deepslate_lapis_ore",
    "copper_block",
    "raw_copper_block",
    "copper_ore",
    "deepslate_copper_ore",
    "cut_copper_slab",
    "cut_copper_stairs",
    "cut_copper",
    "weathered_copper",
    "weathered_cut_copper_slab",
    "weathered_cut_copper_stairs",
    "weathered_cut_copper",
    "oxidized_copper",
    "oxidized_cut_copper_slab",
    "oxidized_cut_copper_stairs",
    "oxidized_cut_copper",
    "exposed_copper",
    "exposed_cut_copper_slab",
    "exposed_cut_copper_stairs",
    "exposed_cut_copper",
    "waxed_copper_block",
    "waxed_cut_copper_slab",
    "waxed_cut_copper_stairs",
    "waxed_cut_copper",
    "waxed_weathered_copper",
    "waxed_weathered_cut_copper_slab",
    "waxed_weathered_cut_copper_stairs",
    "waxed_weathered_cut_copper",
    "waxed_exposed_copper",
    "waxed_exposed_cut_copper_slab",
    "waxed_exposed_cut_copper_stairs",
    "waxed_exposed_cut_copper",
    "waxed_oxidized_copper",
    "waxed_oxidized_cut_copper_slab",
    "waxed_oxidized_cut_copper_stairs",
    "waxed_oxidized_cut_copper",
    "lightning_rod",
    "crafter",
    "chiseled_copper",
    "exposed_chiseled_copper",
    "weathered_chiseled_copper",
    "oxidized_chiseled_copper",
    "waxed_chiseled_copper",
    "waxed_exposed_chiseled_copper",
    "waxed_weathered_chiseled_copper",
    "waxed_oxidized_chiseled_copper",
    "copper_grate",
    "exposed_copper_grate",
    "weathered_copper_grate",
    "oxidized_copper_grate",
    "waxed_copper_grate",
    "waxed_exposed_copper_grate",
    "waxed_weathered_copper_grate",
    "waxed_oxidized_copper_grate",
    "copper_bulb",
    "exposed_copper_bulb",
    "weathered_copper_bulb",
    "oxidized_copper_bulb",
    "waxed_copper_bulb",
    "waxed_exposed_copper_bulb",
    "waxed_weathered_copper_bulb",
    "waxed_oxidized_copper_bulb",
    "copper_trapdoor",
    "exposed_copper_trapdoor",
    "weathered_copper_trapdoor",
    "oxidized_copper_trapdoor",
    "waxed_copper_trapdoor",
    "waxed_exposed_copper_trapdoor",
    "waxed_weathered_copper_trapdoor",
    "waxed_oxidized_copper_trapdoor"
};

inline std::vector<std::string> incorrect_for_iron_tool = {
    "obsidian",
    "crying_obsidian",
    "netherite_block",
    "respawn_anchor",
    "ancient_debris"
};

inline std::vector<std::string> incorrect_for_netherite_tool = {};

inline std::vector<std::string> incorrect_for_stone_tool = {
    "obsidian",
    "crying_obsidian",
    "netherite_block",
    "respawn_anchor",
    "ancient_debris",
    "diamond_block",
    "diamond_ore",
    "deepslate_diamond_ore",
    "emerald_ore",
    "deepslate_emerald_ore",
    "emerald_block",
    "gold_block",
    "raw_gold_block",
    "gold_ore",
    "deepslate_gold_ore",
    "redstone_ore",
    "deepslate_redstone_ore"
};

inline std::vector<std::string> incorrect_for_wooden_tool = {
    "obsidian",
    "crying_obsidian",
    "netherite_block",
    "respawn_anchor",
    "ancient_debris",
    "diamond_block",
    "diamond_ore",
    "deepslate_diamond_ore",
    "emerald_ore",
    "deepslate_emerald_ore",
    "emerald_block",
    "gold_block",
    "raw_gold_block",
    "gold_ore",
    "deepslate_gold_ore",
    "redstone_ore",
    "deepslate_redstone_ore",
    "iron_block",
    "raw_iron_block",
    "iron_ore",
    "deepslate_iron_ore",
    "lapis_block",
    "lapis_ore",
    "deepslate_lapis_ore",
    "copper_block",
    "raw_copper_block",
    "copper_ore",
    "deepslate_copper_ore",
    "cut_copper_slab",
    "cut_copper_stairs",
    "cut_copper",
    "weathered_copper",
    "weathered_cut_copper_slab",
    "weathered_cut_copper_stairs",
    "weathered_cut_copper",
    "oxidized_copper",
    "oxidized_cut_copper_slab",
    "oxidized_cut_copper_stairs",
    "oxidized_cut_copper",
    "exposed_copper",
    "exposed_cut_copper_slab",
    "exposed_cut_copper_stairs",
    "exposed_cut_copper",
    "waxed_copper_block",
    "waxed_cut_copper_slab",
    "waxed_cut_copper_stairs",
    "waxed_cut_copper",
    "waxed_weathered_copper",
    "waxed_weathered_cut_copper_slab",
    "waxed_weathered_cut_copper_stairs",
    "waxed_weathered_cut_copper",
    "waxed_exposed_copper",
    "waxed_exposed_cut_copper_slab",
    "waxed_exposed_cut_copper_stairs",
    "waxed_exposed_cut_copper",
    "waxed_oxidized_copper",
    "waxed_oxidized_cut_copper_slab",
    "waxed_oxidized_cut_copper_stairs",
    "waxed_oxidized_cut_copper",
    "lightning_rod",
    "crafter",
    "chiseled_copper",
    "exposed_chiseled_copper",
    "weathered_chiseled_copper",
    "oxidized_chiseled_copper",
    "waxed_chiseled_copper",
    "waxed_exposed_chiseled_copper",
    "waxed_weathered_chiseled_copper",
    "waxed_oxidized_chiseled_copper",
    "copper_grate",
    "exposed_copper_grate",
    "weathered_copper_grate",
    "oxidized_copper_grate",
    "waxed_copper_grate",
    "waxed_exposed_copper_grate",
    "waxed_weathered_copper_grate",
    "waxed_oxidized_copper_grate",
    "copper_bulb",
    "exposed_copper_bulb",
    "weathered_copper_bulb",
    "oxidized_copper_bulb",
    "waxed_copper_bulb",
    "waxed_exposed_copper_bulb",
    "waxed_weathered_copper_bulb",
    "waxed_oxidized_copper_bulb",
    "copper_trapdoor",
    "exposed_copper_trapdoor",
    "weathered_copper_trapdoor",
    "oxidized_copper_trapdoor",
    "waxed_copper_trapdoor",
    "waxed_exposed_copper_trapdoor",
    "waxed_weathered_copper_trapdoor",
    "waxed_oxidized_copper_trapdoor"
};

inline std::vector<std::string> infiniburn_end = {
    "netherrack",
    "magma_block",
    "bedrock"
};

inline std::vector<std::string> infiniburn_nether = {
    "netherrack",
    "magma_block"
};

inline std::vector<std::string> infiniburn_overworld = {
    "netherrack",
    "magma_block"
};

inline std::vector<std::string> inside_step_sound_blocks = {
    "powder_snow",
    "sculk_vein",
    "glow_lichen",
    "lily_pad",
    "small_amethyst_bud",
    "pink_petals",
    "wildflowers",
    "leaf_litter"
};

inline std::vector<std::string> invalid_spawn_inside = {
    "end_portal",
    "end_gateway"
};

inline std::vector<std::string> iron_ores = {
    "iron_ore",
    "deepslate_iron_ore"
};

inline std::vector<std::string> jungle_logs = {
    "jungle_log",
    "jungle_wood",
    "stripped_jungle_log",
    "stripped_jungle_wood"
};

inline std::vector<std::string> lapis_ores = {
    "lapis_ore",
    "deepslate_lapis_ore"
};

inline std::vector<std::string> lava_pool_stone_cannot_replace = {
    "bedrock",
    "spawner",
    "chest",
    "end_portal_frame",
    "reinforced_deepslate",
    "trial_spawner",
    "vault",
    "jungle_leaves",
    "oak_leaves",
    "spruce_leaves",
    "pale_oak_leaves",
    "dark_oak_leaves",
    "acacia_leaves",
    "birch_leaves",
    "azalea_leaves",
    "flowering_azalea_leaves",
    "mangrove_leaves",
    "cherry_leaves",
    "dark_oak_log",
    "dark_oak_wood",
    "stripped_dark_oak_log",
    "stripped_dark_oak_wood",
    "pale_oak_log",
    "pale_oak_wood",
    "stripped_pale_oak_log",
    "stripped_pale_oak_wood",
    "oak_log",
    "oak_wood",
    "stripped_oak_log",
    "stripped_oak_wood",
    "acacia_log",
    "acacia_wood",
    "stripped_acacia_log",
    "stripped_acacia_wood",
    "birch_log",
    "birch_wood",
    "stripped_birch_log",
    "stripped_birch_wood",
    "jungle_log",
    "jungle_wood",
    "stripped_jungle_log",
    "stripped_jungle_wood",
    "spruce_log",
    "spruce_wood",
    "stripped_spruce_log",
    "stripped_spruce_wood",
    "mangrove_log",
    "mangrove_wood",
    "stripped_mangrove_log",
    "stripped_mangrove_wood",
    "cherry_log",
    "cherry_wood",
    "stripped_cherry_log",
    "stripped_cherry_wood",
    "crimson_stem",
    "stripped_crimson_stem",
    "crimson_hyphae",
    "stripped_crimson_hyphae",
    "warped_stem",
    "stripped_warped_stem",
    "warped_hyphae",
    "stripped_warped_hyphae"
};

inline std::vector<std::string> leaves = {
    "jungle_leaves",
    "oak_leaves",
    "spruce_leaves",
    "pale_oak_leaves",
    "dark_oak_leaves",
    "acacia_leaves",
    "birch_leaves",
    "azalea_leaves",
    "flowering_azalea_leaves",
    "mangrove_leaves",
    "cherry_leaves"
};

inline std::vector<std::string> logs = {
    "dark_oak_log",
    "dark_oak_wood",
    "stripped_dark_oak_log",
    "stripped_dark_oak_wood",
    "pale_oak_log",
    "pale_oak_wood",
    "stripped_pale_oak_log",
    "stripped_pale_oak_wood",
    "oak_log",
    "oak_wood",
    "stripped_oak_log",
    "stripped_oak_wood",
    "acacia_log",
    "acacia_wood",
    "stripped_acacia_log",
    "stripped_acacia_wood",
    "birch_log",
    "birch_wood",
    "stripped_birch_log",
    "stripped_birch_wood",
    "jungle_log",
    "jungle_wood",
    "stripped_jungle_log",
    "stripped_jungle_wood",
    "spruce_log",
    "spruce_wood",
    "stripped_spruce_log",
    "stripped_spruce_wood",
    "mangrove_log",
    "mangrove_wood",
    "stripped_mangrove_log",
    "stripped_mangrove_wood",
    "cherry_log",
    "cherry_wood",
    "stripped_cherry_log",
    "stripped_cherry_wood",
    "crimson_stem",
    "stripped_crimson_stem",
    "crimson_hyphae",
    "stripped_crimson_hyphae",
    "warped_stem",
    "stripped_warped_stem",
    "warped_hyphae",
    "stripped_warped_hyphae"
};

inline std::vector<std::string> logs_that_burn = {
    "dark_oak_log",
    "dark_oak_wood",
    "stripped_dark_oak_log",
    "stripped_dark_oak_wood",
    "pale_oak_log",
    "pale_oak_wood",
    "stripped_pale_oak_log",
    "stripped_pale_oak_wood",
    "oak_log",
    "oak_wood",
    "stripped_oak_log",
    "stripped_oak_wood",
    "acacia_log",
    "acacia_wood",
    "stripped_acacia_log",
    "stripped_acacia_wood",
    "birch_log",
    "birch_wood",
    "stripped_birch_log",
    "stripped_birch_wood",
    "jungle_log",
    "jungle_wood",
    "stripped_jungle_log",
    "stripped_jungle_wood",
    "spruce_log",
    "spruce_wood",
    "stripped_spruce_log",
    "stripped_spruce_wood",
    "mangrove_log",
    "mangrove_wood",
    "stripped_mangrove_log",
    "stripped_mangrove_wood",
    "cherry_log",
    "cherry_wood",
    "stripped_cherry_log",
    "stripped_cherry_wood"
};

inline std::vector<std::string> lush_ground_replaceable = {
    "stone",
    "granite",
    "diorite",
    "andesite",
    "tuff",
    "deepslate",
    "cave_vines_plant",
    "cave_vines",
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots",
    "clay",
    "gravel",
    "sand"
};

inline std::vector<std::string> maintains_farmland = {
    "pumpkin_stem",
    "attached_pumpkin_stem",
    "melon_stem",
    "attached_melon_stem",
    "beetroots",
    "carrots",
    "potatoes",
    "torchflower_crop",
    "torchflower",
    "pitcher_crop",
    "wheat"
};

inline std::vector<std::string> mangrove_logs = {
    "mangrove_log",
    "mangrove_wood",
    "stripped_mangrove_log",
    "stripped_mangrove_wood"
};

inline std::vector<std::string> mangrove_logs_can_grow_through = {
    "mud",
    "muddy_mangrove_roots",
    "mangrove_roots",
    "mangrove_leaves",
    "mangrove_log",
    "mangrove_propagule",
    "moss_carpet",
    "vine"
};

inline std::vector<std::string> mangrove_roots_can_grow_through = {
    "mud",
    "muddy_mangrove_roots",
    "mangrove_roots",
    "moss_carpet",
    "vine",
    "mangrove_propagule",
    "snow"
};

inline std::vector<std::string> mob_interactable_doors = {
    "oak_door",
    "spruce_door",
    "birch_door",
    "jungle_door",
    "acacia_door",
    "dark_oak_door",
    "pale_oak_door",
    "crimson_door",
    "warped_door",
    "mangrove_door",
    "bamboo_door",
    "cherry_door",
    "copper_door",
    "exposed_copper_door",
    "weathered_copper_door",
    "oxidized_copper_door",
    "waxed_copper_door",
    "waxed_exposed_copper_door",
    "waxed_weathered_copper_door",
    "waxed_oxidized_copper_door"
};

inline std::vector<std::string> mooshrooms_spawnable_on = {
    "mycelium"
};

inline std::vector<std::string> moss_replaceable = {
    "stone",
    "granite",
    "diorite",
    "andesite",
    "tuff",
    "deepslate",
    "cave_vines_plant",
    "cave_vines",
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots"
};

inline std::vector<std::string> mushroom_grow_block = {
    "mycelium",
    "podzol",
    "crimson_nylium",
    "warped_nylium"
};

inline std::vector<std::string> needs_diamond_tool = {
    "obsidian",
    "crying_obsidian",
    "netherite_block",
    "respawn_anchor",
    "ancient_debris"
};

inline std::vector<std::string> needs_iron_tool = {
    "diamond_block",
    "diamond_ore",
    "deepslate_diamond_ore",
    "emerald_ore",
    "deepslate_emerald_ore",
    "emerald_block",
    "gold_block",
    "raw_gold_block",
    "gold_ore",
    "deepslate_gold_ore",
    "redstone_ore",
    "deepslate_redstone_ore"
};

inline std::vector<std::string> needs_stone_tool = {
    "iron_block",
    "raw_iron_block",
    "iron_ore",
    "deepslate_iron_ore",
    "lapis_block",
    "lapis_ore",
    "deepslate_lapis_ore",
    "copper_block",
    "raw_copper_block",
    "copper_ore",
    "deepslate_copper_ore",
    "cut_copper_slab",
    "cut_copper_stairs",
    "cut_copper",
    "weathered_copper",
    "weathered_cut_copper_slab",
    "weathered_cut_copper_stairs",
    "weathered_cut_copper",
    "oxidized_copper",
    "oxidized_cut_copper_slab",
    "oxidized_cut_copper_stairs",
    "oxidized_cut_copper",
    "exposed_copper",
    "exposed_cut_copper_slab",
    "exposed_cut_copper_stairs",
    "exposed_cut_copper",
    "waxed_copper_block",
    "waxed_cut_copper_slab",
    "waxed_cut_copper_stairs",
    "waxed_cut_copper",
    "waxed_weathered_copper",
    "waxed_weathered_cut_copper_slab",
    "waxed_weathered_cut_copper_stairs",
    "waxed_weathered_cut_copper",
    "waxed_exposed_copper",
    "waxed_exposed_cut_copper_slab",
    "waxed_exposed_cut_copper_stairs",
    "waxed_exposed_cut_copper",
    "waxed_oxidized_copper",
    "waxed_oxidized_cut_copper_slab",
    "waxed_oxidized_cut_copper_stairs",
    "waxed_oxidized_cut_copper",
    "lightning_rod",
    "crafter",
    "chiseled_copper",
    "exposed_chiseled_copper",
    "weathered_chiseled_copper",
    "oxidized_chiseled_copper",
    "waxed_chiseled_copper",
    "waxed_exposed_chiseled_copper",
    "waxed_weathered_chiseled_copper",
    "waxed_oxidized_chiseled_copper",
    "copper_grate",
    "exposed_copper_grate",
    "weathered_copper_grate",
    "oxidized_copper_grate",
    "waxed_copper_grate",
    "waxed_exposed_copper_grate",
    "waxed_weathered_copper_grate",
    "waxed_oxidized_copper_grate",
    "copper_bulb",
    "exposed_copper_bulb",
    "weathered_copper_bulb",
    "oxidized_copper_bulb",
    "waxed_copper_bulb",
    "waxed_exposed_copper_bulb",
    "waxed_weathered_copper_bulb",
    "waxed_oxidized_copper_bulb",
    "copper_trapdoor",
    "exposed_copper_trapdoor",
    "weathered_copper_trapdoor",
    "oxidized_copper_trapdoor",
    "waxed_copper_trapdoor",
    "waxed_exposed_copper_trapdoor",
    "waxed_weathered_copper_trapdoor",
    "waxed_oxidized_copper_trapdoor"
};

inline std::vector<std::string> nether_carver_replaceables = {
    "stone",
    "granite",
    "diorite",
    "andesite",
    "tuff",
    "deepslate",
    "netherrack",
    "basalt",
    "blackstone",
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots",
    "crimson_nylium",
    "warped_nylium",
    "nether_wart_block",
    "warped_wart_block",
    "soul_sand",
    "soul_soil"
};

inline std::vector<std::string> nylium = {
    "crimson_nylium",
    "warped_nylium"
};

inline std::vector<std::string> oak_logs = {
    "oak_log",
    "oak_wood",
    "stripped_oak_log",
    "stripped_oak_wood"
};

inline std::vector<std::string> occludes_vibration_signals = {
    "white_wool",
    "orange_wool",
    "magenta_wool",
    "light_blue_wool",
    "yellow_wool",
    "lime_wool",
    "pink_wool",
    "gray_wool",
    "light_gray_wool",
    "cyan_wool",
    "purple_wool",
    "blue_wool",
    "brown_wool",
    "green_wool",
    "red_wool",
    "black_wool"
};

inline std::vector<std::string> overworld_carver_replaceables = {
    "stone",
    "granite",
    "diorite",
    "andesite",
    "tuff",
    "deepslate",
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots",
    "sand",
    "red_sand",
    "suspicious_sand",
    "terracotta",
    "white_terracotta",
    "orange_terracotta",
    "magenta_terracotta",
    "light_blue_terracotta",
    "yellow_terracotta",
    "lime_terracotta",
    "pink_terracotta",
    "gray_terracotta",
    "light_gray_terracotta",
    "cyan_terracotta",
    "purple_terracotta",
    "blue_terracotta",
    "brown_terracotta",
    "green_terracotta",
    "red_terracotta",
    "black_terracotta",
    "iron_ore",
    "deepslate_iron_ore",
    "copper_ore",
    "deepslate_copper_ore",
    "snow",
    "snow_block",
    "powder_snow",
    "water",
    "gravel",
    "suspicious_gravel",
    "sandstone",
    "red_sandstone",
    "calcite",
    "packed_ice",
    "raw_iron_block",
    "raw_copper_block"
};

inline std::vector<std::string> overworld_natural_logs = {
    "acacia_log",
    "birch_log",
    "oak_log",
    "jungle_log",
    "spruce_log",
    "dark_oak_log",
    "pale_oak_log",
    "mangrove_log",
    "cherry_log"
};

inline std::vector<std::string> pale_oak_logs = {
    "pale_oak_log",
    "pale_oak_wood",
    "stripped_pale_oak_log",
    "stripped_pale_oak_wood"
};

inline std::vector<std::string> parrots_spawnable_on = {
    "grass_block",
    "air",
    "jungle_leaves",
    "oak_leaves",
    "spruce_leaves",
    "pale_oak_leaves",
    "dark_oak_leaves",
    "acacia_leaves",
    "birch_leaves",
    "azalea_leaves",
    "flowering_azalea_leaves",
    "mangrove_leaves",
    "cherry_leaves",
    "dark_oak_log",
    "dark_oak_wood",
    "stripped_dark_oak_log",
    "stripped_dark_oak_wood",
    "pale_oak_log",
    "pale_oak_wood",
    "stripped_pale_oak_log",
    "stripped_pale_oak_wood",
    "oak_log",
    "oak_wood",
    "stripped_oak_log",
    "stripped_oak_wood",
    "acacia_log",
    "acacia_wood",
    "stripped_acacia_log",
    "stripped_acacia_wood",
    "birch_log",
    "birch_wood",
    "stripped_birch_log",
    "stripped_birch_wood",
    "jungle_log",
    "jungle_wood",
    "stripped_jungle_log",
    "stripped_jungle_wood",
    "spruce_log",
    "spruce_wood",
    "stripped_spruce_log",
    "stripped_spruce_wood",
    "mangrove_log",
    "mangrove_wood",
    "stripped_mangrove_log",
    "stripped_mangrove_wood",
    "cherry_log",
    "cherry_wood",
    "stripped_cherry_log",
    "stripped_cherry_wood",
    "crimson_stem",
    "stripped_crimson_stem",
    "crimson_hyphae",
    "stripped_crimson_hyphae",
    "warped_stem",
    "stripped_warped_stem",
    "warped_hyphae",
    "stripped_warped_hyphae"
};

inline std::vector<std::string> piglin_repellents = {
    "soul_fire",
    "soul_torch",
    "soul_lantern",
    "soul_wall_torch",
    "soul_campfire"
};

inline std::vector<std::string> planks = {
    "oak_planks",
    "spruce_planks",
    "birch_planks",
    "jungle_planks",
    "acacia_planks",
    "dark_oak_planks",
    "pale_oak_planks",
    "crimson_planks",
    "warped_planks",
    "mangrove_planks",
    "bamboo_planks",
    "cherry_planks"
};

inline std::vector<std::string> polar_bears_spawnable_on_alternate = {
    "ice"
};

inline std::vector<std::string> portals = {
    "nether_portal",
    "end_portal",
    "end_gateway"
};

inline std::vector<std::string> pressure_plates = {
    "light_weighted_pressure_plate",
    "heavy_weighted_pressure_plate",
    "oak_pressure_plate",
    "spruce_pressure_plate",
    "birch_pressure_plate",
    "jungle_pressure_plate",
    "acacia_pressure_plate",
    "dark_oak_pressure_plate",
    "pale_oak_pressure_plate",
    "crimson_pressure_plate",
    "warped_pressure_plate",
    "mangrove_pressure_plate",
    "bamboo_pressure_plate",
    "cherry_pressure_plate",
    "stone_pressure_plate",
    "polished_blackstone_pressure_plate"
};

inline std::vector<std::string> prevent_mob_spawning_inside = {
    "rail",
    "powered_rail",
    "detector_rail",
    "activator_rail"
};

inline std::vector<std::string> rabbits_spawnable_on = {
    "grass_block",
    "snow",
    "snow_block",
    "sand"
};

inline std::vector<std::string> rails = {
    "rail",
    "powered_rail",
    "detector_rail",
    "activator_rail"
};

inline std::vector<std::string> redstone_ores = {
    "redstone_ore",
    "deepslate_redstone_ore"
};

inline std::vector<std::string> replaceable = {
    "air",
    "water",
    "lava",
    "short_grass",
    "fern",
    "dead_bush",
    "bush",
    "short_dry_grass",
    "tall_dry_grass",
    "seagrass",
    "tall_seagrass",
    "fire",
    "soul_fire",
    "snow",
    "vine",
    "glow_lichen",
    "resin_clump",
    "light",
    "tall_grass",
    "large_fern",
    "structure_void",
    "void_air",
    "cave_air",
    "bubble_column",
    "warped_roots",
    "nether_sprouts",
    "crimson_roots",
    "leaf_litter",
    "hanging_roots"
};

inline std::vector<std::string> replaceable_by_mushrooms = {
    "jungle_leaves",
    "oak_leaves",
    "spruce_leaves",
    "pale_oak_leaves",
    "dark_oak_leaves",
    "acacia_leaves",
    "birch_leaves",
    "azalea_leaves",
    "flowering_azalea_leaves",
    "mangrove_leaves",
    "cherry_leaves",
    "dandelion",
    "open_eyeblossom",
    "poppy",
    "blue_orchid",
    "allium",
    "azure_bluet",
    "red_tulip",
    "orange_tulip",
    "white_tulip",
    "pink_tulip",
    "oxeye_daisy",
    "cornflower",
    "lily_of_the_valley",
    "wither_rose",
    "torchflower",
    "closed_eyeblossom",
    "pale_moss_carpet",
    "short_grass",
    "fern",
    "dead_bush",
    "vine",
    "glow_lichen",
    "sunflower",
    "lilac",
    "rose_bush",
    "peony",
    "tall_grass",
    "large_fern",
    "hanging_roots",
    "pitcher_plant",
    "water",
    "seagrass",
    "tall_seagrass",
    "brown_mushroom",
    "red_mushroom",
    "brown_mushroom_block",
    "red_mushroom_block",
    "warped_roots",
    "nether_sprouts",
    "crimson_roots",
    "leaf_litter",
    "short_dry_grass",
    "tall_dry_grass",
    "bush",
    "firefly_bush"
};

inline std::vector<std::string> replaceable_by_trees = {
    "jungle_leaves",
    "oak_leaves",
    "spruce_leaves",
    "pale_oak_leaves",
    "dark_oak_leaves",
    "acacia_leaves",
    "birch_leaves",
    "azalea_leaves",
    "flowering_azalea_leaves",
    "mangrove_leaves",
    "cherry_leaves",
    "dandelion",
    "open_eyeblossom",
    "poppy",
    "blue_orchid",
    "allium",
    "azure_bluet",
    "red_tulip",
    "orange_tulip",
    "white_tulip",
    "pink_tulip",
    "oxeye_daisy",
    "cornflower",
    "lily_of_the_valley",
    "wither_rose",
    "torchflower",
    "closed_eyeblossom",
    "pale_moss_carpet",
    "short_grass",
    "fern",
    "dead_bush",
    "vine",
    "glow_lichen",
    "sunflower",
    "lilac",
    "rose_bush",
    "peony",
    "tall_grass",
    "large_fern",
    "hanging_roots",
    "pitcher_plant",
    "water",
    "seagrass",
    "tall_seagrass",
    "bush",
    "firefly_bush",
    "warped_roots",
    "nether_sprouts",
    "crimson_roots",
    "leaf_litter",
    "short_dry_grass",
    "tall_dry_grass"
};

inline std::vector<std::string> sand = {
    "sand",
    "red_sand",
    "suspicious_sand"
};

inline std::vector<std::string> saplings = {
    "oak_sapling",
    "spruce_sapling",
    "birch_sapling",
    "jungle_sapling",
    "acacia_sapling",
    "dark_oak_sapling",
    "pale_oak_sapling",
    "azalea",
    "flowering_azalea",
    "mangrove_propagule",
    "cherry_sapling"
};

inline std::vector<std::string> sculk_replaceable = {
    "stone",
    "granite",
    "diorite",
    "andesite",
    "tuff",
    "deepslate",
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots",
    "terracotta",
    "white_terracotta",
    "orange_terracotta",
    "magenta_terracotta",
    "light_blue_terracotta",
    "yellow_terracotta",
    "lime_terracotta",
    "pink_terracotta",
    "gray_terracotta",
    "light_gray_terracotta",
    "cyan_terracotta",
    "purple_terracotta",
    "blue_terracotta",
    "brown_terracotta",
    "green_terracotta",
    "red_terracotta",
    "black_terracotta",
    "crimson_nylium",
    "warped_nylium",
    "netherrack",
    "basalt",
    "blackstone",
    "sand",
    "red_sand",
    "gravel",
    "soul_sand",
    "soul_soil",
    "calcite",
    "smooth_basalt",
    "clay",
    "dripstone_block",
    "end_stone",
    "red_sandstone",
    "sandstone"
};

inline std::vector<std::string> sculk_replaceable_world_gen = {
    "stone",
    "granite",
    "diorite",
    "andesite",
    "tuff",
    "deepslate",
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "mycelium",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots",
    "terracotta",
    "white_terracotta",
    "orange_terracotta",
    "magenta_terracotta",
    "light_blue_terracotta",
    "yellow_terracotta",
    "lime_terracotta",
    "pink_terracotta",
    "gray_terracotta",
    "light_gray_terracotta",
    "cyan_terracotta",
    "purple_terracotta",
    "blue_terracotta",
    "brown_terracotta",
    "green_terracotta",
    "red_terracotta",
    "black_terracotta",
    "crimson_nylium",
    "warped_nylium",
    "netherrack",
    "basalt",
    "blackstone",
    "sand",
    "red_sand",
    "gravel",
    "soul_sand",
    "soul_soil",
    "calcite",
    "smooth_basalt",
    "clay",
    "dripstone_block",
    "end_stone",
    "red_sandstone",
    "sandstone",
    "deepslate_bricks",
    "deepslate_tiles",
    "cobbled_deepslate",
    "cracked_deepslate_bricks",
    "cracked_deepslate_tiles",
    "polished_deepslate"
};

inline std::vector<std::string> shulker_boxes = {
    "shulker_box",
    "black_shulker_box",
    "blue_shulker_box",
    "brown_shulker_box",
    "cyan_shulker_box",
    "gray_shulker_box",
    "green_shulker_box",
    "light_blue_shulker_box",
    "light_gray_shulker_box",
    "lime_shulker_box",
    "magenta_shulker_box",
    "orange_shulker_box",
    "pink_shulker_box",
    "purple_shulker_box",
    "red_shulker_box",
    "white_shulker_box",
    "yellow_shulker_box"
};

inline std::vector<std::string> signs = {
    "oak_sign",
    "spruce_sign",
    "birch_sign",
    "acacia_sign",
    "jungle_sign",
    "dark_oak_sign",
    "pale_oak_sign",
    "crimson_sign",
    "warped_sign",
    "mangrove_sign",
    "bamboo_sign",
    "cherry_sign",
    "oak_wall_sign",
    "spruce_wall_sign",
    "birch_wall_sign",
    "acacia_wall_sign",
    "jungle_wall_sign",
    "dark_oak_wall_sign",
    "pale_oak_wall_sign",
    "crimson_wall_sign",
    "warped_wall_sign",
    "mangrove_wall_sign",
    "bamboo_wall_sign",
    "cherry_wall_sign"
};

inline std::vector<std::string> slabs = {
    "oak_slab",
    "spruce_slab",
    "birch_slab",
    "jungle_slab",
    "acacia_slab",
    "dark_oak_slab",
    "pale_oak_slab",
    "crimson_slab",
    "warped_slab",
    "mangrove_slab",
    "bamboo_slab",
    "cherry_slab",
    "bamboo_mosaic_slab",
    "stone_slab",
    "smooth_stone_slab",
    "stone_brick_slab",
    "sandstone_slab",
    "purpur_slab",
    "quartz_slab",
    "red_sandstone_slab",
    "brick_slab",
    "cobblestone_slab",
    "nether_brick_slab",
    "petrified_oak_slab",
    "prismarine_slab",
    "prismarine_brick_slab",
    "dark_prismarine_slab",
    "polished_granite_slab",
    "smooth_red_sandstone_slab",
    "mossy_stone_brick_slab",
    "polished_diorite_slab",
    "mossy_cobblestone_slab",
    "end_stone_brick_slab",
    "smooth_sandstone_slab",
    "smooth_quartz_slab",
    "granite_slab",
    "andesite_slab",
    "red_nether_brick_slab",
    "polished_andesite_slab",
    "diorite_slab",
    "cut_sandstone_slab",
    "cut_red_sandstone_slab",
    "blackstone_slab",
    "polished_blackstone_brick_slab",
    "polished_blackstone_slab",
    "cobbled_deepslate_slab",
    "polished_deepslate_slab",
    "deepslate_tile_slab",
    "deepslate_brick_slab",
    "waxed_weathered_cut_copper_slab",
    "waxed_exposed_cut_copper_slab",
    "waxed_cut_copper_slab",
    "oxidized_cut_copper_slab",
    "weathered_cut_copper_slab",
    "exposed_cut_copper_slab",
    "cut_copper_slab",
    "waxed_oxidized_cut_copper_slab",
    "mud_brick_slab",
    "tuff_slab",
    "polished_tuff_slab",
    "tuff_brick_slab",
    "resin_brick_slab"
};

inline std::vector<std::string> small_dripleaf_placeable = {
    "clay",
    "moss_block"
};

inline std::vector<std::string> small_flowers = {
    "dandelion",
    "open_eyeblossom",
    "poppy",
    "blue_orchid",
    "allium",
    "azure_bluet",
    "red_tulip",
    "orange_tulip",
    "white_tulip",
    "pink_tulip",
    "oxeye_daisy",
    "cornflower",
    "lily_of_the_valley",
    "wither_rose",
    "torchflower",
    "closed_eyeblossom"
};

inline std::vector<std::string> smelts_to_glass = {
    "sand",
    "red_sand"
};

inline std::vector<std::string> snaps_goat_horn = {
    "acacia_log",
    "birch_log",
    "oak_log",
    "jungle_log",
    "spruce_log",
    "dark_oak_log",
    "pale_oak_log",
    "mangrove_log",
    "cherry_log",
    "stone",
    "packed_ice",
    "iron_ore",
    "coal_ore",
    "copper_ore",
    "emerald_ore"
};

inline std::vector<std::string> sniffer_diggable_block = {
    "dirt",
    "grass_block",
    "podzol",
    "coarse_dirt",
    "rooted_dirt",
    "moss_block",
    "pale_moss_block",
    "mud",
    "muddy_mangrove_roots"
};

inline std::vector<std::string> sniffer_egg_hatch_boost = {
    "moss_block"
};

inline std::vector<std::string> snow = {
    "snow",
    "snow_block",
    "powder_snow"
};

inline std::vector<std::string> snow_layer_cannot_survive_on = {
    "ice",
    "packed_ice",
    "barrier"
};

inline std::vector<std::string> snow_layer_can_survive_on = {
    "honey_block",
    "soul_sand",
    "mud"
};

inline std::vector<std::string> soul_fire_base_blocks = {
    "soul_sand",
    "soul_soil"
};

inline std::vector<std::string> soul_speed_blocks = {
    "soul_sand",
    "soul_soil"
};

inline std::vector<std::string> spruce_logs = {
    "spruce_log",
    "spruce_wood",
    "stripped_spruce_log",
    "stripped_spruce_wood"
};

inline std::vector<std::string> stairs = {
    "oak_stairs",
    "spruce_stairs",
    "birch_stairs",
    "jungle_stairs",
    "acacia_stairs",
    "dark_oak_stairs",
    "pale_oak_stairs",
    "crimson_stairs",
    "warped_stairs",
    "mangrove_stairs",
    "bamboo_stairs",
    "cherry_stairs",
    "bamboo_mosaic_stairs",
    "cobblestone_stairs",
    "sandstone_stairs",
    "nether_brick_stairs",
    "stone_brick_stairs",
    "brick_stairs",
    "purpur_stairs",
    "quartz_stairs",
    "red_sandstone_stairs",
    "prismarine_brick_stairs",
    "prismarine_stairs",
    "dark_prismarine_stairs",
    "polished_granite_stairs",
    "smooth_red_sandstone_stairs",
    "mossy_stone_brick_stairs",
    "polished_diorite_stairs",
    "mossy_cobblestone_stairs",
    "end_stone_brick_stairs",
    "stone_stairs",
    "smooth_sandstone_stairs",
    "smooth_quartz_stairs",
    "granite_stairs",
    "andesite_stairs",
    "red_nether_brick_stairs",
    "polished_andesite_stairs",
    "diorite_stairs",
    "blackstone_stairs",
    "polished_blackstone_brick_stairs",
    "polished_blackstone_stairs",
    "cobbled_deepslate_stairs",
    "polished_deepslate_stairs",
    "deepslate_tile_stairs",
    "deepslate_brick_stairs",
    "oxidized_cut_copper_stairs",
    "weathered_cut_copper_stairs",
    "exposed_cut_copper_stairs",
    "cut_copper_stairs",
    "waxed_weathered_cut_copper_stairs",
    "waxed_exposed_cut_copper_stairs",
    "waxed_cut_copper_stairs",
    "waxed_oxidized_cut_copper_stairs",
    "mud_brick_stairs",
    "tuff_stairs",
    "polished_tuff_stairs",
    "tuff_brick_stairs",
    "resin_brick_stairs"
};

inline std::vector<std::string> standing_signs = {
    "oak_sign",
    "spruce_sign",
    "birch_sign",
    "acacia_sign",
    "jungle_sign",
    "dark_oak_sign",
    "pale_oak_sign",
    "crimson_sign",
    "warped_sign",
    "mangrove_sign",
    "bamboo_sign",
    "cherry_sign"
};

inline std::vector<std::string> stone_bricks = {
    "stone_bricks",
    "mossy_stone_bricks",
    "cracked_stone_bricks",
    "chiseled_stone_bricks"
};

inline std::vector<std::string> stone_buttons = {
    "stone_button",
    "polished_blackstone_button"
};

inline std::vector<std::string> stone_ore_replaceables = {
    "stone",
    "granite",
    "diorite",
    "andesite"
};

inline std::vector<std::string> stone_pressure_plates = {
    "stone_pressure_plate",
    "polished_blackstone_pressure_plate"
};

inline std::vector<std::string> strider_warm_blocks = {
    "lava"
};

inline std::vector<std::string> sword_efficient = {
    "jungle_leaves",
    "oak_leaves",
    "spruce_leaves",
    "pale_oak_leaves",
    "dark_oak_leaves",
    "acacia_leaves",
    "birch_leaves",
    "azalea_leaves",
    "flowering_azalea_leaves",
    "mangrove_leaves",
    "cherry_leaves",
    "vine",
    "glow_lichen",
    "pumpkin",
    "carved_pumpkin",
    "jack_o_lantern",
    "melon",
    "cocoa",
    "big_dripleaf",
    "big_dripleaf_stem",
    "chorus_plant",
    "chorus_flower"
};

inline std::vector<std::string> sword_instantly_mines = {
    "bamboo",
    "bamboo_sapling"
};

inline std::vector<std::string> terracotta = {
    "terracotta",
    "white_terracotta",
    "orange_terracotta",
    "magenta_terracotta",
    "light_blue_terracotta",
    "yellow_terracotta",
    "lime_terracotta",
    "pink_terracotta",
    "gray_terracotta",
    "light_gray_terracotta",
    "cyan_terracotta",
    "purple_terracotta",
    "blue_terracotta",
    "brown_terracotta",
    "green_terracotta",
    "red_terracotta",
    "black_terracotta"
};

inline std::vector<std::string> trail_ruins_replaceable = {
    "gravel"
};

inline std::vector<std::string> trapdoors = {
    "acacia_trapdoor",
    "birch_trapdoor",
    "dark_oak_trapdoor",
    "pale_oak_trapdoor",
    "jungle_trapdoor",
    "oak_trapdoor",
    "spruce_trapdoor",
    "crimson_trapdoor",
    "warped_trapdoor",
    "mangrove_trapdoor",
    "bamboo_trapdoor",
    "cherry_trapdoor",
    "iron_trapdoor",
    "copper_trapdoor",
    "exposed_copper_trapdoor",
    "weathered_copper_trapdoor",
    "oxidized_copper_trapdoor",
    "waxed_copper_trapdoor",
    "waxed_exposed_copper_trapdoor",
    "waxed_weathered_copper_trapdoor",
    "waxed_oxidized_copper_trapdoor"
};

inline std::vector<std::string> triggers_ambient_desert_dry_vegetation_block_sounds = {
    "terracotta",
    "white_terracotta",
    "orange_terracotta",
    "magenta_terracotta",
    "light_blue_terracotta",
    "yellow_terracotta",
    "lime_terracotta",
    "pink_terracotta",
    "gray_terracotta",
    "light_gray_terracotta",
    "cyan_terracotta",
    "purple_terracotta",
    "blue_terracotta",
    "brown_terracotta",
    "green_terracotta",
    "red_terracotta",
    "black_terracotta",
    "sand",
    "red_sand"
};

inline std::vector<std::string> triggers_ambient_desert_sand_block_sounds = {
    "sand",
    "red_sand"
};

inline std::vector<std::string> triggers_ambient_dried_ghast_block_sounds = {
    "soul_sand",
    "soul_soil"
};

inline std::vector<std::string> underwater_bonemeals = {
    "seagrass",
    "tube_coral",
    "brain_coral",
    "bubble_coral",
    "fire_coral",
    "horn_coral",
    "tube_coral_fan",
    "brain_coral_fan",
    "bubble_coral_fan",
    "fire_coral_fan",
    "horn_coral_fan",
    "tube_coral_wall_fan",
    "brain_coral_wall_fan",
    "bubble_coral_wall_fan",
    "fire_coral_wall_fan",
    "horn_coral_wall_fan"
};

inline std::vector<std::string> unstable_bottom_center = {
    "acacia_fence_gate",
    "birch_fence_gate",
    "dark_oak_fence_gate",
    "pale_oak_fence_gate",
    "jungle_fence_gate",
    "oak_fence_gate",
    "spruce_fence_gate",
    "crimson_fence_gate",
    "warped_fence_gate",
    "mangrove_fence_gate",
    "bamboo_fence_gate",
    "cherry_fence_gate"
};

inline std::vector<std::string> valid_spawn = {
    "grass_block",
    "podzol"
};

inline std::vector<std::string> vibration_resonators = {
    "amethyst_block"
};

inline std::vector<std::string> walls = {
    "cobblestone_wall",
    "mossy_cobblestone_wall",
    "brick_wall",
    "prismarine_wall",
    "red_sandstone_wall",
    "mossy_stone_brick_wall",
    "granite_wall",
    "stone_brick_wall",
    "nether_brick_wall",
    "andesite_wall",
    "red_nether_brick_wall",
    "sandstone_wall",
    "end_stone_brick_wall",
    "diorite_wall",
    "blackstone_wall",
    "polished_blackstone_brick_wall",
    "polished_blackstone_wall",
    "cobbled_deepslate_wall",
    "polished_deepslate_wall",
    "deepslate_tile_wall",
    "deepslate_brick_wall",
    "mud_brick_wall",
    "tuff_wall",
    "polished_tuff_wall",
    "tuff_brick_wall",
    "resin_brick_wall"
};

inline std::vector<std::string> wall_corals = {
    "tube_coral_wall_fan",
    "brain_coral_wall_fan",
    "bubble_coral_wall_fan",
    "fire_coral_wall_fan",
    "horn_coral_wall_fan"
};

inline std::vector<std::string> wall_hanging_signs = {
    "oak_wall_hanging_sign",
    "spruce_wall_hanging_sign",
    "birch_wall_hanging_sign",
    "acacia_wall_hanging_sign",
    "cherry_wall_hanging_sign",
    "jungle_wall_hanging_sign",
    "dark_oak_wall_hanging_sign",
    "pale_oak_wall_hanging_sign",
    "crimson_wall_hanging_sign",
    "warped_wall_hanging_sign",
    "mangrove_wall_hanging_sign",
    "bamboo_wall_hanging_sign"
};

inline std::vector<std::string> wall_post_override = {
    "torch",
    "soul_torch",
    "redstone_torch",
    "tripwire",
    "oak_sign",
    "spruce_sign",
    "birch_sign",
    "acacia_sign",
    "jungle_sign",
    "dark_oak_sign",
    "pale_oak_sign",
    "crimson_sign",
    "warped_sign",
    "mangrove_sign",
    "bamboo_sign",
    "cherry_sign",
    "oak_wall_sign",
    "spruce_wall_sign",
    "birch_wall_sign",
    "acacia_wall_sign",
    "jungle_wall_sign",
    "dark_oak_wall_sign",
    "pale_oak_wall_sign",
    "crimson_wall_sign",
    "warped_wall_sign",
    "mangrove_wall_sign",
    "bamboo_wall_sign",
    "cherry_wall_sign",
    "white_banner",
    "orange_banner",
    "magenta_banner",
    "light_blue_banner",
    "yellow_banner",
    "lime_banner",
    "pink_banner",
    "gray_banner",
    "light_gray_banner",
    "cyan_banner",
    "purple_banner",
    "blue_banner",
    "brown_banner",
    "green_banner",
    "red_banner",
    "black_banner",
    "white_wall_banner",
    "orange_wall_banner",
    "magenta_wall_banner",
    "light_blue_wall_banner",
    "yellow_wall_banner",
    "lime_wall_banner",
    "pink_wall_banner",
    "gray_wall_banner",
    "light_gray_wall_banner",
    "cyan_wall_banner",
    "purple_wall_banner",
    "blue_wall_banner",
    "brown_wall_banner",
    "green_wall_banner",
    "red_wall_banner",
    "black_wall_banner",
    "light_weighted_pressure_plate",
    "heavy_weighted_pressure_plate",
    "oak_pressure_plate",
    "spruce_pressure_plate",
    "birch_pressure_plate",
    "jungle_pressure_plate",
    "acacia_pressure_plate",
    "dark_oak_pressure_plate",
    "pale_oak_pressure_plate",
    "crimson_pressure_plate",
    "warped_pressure_plate",
    "mangrove_pressure_plate",
    "bamboo_pressure_plate",
    "cherry_pressure_plate",
    "stone_pressure_plate",
    "polished_blackstone_pressure_plate",
    "cactus_flower"
};

inline std::vector<std::string> wall_signs = {
    "oak_wall_sign",
    "spruce_wall_sign",
    "birch_wall_sign",
    "acacia_wall_sign",
    "jungle_wall_sign",
    "dark_oak_wall_sign",
    "pale_oak_wall_sign",
    "crimson_wall_sign",
    "warped_wall_sign",
    "mangrove_wall_sign",
    "bamboo_wall_sign",
    "cherry_wall_sign"
};

inline std::vector<std::string> warped_stems = {
    "warped_stem",
    "stripped_warped_stem",
    "warped_hyphae",
    "stripped_warped_hyphae"
};

inline std::vector<std::string> wart_blocks = {
    "nether_wart_block",
    "warped_wart_block"
};

inline std::vector<std::string> wither_immune = {
    "barrier",
    "bedrock",
    "end_portal",
    "end_portal_frame",
    "end_gateway",
    "command_block",
    "repeating_command_block",
    "chain_command_block",
    "structure_block",
    "jigsaw",
    "moving_piston",
    "light",
    "reinforced_deepslate",
    "test_block",
    "test_instance_block"
};

inline std::vector<std::string> wither_summon_base_blocks = {
    "soul_sand",
    "soul_soil"
};

inline std::vector<std::string> wolves_spawnable_on = {
    "grass_block",
    "snow",
    "snow_block",
    "coarse_dirt",
    "podzol"
};

inline std::vector<std::string> wooden_buttons = {
    "oak_button",
    "spruce_button",
    "birch_button",
    "jungle_button",
    "acacia_button",
    "dark_oak_button",
    "pale_oak_button",
    "crimson_button",
    "warped_button",
    "mangrove_button",
    "bamboo_button",
    "cherry_button"
};

inline std::vector<std::string> wooden_doors = {
    "oak_door",
    "spruce_door",
    "birch_door",
    "jungle_door",
    "acacia_door",
    "dark_oak_door",
    "pale_oak_door",
    "crimson_door",
    "warped_door",
    "mangrove_door",
    "bamboo_door",
    "cherry_door"
};

inline std::vector<std::string> wooden_fences = {
    "oak_fence",
    "acacia_fence",
    "dark_oak_fence",
    "pale_oak_fence",
    "spruce_fence",
    "birch_fence",
    "jungle_fence",
    "crimson_fence",
    "warped_fence",
    "mangrove_fence",
    "bamboo_fence",
    "cherry_fence"
};

inline std::vector<std::string> wooden_pressure_plates = {
    "oak_pressure_plate",
    "spruce_pressure_plate",
    "birch_pressure_plate",
    "jungle_pressure_plate",
    "acacia_pressure_plate",
    "dark_oak_pressure_plate",
    "pale_oak_pressure_plate",
    "crimson_pressure_plate",
    "warped_pressure_plate",
    "mangrove_pressure_plate",
    "bamboo_pressure_plate",
    "cherry_pressure_plate"
};

inline std::vector<std::string> wooden_slabs = {
    "oak_slab",
    "spruce_slab",
    "birch_slab",
    "jungle_slab",
    "acacia_slab",
    "dark_oak_slab",
    "pale_oak_slab",
    "crimson_slab",
    "warped_slab",
    "mangrove_slab",
    "bamboo_slab",
    "cherry_slab"
};

inline std::vector<std::string> wooden_stairs = {
    "oak_stairs",
    "spruce_stairs",
    "birch_stairs",
    "jungle_stairs",
    "acacia_stairs",
    "dark_oak_stairs",
    "pale_oak_stairs",
    "crimson_stairs",
    "warped_stairs",
    "mangrove_stairs",
    "bamboo_stairs",
    "cherry_stairs"
};

inline std::vector<std::string> wooden_trapdoors = {
    "acacia_trapdoor",
    "birch_trapdoor",
    "dark_oak_trapdoor",
    "pale_oak_trapdoor",
    "jungle_trapdoor",
    "oak_trapdoor",
    "spruce_trapdoor",
    "crimson_trapdoor",
    "warped_trapdoor",
    "mangrove_trapdoor",
    "bamboo_trapdoor",
    "cherry_trapdoor"
};

inline std::vector<std::string> wool = {
    "white_wool",
    "orange_wool",
    "magenta_wool",
    "light_blue_wool",
    "yellow_wool",
    "lime_wool",
    "pink_wool",
    "gray_wool",
    "light_gray_wool",
    "cyan_wool",
    "purple_wool",
    "blue_wool",
    "brown_wool",
    "green_wool",
    "red_wool",
    "black_wool"
};

inline std::vector<std::string> wool_carpets = {
    "white_carpet",
    "orange_carpet",
    "magenta_carpet",
    "light_blue_carpet",
    "yellow_carpet",
    "lime_carpet",
    "pink_carpet",
    "gray_carpet",
    "light_gray_carpet",
    "cyan_carpet",
    "purple_carpet",
    "blue_carpet",
    "brown_carpet",
    "green_carpet",
    "red_carpet",
    "black_carpet"
};


inline std::vector<std::string> mineable_axe = {
    "note_block",
    "bamboo",
    "barrel",
    "bee_nest",
    "beehive",
    "big_dripleaf_stem",
    "big_dripleaf",
    "bookshelf",
    "brown_mushroom_block",
    "campfire",
    "cartography_table",
    "carved_pumpkin",
    "chest",
    "chorus_flower",
    "chorus_plant",
    "cocoa",
    "composter",
    "crafting_table",
    "daylight_detector",
    "fletching_table",
    "glow_lichen",
    "jack_o_lantern",
    "jukebox",
    "ladder",
    "lectern",
    "loom",
    "melon",
    "mushroom_stem",
    "pumpkin",
    "red_mushroom_block",
    "smithing_table",
    "soul_campfire",
    "trapped_chest",
    "vine",
    "white_banner",
    "orange_banner",
    "magenta_banner",
    "light_blue_banner",
    "yellow_banner",
    "lime_banner",
    "pink_banner",
    "gray_banner",
    "light_gray_banner",
    "cyan_banner",
    "purple_banner",
    "blue_banner",
    "brown_banner",
    "green_banner",
    "red_banner",
    "black_banner",
    "white_wall_banner",
    "orange_wall_banner",
    "magenta_wall_banner",
    "light_blue_wall_banner",
    "yellow_wall_banner",
    "lime_wall_banner",
    "pink_wall_banner",
    "gray_wall_banner",
    "light_gray_wall_banner",
    "cyan_wall_banner",
    "purple_wall_banner",
    "blue_wall_banner",
    "brown_wall_banner",
    "green_wall_banner",
    "red_wall_banner",
    "black_wall_banner",
    "acacia_fence_gate",
    "birch_fence_gate",
    "dark_oak_fence_gate",
    "pale_oak_fence_gate",
    "jungle_fence_gate",
    "oak_fence_gate",
    "spruce_fence_gate",
    "crimson_fence_gate",
    "warped_fence_gate",
    "mangrove_fence_gate",
    "bamboo_fence_gate",
    "cherry_fence_gate",
    "dark_oak_log",
    "dark_oak_wood",
    "stripped_dark_oak_log",
    "stripped_dark_oak_wood",
    "pale_oak_log",
    "pale_oak_wood",
    "stripped_pale_oak_log",
    "stripped_pale_oak_wood",
    "oak_log",
    "oak_wood",
    "stripped_oak_log",
    "stripped_oak_wood",
    "acacia_log",
    "acacia_wood",
    "stripped_acacia_log",
    "stripped_acacia_wood",
    "birch_log",
    "birch_wood",
    "stripped_birch_log",
    "stripped_birch_wood",
    "jungle_log",
    "jungle_wood",
    "stripped_jungle_log",
    "stripped_jungle_wood",
    "spruce_log",
    "spruce_wood",
    "stripped_spruce_log",
    "stripped_spruce_wood",
    "mangrove_log",
    "mangrove_wood",
    "stripped_mangrove_log",
    "stripped_mangrove_wood",
    "cherry_log",
    "cherry_wood",
    "stripped_cherry_log",
    "stripped_cherry_wood",
    "crimson_stem",
    "stripped_crimson_stem",
    "crimson_hyphae",
    "stripped_crimson_hyphae",
    "warped_stem",
    "stripped_warped_stem",
    "warped_hyphae",
    "stripped_warped_hyphae",
    "oak_planks",
    "spruce_planks",
    "birch_planks",
    "jungle_planks",
    "acacia_planks",
    "dark_oak_planks",
    "pale_oak_planks",
    "crimson_planks",
    "warped_planks",
    "mangrove_planks",
    "bamboo_planks",
    "cherry_planks",
    "oak_sign",
    "spruce_sign",
    "birch_sign",
    "acacia_sign",
    "jungle_sign",
    "dark_oak_sign",
    "pale_oak_sign",
    "crimson_sign",
    "warped_sign",
    "mangrove_sign",
    "bamboo_sign",
    "cherry_sign",
    "oak_wall_sign",
    "spruce_wall_sign",
    "birch_wall_sign",
    "acacia_wall_sign",
    "jungle_wall_sign",
    "dark_oak_wall_sign",
    "pale_oak_wall_sign",
    "crimson_wall_sign",
    "warped_wall_sign",
    "mangrove_wall_sign",
    "bamboo_wall_sign",
    "cherry_wall_sign",
    "oak_button",
    "spruce_button",
    "birch_button",
    "jungle_button",
    "acacia_button",
    "dark_oak_button",
    "pale_oak_button",
    "crimson_button",
    "warped_button",
    "mangrove_button",
    "bamboo_button",
    "cherry_button",
    "oak_door",
    "spruce_door",
    "birch_door",
    "jungle_door",
    "acacia_door",
    "dark_oak_door",
    "pale_oak_door",
    "crimson_door",
    "warped_door",
    "mangrove_door",
    "bamboo_door",
    "cherry_door",
    "oak_fence",
    "acacia_fence",
    "dark_oak_fence",
    "pale_oak_fence",
    "spruce_fence",
    "birch_fence",
    "jungle_fence",
    "crimson_fence",
    "warped_fence",
    "mangrove_fence",
    "bamboo_fence",
    "cherry_fence",
    "oak_pressure_plate",
    "spruce_pressure_plate",
    "birch_pressure_plate",
    "jungle_pressure_plate",
    "acacia_pressure_plate",
    "dark_oak_pressure_plate",
    "pale_oak_pressure_plate",
    "crimson_pressure_plate",
    "warped_pressure_plate",
    "mangrove_pressure_plate",
    "bamboo_pressure_plate",
    "cherry_pressure_plate",
    "oak_slab",
    "spruce_slab",
    "birch_slab",
    "jungle_slab",
    "acacia_slab",
    "dark_oak_slab",
    "pale_oak_slab",
    "crimson_slab",
    "warped_slab",
    "mangrove_slab",
    "bamboo_slab",
    "cherry_slab",
    "oak_stairs",
    "spruce_stairs",
    "birch_stairs",
    "jungle_stairs",
    "acacia_stairs",
    "dark_oak_stairs",
    "pale_oak_stairs",
    "crimson_stairs",
    "warped_stairs",
    "mangrove_stairs",
    "bamboo_stairs",
    "cherry_stairs",
    "acacia_trapdoor",
    "birch_trapdoor",
    "dark_oak_trapdoor",
    "pale_oak_trapdoor",
    "jungle_trapdoor",
    "oak_trapdoor",
    "spruce_trapdoor",
    "crimson_trapdoor",
    "warped_trapdoor",
    "mangrove_trapdoor",
    "bamboo_trapdoor",
    "cherry_trapdoor",
    "mangrove_roots",
    "oak_hanging_sign",
    "spruce_hanging_sign",
    "birch_hanging_sign",
    "acacia_hanging_sign",
    "cherry_hanging_sign",
    "jungle_hanging_sign",
    "dark_oak_hanging_sign",
    "pale_oak_hanging_sign",
    "crimson_hanging_sign",
    "warped_hanging_sign",
    "mangrove_hanging_sign",
    "bamboo_hanging_sign",
    "oak_wall_hanging_sign",
    "spruce_wall_hanging_sign",
    "birch_wall_hanging_sign",
    "acacia_wall_hanging_sign",
    "cherry_wall_hanging_sign",
    "jungle_wall_hanging_sign",
    "dark_oak_wall_hanging_sign",
    "pale_oak_wall_hanging_sign",
    "crimson_wall_hanging_sign",
    "warped_wall_hanging_sign",
    "mangrove_wall_hanging_sign",
    "bamboo_wall_hanging_sign",
    "bamboo_mosaic",
    "bamboo_mosaic_slab",
    "bamboo_mosaic_stairs",
    "bamboo_block",
    "stripped_bamboo_block",
    "chiseled_bookshelf",
    "creaking_heart"
};

inline std::vector<std::string> mineable_hoe = {
    "jungle_leaves",
    "oak_leaves",
    "spruce_leaves",
    "pale_oak_leaves",
    "dark_oak_leaves",
    "acacia_leaves",
    "birch_leaves",
    "azalea_leaves",
    "flowering_azalea_leaves",
    "mangrove_leaves",
    "cherry_leaves",
    "nether_wart_block",
    "warped_wart_block",
    "hay_block",
    "dried_kelp_block",
    "target",
    "shroomlight",
    "sponge",
    "wet_sponge",
    "sculk_sensor",
    "calibrated_sculk_sensor",
    "moss_block",
    "moss_carpet",
    "pale_moss_block",
    "pale_moss_carpet",
    "sculk",
    "sculk_catalyst",
    "sculk_vein",
    "sculk_shrieker"
};

inline std::vector<std::string> mineable_pickaxe = {
    "stone",
    "granite",
    "polished_granite",
    "diorite",
    "polished_diorite",
    "andesite",
    "polished_andesite",
    "cobblestone",
    "gold_ore",
    "deepslate_gold_ore",
    "iron_ore",
    "deepslate_iron_ore",
    "coal_ore",
    "deepslate_coal_ore",
    "nether_gold_ore",
    "lapis_ore",
    "deepslate_lapis_ore",
    "lapis_block",
    "dispenser",
    "sandstone",
    "chiseled_sandstone",
    "cut_sandstone",
    "gold_block",
    "iron_block",
    "bricks",
    "mossy_cobblestone",
    "obsidian",
    "spawner",
    "diamond_ore",
    "deepslate_diamond_ore",
    "diamond_block",
    "furnace",
    "cobblestone_stairs",
    "stone_pressure_plate",
    "iron_door",
    "redstone_ore",
    "deepslate_redstone_ore",
    "netherrack",
    "basalt",
    "polished_basalt",
    "stone_bricks",
    "mossy_stone_bricks",
    "cracked_stone_bricks",
    "chiseled_stone_bricks",
    "iron_bars",
    "chain",
    "brick_stairs",
    "stone_brick_stairs",
    "nether_bricks",
    "nether_brick_fence",
    "nether_brick_stairs",
    "enchanting_table",
    "brewing_stand",
    "end_stone",
    "sandstone_stairs",
    "emerald_ore",
    "deepslate_emerald_ore",
    "ender_chest",
    "emerald_block",
    "light_weighted_pressure_plate",
    "heavy_weighted_pressure_plate",
    "redstone_block",
    "nether_quartz_ore",
    "hopper",
    "quartz_block",
    "chiseled_quartz_block",
    "quartz_pillar",
    "quartz_stairs",
    "dropper",
    "white_terracotta",
    "orange_terracotta",
    "magenta_terracotta",
    "light_blue_terracotta",
    "yellow_terracotta",
    "lime_terracotta",
    "pink_terracotta",
    "gray_terracotta",
    "light_gray_terracotta",
    "cyan_terracotta",
    "purple_terracotta",
    "blue_terracotta",
    "brown_terracotta",
    "green_terracotta",
    "red_terracotta",
    "black_terracotta",
    "iron_trapdoor",
    "prismarine",
    "prismarine_bricks",
    "dark_prismarine",
    "prismarine_stairs",
    "prismarine_brick_stairs",
    "dark_prismarine_stairs",
    "prismarine_slab",
    "prismarine_brick_slab",
    "dark_prismarine_slab",
    "terracotta",
    "coal_block",
    "red_sandstone",
    "chiseled_red_sandstone",
    "cut_red_sandstone",
    "red_sandstone_stairs",
    "stone_slab",
    "smooth_stone_slab",
    "sandstone_slab",
    "cut_sandstone_slab",
    "petrified_oak_slab",
    "cobblestone_slab",
    "brick_slab",
    "stone_brick_slab",
    "nether_brick_slab",
    "quartz_slab",
    "red_sandstone_slab",
    "cut_red_sandstone_slab",
    "purpur_slab",
    "smooth_stone",
    "smooth_sandstone",
    "smooth_quartz",
    "smooth_red_sandstone",
    "purpur_block",
    "purpur_pillar",
    "purpur_stairs",
    "end_stone_bricks",
    "magma_block",
    "red_nether_bricks",
    "bone_block",
    "observer",
    "white_glazed_terracotta",
    "orange_glazed_terracotta",
    "magenta_glazed_terracotta",
    "light_blue_glazed_terracotta",
    "yellow_glazed_terracotta",
    "lime_glazed_terracotta",
    "pink_glazed_terracotta",
    "gray_glazed_terracotta",
    "light_gray_glazed_terracotta",
    "cyan_glazed_terracotta",
    "purple_glazed_terracotta",
    "blue_glazed_terracotta",
    "brown_glazed_terracotta",
    "green_glazed_terracotta",
    "red_glazed_terracotta",
    "black_glazed_terracotta",
    "white_concrete",
    "orange_concrete",
    "magenta_concrete",
    "light_blue_concrete",
    "yellow_concrete",
    "lime_concrete",
    "pink_concrete",
    "gray_concrete",
    "light_gray_concrete",
    "cyan_concrete",
    "purple_concrete",
    "blue_concrete",
    "brown_concrete",
    "green_concrete",
    "red_concrete",
    "black_concrete",
    "dead_tube_coral_block",
    "dead_brain_coral_block",
    "dead_bubble_coral_block",
    "dead_fire_coral_block",
    "dead_horn_coral_block",
    "tube_coral_block",
    "brain_coral_block",
    "bubble_coral_block",
    "fire_coral_block",
    "horn_coral_block",
    "dead_tube_coral",
    "dead_brain_coral",
    "dead_bubble_coral",
    "dead_fire_coral",
    "dead_horn_coral",
    "dead_tube_coral_fan",
    "dead_brain_coral_fan",
    "dead_bubble_coral_fan",
    "dead_fire_coral_fan",
    "dead_horn_coral_fan",
    "dead_tube_coral_wall_fan",
    "dead_brain_coral_wall_fan",
    "dead_bubble_coral_wall_fan",
    "dead_fire_coral_wall_fan",
    "dead_horn_coral_wall_fan",
    "polished_granite_stairs",
    "smooth_red_sandstone_stairs",
    "mossy_stone_brick_stairs",
    "polished_diorite_stairs",
    "mossy_cobblestone_stairs",
    "end_stone_brick_stairs",
    "stone_stairs",
    "smooth_sandstone_stairs",
    "smooth_quartz_stairs",
    "granite_stairs",
    "andesite_stairs",
    "red_nether_brick_stairs",
    "polished_andesite_stairs",
    "diorite_stairs",
    "polished_granite_slab",
    "smooth_red_sandstone_slab",
    "mossy_stone_brick_slab",
    "polished_diorite_slab",
    "mossy_cobblestone_slab",
    "end_stone_brick_slab",
    "smooth_sandstone_slab",
    "smooth_quartz_slab",
    "granite_slab",
    "andesite_slab",
    "red_nether_brick_slab",
    "polished_andesite_slab",
    "diorite_slab",
    "smoker",
    "blast_furnace",
    "grindstone",
    "stonecutter",
    "bell",
    "lantern",
    "soul_lantern",
    "warped_nylium",
    "crimson_nylium",
    "netherite_block",
    "ancient_debris",
    "crying_obsidian",
    "respawn_anchor",
    "lodestone",
    "blackstone",
    "blackstone_stairs",
    "blackstone_slab",
    "polished_blackstone",
    "polished_blackstone_bricks",
    "cracked_polished_blackstone_bricks",
    "chiseled_polished_blackstone",
    "polished_blackstone_brick_slab",
    "polished_blackstone_brick_stairs",
    "gilded_blackstone",
    "polished_blackstone_stairs",
    "polished_blackstone_slab",
    "polished_blackstone_pressure_plate",
    "chiseled_nether_bricks",
    "cracked_nether_bricks",
    "quartz_bricks",
    "tuff",
    "calcite",
    "oxidized_copper",
    "weathered_copper",
    "exposed_copper",
    "copper_block",
    "copper_ore",
    "deepslate_copper_ore",
    "oxidized_cut_copper",
    "weathered_cut_copper",
    "exposed_cut_copper",
    "cut_copper",
    "oxidized_cut_copper_stairs",
    "weathered_cut_copper_stairs",
    "exposed_cut_copper_stairs",
    "cut_copper_stairs",
    "oxidized_cut_copper_slab",
    "weathered_cut_copper_slab",
    "exposed_cut_copper_slab",
    "cut_copper_slab",
    "waxed_copper_block",
    "waxed_weathered_copper",
    "waxed_exposed_copper",
    "waxed_oxidized_copper",
    "waxed_oxidized_cut_copper",
    "waxed_weathered_cut_copper",
    "waxed_exposed_cut_copper",
    "waxed_cut_copper",
    "waxed_oxidized_cut_copper_stairs",
    "waxed_weathered_cut_copper_stairs",
    "waxed_exposed_cut_copper_stairs",
    "waxed_cut_copper_stairs",
    "waxed_oxidized_cut_copper_slab",
    "waxed_weathered_cut_copper_slab",
    "waxed_exposed_cut_copper_slab",
    "waxed_cut_copper_slab",
    "lightning_rod",
    "pointed_dripstone",
    "dripstone_block",
    "deepslate",
    "cobbled_deepslate",
    "cobbled_deepslate_stairs",
    "cobbled_deepslate_slab",
    "polished_deepslate",
    "polished_deepslate_stairs",
    "polished_deepslate_slab",
    "deepslate_tiles",
    "deepslate_tile_stairs",
    "deepslate_tile_slab",
    "deepslate_bricks",
    "deepslate_brick_stairs",
    "deepslate_brick_slab",
    "chiseled_deepslate",
    "cracked_deepslate_bricks",
    "cracked_deepslate_tiles",
    "smooth_basalt",
    "raw_iron_block",
    "raw_copper_block",
    "raw_gold_block",
    "ice",
    "packed_ice",
    "blue_ice",
    "piston",
    "sticky_piston",
    "piston_head",
    "amethyst_cluster",
    "small_amethyst_bud",
    "medium_amethyst_bud",
    "large_amethyst_bud",
    "amethyst_block",
    "budding_amethyst",
    "infested_cobblestone",
    "infested_chiseled_stone_bricks",
    "infested_cracked_stone_bricks",
    "infested_deepslate",
    "infested_stone",
    "infested_mossy_stone_bricks",
    "infested_stone_bricks",
    "stone_button",
    "polished_blackstone_button",
    "cobblestone_wall",
    "mossy_cobblestone_wall",
    "brick_wall",
    "prismarine_wall",
    "red_sandstone_wall",
    "mossy_stone_brick_wall",
    "granite_wall",
    "stone_brick_wall",
    "nether_brick_wall",
    "andesite_wall",
    "red_nether_brick_wall",
    "sandstone_wall",
    "end_stone_brick_wall",
    "diorite_wall",
    "blackstone_wall",
    "polished_blackstone_brick_wall",
    "polished_blackstone_wall",
    "cobbled_deepslate_wall",
    "polished_deepslate_wall",
    "deepslate_tile_wall",
    "deepslate_brick_wall",
    "mud_brick_wall",
    "tuff_wall",
    "polished_tuff_wall",
    "tuff_brick_wall",
    "resin_brick_wall",
    "shulker_box",
    "black_shulker_box",
    "blue_shulker_box",
    "brown_shulker_box",
    "cyan_shulker_box",
    "gray_shulker_box",
    "green_shulker_box",
    "light_blue_shulker_box",
    "light_gray_shulker_box",
    "lime_shulker_box",
    "magenta_shulker_box",
    "orange_shulker_box",
    "pink_shulker_box",
    "purple_shulker_box",
    "red_shulker_box",
    "white_shulker_box",
    "yellow_shulker_box",
    "anvil",
    "chipped_anvil",
    "damaged_anvil",
    "cauldron",
    "water_cauldron",
    "lava_cauldron",
    "powder_snow_cauldron",
    "rail",
    "powered_rail",
    "detector_rail",
    "activator_rail",
    "conduit",
    "mud_bricks",
    "mud_brick_stairs",
    "mud_brick_slab",
    "packed_mud",
    "crafter",
    "tuff_slab",
    "tuff_stairs",
    "tuff_wall",
    "chiseled_tuff",
    "polished_tuff",
    "polished_tuff_slab",
    "polished_tuff_stairs",
    "polished_tuff_wall",
    "tuff_bricks",
    "tuff_brick_slab",
    "tuff_brick_stairs",
    "tuff_brick_wall",
    "chiseled_tuff_bricks",
    "chiseled_copper",
    "exposed_chiseled_copper",
    "weathered_chiseled_copper",
    "oxidized_chiseled_copper",
    "waxed_chiseled_copper",
    "waxed_exposed_chiseled_copper",
    "waxed_weathered_chiseled_copper",
    "waxed_oxidized_chiseled_copper",
    "copper_grate",
    "exposed_copper_grate",
    "weathered_copper_grate",
    "oxidized_copper_grate",
    "waxed_copper_grate",
    "waxed_exposed_copper_grate",
    "waxed_weathered_copper_grate",
    "waxed_oxidized_copper_grate",
    "copper_bulb",
    "exposed_copper_bulb",
    "weathered_copper_bulb",
    "oxidized_copper_bulb",
    "waxed_copper_bulb",
    "waxed_exposed_copper_bulb",
    "waxed_weathered_copper_bulb",
    "waxed_oxidized_copper_bulb",
    "copper_door",
    "exposed_copper_door",
    "weathered_copper_door",
    "oxidized_copper_door",
    "waxed_copper_door",
    "waxed_exposed_copper_door",
    "waxed_weathered_copper_door",
    "waxed_oxidized_copper_door",
    "copper_trapdoor",
    "exposed_copper_trapdoor",
    "weathered_copper_trapdoor",
    "oxidized_copper_trapdoor",
    "waxed_copper_trapdoor",
    "waxed_exposed_copper_trapdoor",
    "waxed_weathered_copper_trapdoor",
    "waxed_oxidized_copper_trapdoor",
    "heavy_core",
    "resin_bricks",
    "resin_brick_slab",
    "resin_brick_wall",
    "resin_brick_stairs",
    "chiseled_resin_bricks"
};

inline std::vector<std::string> mineable_shovel = {
    "clay",
    "dirt",
    "coarse_dirt",
    "podzol",
    "farmland",
    "grass_block",
    "gravel",
    "mycelium",
    "sand",
    "red_sand",
    "snow_block",
    "snow",
    "soul_sand",
    "dirt_path",
    "soul_soil",
    "rooted_dirt",
    "muddy_mangrove_roots",
    "mud",
    "suspicious_sand",
    "suspicious_gravel",
    "white_concrete_powder",
    "orange_concrete_powder",
    "magenta_concrete_powder",
    "light_blue_concrete_powder",
    "yellow_concrete_powder",
    "lime_concrete_powder",
    "pink_concrete_powder",
    "gray_concrete_powder",
    "light_gray_concrete_powder",
    "cyan_concrete_powder",
    "purple_concrete_powder",
    "blue_concrete_powder",
    "brown_concrete_powder",
    "green_concrete_powder",
    "red_concrete_powder",
    "black_concrete_powder"
};

inline std::unordered_map<std::string, std::vector<std::string>> tagMap = {
    { "acacia_logs", acacia_logs },
    { "air", air },
    { "all_hanging_signs", all_hanging_signs },
    { "all_signs", all_signs },
    { "ancient_city_replaceable", ancient_city_replaceable },
    { "animals_spawnable_on", animals_spawnable_on },
    { "anvil", anvil },
    { "armadillo_spawnable_on", armadillo_spawnable_on },
    { "axolotls_spawnable_on", axolotls_spawnable_on },
    { "azalea_grows_on", azalea_grows_on },
    { "azalea_root_replaceable", azalea_root_replaceable },
    { "badlands_terracotta", badlands_terracotta },
    { "bamboo_blocks", bamboo_blocks },
    { "bamboo_plantable_on", bamboo_plantable_on },
    { "banners", banners },
    { "base_stone_nether", base_stone_nether },
    { "base_stone_overworld", base_stone_overworld },
    { "bats_spawnable_on", bats_spawnable_on },
    { "beacon_base_blocks", beacon_base_blocks },
    { "beds", beds },
    { "beehives", beehives },
    { "bee_attractive", bee_attractive },
    { "bee_growables", bee_growables },
    { "big_dripleaf_placeable", big_dripleaf_placeable },
    { "birch_logs", birch_logs },
    { "blocks_wind_charge_explosions", blocks_wind_charge_explosions },
    { "buttons", buttons },
    { "camels_spawnable_on", camels_spawnable_on },
    { "camel_sand_step_sound_blocks", camel_sand_step_sound_blocks },
    { "campfires", campfires },
    { "candles", candles },
    { "candle_cakes", candle_cakes },
    { "cauldrons", cauldrons },
    { "cave_vines", cave_vines },
    { "ceiling_hanging_signs", ceiling_hanging_signs },
    { "cherry_logs", cherry_logs },
    { "climbable", climbable },
    { "coal_ores", coal_ores },
    { "combination_step_sound_blocks", combination_step_sound_blocks },
    { "completes_find_tree_tutorial", completes_find_tree_tutorial },
    { "concrete_powder", concrete_powder },
    { "convertable_to_mud", convertable_to_mud },
    { "copper_ores", copper_ores },
    { "corals", corals },
    { "coral_blocks", coral_blocks },
    { "coral_plants", coral_plants },
    { "crimson_stems", crimson_stems },
    { "crops", crops },
    { "crystal_sound_blocks", crystal_sound_blocks },
    { "dampens_vibrations", dampens_vibrations },
    { "dark_oak_logs", dark_oak_logs },
    { "deepslate_ore_replaceables", deepslate_ore_replaceables },
    { "diamond_ores", diamond_ores },
    { "dirt", dirt },
    { "does_not_block_hoppers", does_not_block_hoppers },
    { "doors", doors },
    { "dragon_immune", dragon_immune },
    { "dragon_transparent", dragon_transparent },
    { "dripstone_replaceable_blocks", dripstone_replaceable_blocks },
    { "dry_vegetation_may_place_on", dry_vegetation_may_place_on },
    { "edible_for_sheep", edible_for_sheep },
    { "emerald_ores", emerald_ores },
    { "enchantment_power_provider", enchantment_power_provider },
    { "enchantment_power_transmitter", enchantment_power_transmitter },
    { "enderman_holdable", enderman_holdable },
    { "fall_damage_resetting", fall_damage_resetting },
    { "features_cannot_replace", features_cannot_replace },
    { "fences", fences },
    { "fence_gates", fence_gates },
    { "fire", fire },
    { "flowers", flowers },
    { "flower_pots", flower_pots },
    { "foxes_spawnable_on", foxes_spawnable_on },
    { "frogs_spawnable_on", frogs_spawnable_on },
    { "frog_prefer_jump_to", frog_prefer_jump_to },
    { "geode_invalid_blocks", geode_invalid_blocks },
    { "goats_spawnable_on", goats_spawnable_on },
    { "gold_ores", gold_ores },
    { "guarded_by_piglins", guarded_by_piglins },
    { "happy_ghast_avoids", happy_ghast_avoids },
    { "hoglin_repellents", hoglin_repellents },
    { "ice", ice },
    { "impermeable", impermeable },
    { "incorrect_for_diamond_tool", incorrect_for_diamond_tool },
    { "incorrect_for_gold_tool", incorrect_for_gold_tool },
    { "incorrect_for_iron_tool", incorrect_for_iron_tool },
    { "incorrect_for_netherite_tool", incorrect_for_netherite_tool },
    { "incorrect_for_stone_tool", incorrect_for_stone_tool },
    { "incorrect_for_wooden_tool", incorrect_for_wooden_tool },
    { "infiniburn_end", infiniburn_end },
    { "infiniburn_nether", infiniburn_nether },
    { "infiniburn_overworld", infiniburn_overworld },
    { "inside_step_sound_blocks", inside_step_sound_blocks },
    { "invalid_spawn_inside", invalid_spawn_inside },
    { "iron_ores", iron_ores },
    { "jungle_logs", jungle_logs },
    { "lapis_ores", lapis_ores },
    { "lava_pool_stone_cannot_replace", lava_pool_stone_cannot_replace },
    { "leaves", leaves },
    { "logs", logs },
    { "logs_that_burn", logs_that_burn },
    { "lush_ground_replaceable", lush_ground_replaceable },
    { "maintains_farmland", maintains_farmland },
    { "mangrove_logs", mangrove_logs },
    { "mangrove_logs_can_grow_through", mangrove_logs_can_grow_through },
    { "mangrove_roots_can_grow_through", mangrove_roots_can_grow_through },
    { "mob_interactable_doors", mob_interactable_doors },
    { "mooshrooms_spawnable_on", mooshrooms_spawnable_on },
    { "moss_replaceable", moss_replaceable },
    { "mushroom_grow_block", mushroom_grow_block },
    { "needs_diamond_tool", needs_diamond_tool },
    { "needs_iron_tool", needs_iron_tool },
    { "needs_stone_tool", needs_stone_tool },
    { "nether_carver_replaceables", nether_carver_replaceables },
    { "nylium", nylium },
    { "oak_logs", oak_logs },
    { "occludes_vibration_signals", occludes_vibration_signals },
    { "overworld_carver_replaceables", overworld_carver_replaceables },
    { "overworld_natural_logs", overworld_natural_logs },
    { "pale_oak_logs", pale_oak_logs },
    { "parrots_spawnable_on", parrots_spawnable_on },
    { "piglin_repellents", piglin_repellents },
    { "planks", planks },
    { "polar_bears_spawnable_on_alternate", polar_bears_spawnable_on_alternate },
    { "portals", portals },
    { "pressure_plates", pressure_plates },
    { "prevent_mob_spawning_inside", prevent_mob_spawning_inside },
    { "rabbits_spawnable_on", rabbits_spawnable_on },
    { "rails", rails },
    { "redstone_ores", redstone_ores },
    { "replaceable", replaceable },
    { "replaceable_by_mushrooms", replaceable_by_mushrooms },
    { "replaceable_by_trees", replaceable_by_trees },
    { "sand", sand },
    { "saplings", saplings },
    { "sculk_replaceable", sculk_replaceable },
    { "sculk_replaceable_world_gen", sculk_replaceable_world_gen },
    { "shulker_boxes", shulker_boxes },
    { "signs", signs },
    { "slabs", slabs },
    { "small_dripleaf_placeable", small_dripleaf_placeable },
    { "small_flowers", small_flowers },
    { "smelts_to_glass", smelts_to_glass },
    { "snaps_goat_horn", snaps_goat_horn },
    { "sniffer_diggable_block", sniffer_diggable_block },
    { "sniffer_egg_hatch_boost", sniffer_egg_hatch_boost },
    { "snow", snow },
    { "snow_layer_cannot_survive_on", snow_layer_cannot_survive_on },
    { "snow_layer_can_survive_on", snow_layer_can_survive_on },
    { "soul_fire_base_blocks", soul_fire_base_blocks },
    { "soul_speed_blocks", soul_speed_blocks },
    { "spruce_logs", spruce_logs },
    { "stairs", stairs },
    { "standing_signs", standing_signs },
    { "stone_bricks", stone_bricks },
    { "stone_buttons", stone_buttons },
    { "stone_ore_replaceables", stone_ore_replaceables },
    { "stone_pressure_plates", stone_pressure_plates },
    { "strider_warm_blocks", strider_warm_blocks },
    { "sword_efficient", sword_efficient },
    { "sword_instantly_mines", sword_instantly_mines },
    { "terracotta", terracotta },
    { "trail_ruins_replaceable", trail_ruins_replaceable },
    { "trapdoors", trapdoors },
    { "triggers_ambient_desert_dry_vegetation_block_sounds", triggers_ambient_desert_dry_vegetation_block_sounds },
    { "triggers_ambient_desert_sand_block_sounds", triggers_ambient_desert_sand_block_sounds },
    { "triggers_ambient_dried_ghast_block_sounds", triggers_ambient_dried_ghast_block_sounds },
    { "underwater_bonemeals", underwater_bonemeals },
    { "unstable_bottom_center", unstable_bottom_center },
    { "valid_spawn", valid_spawn },
    { "vibration_resonators", vibration_resonators },
    { "walls", walls },
    { "wall_corals", wall_corals },
    { "wall_hanging_signs", wall_hanging_signs },
    { "wall_post_override", wall_post_override },
    { "wall_signs", wall_signs },
    { "warped_stems", warped_stems },
    { "wart_blocks", wart_blocks },
    { "wither_immune", wither_immune },
    { "wither_summon_base_blocks", wither_summon_base_blocks },
    { "wolves_spawnable_on", wolves_spawnable_on },
    { "wooden_buttons", wooden_buttons },
    { "wooden_doors", wooden_doors },
    { "wooden_fences", wooden_fences },
    { "wooden_pressure_plates", wooden_pressure_plates },
    { "wooden_slabs", wooden_slabs },
    { "wooden_stairs", wooden_stairs },
    { "wooden_trapdoors", wooden_trapdoors },
    { "wool", wool },
    { "wool_carpets", wool_carpets },
    { "mineable/axe", mineable_axe },
    { "mineable/hoe", mineable_hoe },
    { "mineable/pickaxe", mineable_pickaxe },
    { "mineable/shovel", mineable_shovel },
};
