#include "SoundDescriptions.hpp"

const std::unordered_map<std::string, std::string> SoundDescriptions::soundDescriptions = {
    {"ambient.basalt_deltas.additions", "Eerie basalt delta sounds"},
    {"ambient.basalt_deltas.loop", "Basalt deltas atmosphere"},
    {"ambient.basalt_deltas.mood", "Ominous basalt delta ambience"},
    {"ambient.candle", "Candle flickering"},
    {"ambient.cave", "Eerie cave sounds"},
    {"ambient.crimson_forest.additions", "Crimson forest sounds"},
    {"ambient.crimson_forest.loop", "Crimson forest atmosphere"},
    {"ambient.crimson_forest.mood", "Unsettling crimson forest ambience"},
    {"ambient.nether_wastes.additions", "Nether wastes sounds"},
    {"ambient.nether_wastes.loop", "Nether wastes atmosphere"},
    {"ambient.nether_wastes.mood", "Ominous nether wastes ambience"},
    {"ambient.soulsand_valley.additions", "Soul sand valley sounds"},
    {"ambient.soulsand_valley.loop", "Soul sand valley atmosphere"},
    {"ambient.soulsand_valley.mood", "Haunting soul sand valley ambience"},
    {"ambient.underwater.enter", "Entering underwater"},
    {"ambient.underwater.exit", "Exiting underwater"},
    {"ambient.warped_forest.additions", "Warped forest sounds"},
    {"ambient.warped_forest.loop", "Warped forest atmosphere"},
    {"ambient.warped_forest.mood", "Mysterious warped forest ambience"},
    {"ambient.weather.lightning.impact", "Lightning strikes"},
    {"ambient.weather.rain", "Rain falls"},
    {"ambient.weather.the_end_light_flash", "End light flashes"},
    {"ambient.weather.thunder", "Thunder rumbles"},
    {"apply_effect.bad_omen", "Bad Omen takes hold"},
    {"apply_effect.raid_omen", "Raid Omen looms"},
    {"apply_effect.trial_omen", "Trial Omen appears"},
    {"armor.break_wolf", "Wolf armor breaks"},
    {"armor.crack_wolf", "Wolf armor cracks"},
    {"armor.damage_wolf", "Wolf armor takes damage"},
    {"armor.equip_chain", "Chain armor jingles"},
    {"armor.equip_diamond", "Diamond armor clangs"},
    {"armor.equip_generic", "Armor equips"},
    {"armor.equip_gold", "Gold armor clinks"},
    {"armor.equip_iron", "Iron armor clanks"},
    {"armor.equip_leather", "Leather armor rustles"},
    {"armor.equip_netherite", "Netherite armor clanks"},
    {"armor.equip_wolf", "Wolf armor fastens"},
    {"armor.repair_wolf", "Wolf armor is repaired"},
    {"armor.unequip_wolf", "Wolf armor snips away"},
    {"balloon.pop", "Balloon pops"},
    {"beacon.activate", "Beacon activates"},
    {"beacon.ambient", "Beacon hums"},
    {"beacon.deactivate", "Beacon deactivates"},
    {"beacon.power", "Beacon power selected"},
    {"block.bamboo.break", "Bamboo breaks"},
    {"block.bamboo.fall", "Bamboo falls"},
    {"block.bamboo.hit", "Bamboo breaking"},
    {"block.bamboo.place", "Bamboo placed"},
    {"block.bamboo.step", "Footsteps on bamboo"},
    {"block.bamboo_sapling.break", "Bamboo sapling breaks"},
    {"block.bamboo_sapling.place", "Bamboo sapling placed"},
    {"block.barrel.close", "Barrel closes"},
    {"block.barrel.open", "Barrel opens"},
    {"block.beehive.drip", "Honey drips"},
    {"block.beehive.enter", "Bee enters hive"},
    {"block.beehive.exit", "Bee leaves hive"},
    {"block.beehive.shear", "Shears scrape"},
    {"block.beehive.work", "Bees work"},
    {"block.bell.hit", "Bell rings"},
    {"block.blastfurnace.fire_crackle", "Blast furnace crackles"},
    {"block.bowhit", "Arrow hits"},
    {"block.cactus_flower.break", "Cactus flower breaks"},
    {"block.cactus_flower.place", "Cactus flower placed"},
    {"block.campfire.crackle", "Campfire crackles"},
    {"block.cartography_table.use", "Cartographer works"},
    {"block.cave_vines.place", "Cave vines placed"},
    {"block.chorusflower.death", "Chorus flower withers"},
    {"block.chorusflower.grow", "Chorus flower grows"},
    {"block.click", "Button clicks"},
    {"block.composter.empty", "Composter emptied"},
    {"block.composter.fill", "Composter filled"},
    {"block.composter.fill_success", "Composter ready"},
    {"block.composter.ready", "Composter composts"},
    {"block.copper_bulb.turn_off", "Copper bulb turns off"},
    {"block.copper_bulb.turn_on", "Copper bulb turns on"},
    {"block.creaking_heart.ambient", "Creaking Heart pulses"},
    {"block.creaking_heart.break", "Creaking Heart breaks"},
    {"block.creaking_heart.fall", "Creaking Heart falls"},
    {"block.creaking_heart.hit", "Creaking Heart hit"},
    {"block.creaking_heart.place", "Creaking Heart placed"},
    {"block.creaking_heart.spawn_mob", "Creaking Heart awakens"},
    {"block.creaking_heart.step", "Footsteps on Creaking Heart"},
    {"block.creaking_heart.trail", "Creaking Heart trails"},
    {"block.deadbush.ambient", "Dry sounds"},
    {"block.decorated_pot.insert", "Decorated pot fills"},
    {"block.decorated_pot.insert_fail", "Decorated pot wobbles"},
    {"block.dried_ghast.ambient", "Sounds of dryness"},
    {"block.dried_ghast.ambient_water", "Dried ghast rehydrates"},
    {"block.dried_ghast.break", "Dried ghast breaks"},
    {"block.dried_ghast.fall", "Dried ghast falls"},
    {"block.dried_ghast.place", "Dried ghast placed"},
    {"block.dried_ghast.place_in_water", "Dried ghast soaks"},
    {"block.dried_ghast.state_change", "Dried ghast feels better"},
    {"block.dried_ghast.step", "Footsteps on dried ghast"},
    {"block.dry_grass.ambient.attached", "Windy sounds"},
    {"block.enchanting_table.use", "Enchanting table used"},
    {"block.end_portal.spawn", "End portal opens"},
    {"block.end_portal_frame.fill", "Eye of Ender attaches"},
    {"block.eyeblossom.ambient", "Eyeblossom whispers"},
    {"block.eyeblossom.close", "Eyeblossom closes"},
    {"block.eyeblossom.close_long", "Eyeblossom closes slowly"},
    {"block.eyeblossom.open", "Eyeblossom opens"},
    {"block.eyeblossom.open_long", "Eyeblossom opens slowly"},
    {"block.false_permissions", "Permission denied"},
    {"block.firefly_bush.ambient", "Fireflies buzz"},
    {"block.furnace.lit", "Furnace crackles"},
    {"block.grindstone.use", "Grindstone used"},
    {"block.itemframe.add_item", "Item frame fills"},
    {"block.itemframe.break", "Item frame broken"},
    {"block.itemframe.place", "Item frame placed"},
    {"block.itemframe.remove_item", "Item frame empties"},
    {"block.itemframe.rotate_item", "Item frame clicks"},
    {"block.lantern.break", "Lantern breaks"},
    {"block.lantern.fall", "Lantern falls"},
    {"block.lantern.hit", "Lantern hit"},
    {"block.lantern.place", "Lantern placed"},
    {"block.lantern.step", "Footsteps on lantern"},
    {"block.leaf_litter.break", "Leaf litter breaks"},
    {"block.leaf_litter.place", "Leaf litter placed"},
    {"block.leaf_litter.step", "Footsteps on leaf litter"},
    {"block.loom.use", "Loom used"},
    {"block.mangrove_roots.break", "Mangrove roots break"},
    {"block.mangrove_roots.fall", "Mangrove roots fall"},
    {"block.mangrove_roots.hit", "Mangrove roots hit"},
    {"block.mangrove_roots.place", "Mangrove roots placed"},
    {"block.mangrove_roots.step", "Footsteps on mangrove roots"},
    {"block.mob_spawner.break", "Spawner breaks"},
    {"block.mob_spawner.step", "Footsteps on spawner"},
    {"block.mud.break", "Mud breaks"},
    {"block.mud.fall", "Mud falls"},
    {"block.mud.hit", "Mud hit"},
    {"block.mud.place", "Mud placed"},
    {"block.mud.step", "Footsteps in mud"},
    {"block.mud_bricks.break", "Mud bricks break"},
    {"block.mud_bricks.fall", "Mud bricks fall"},
    {"block.mud_bricks.hit", "Mud bricks hit"},
    {"block.mud_bricks.place", "Mud bricks placed"},
    {"block.mud_bricks.step", "Footsteps on mud bricks"},
    {"block.muddy_mangrove_roots.break", "Muddy mangrove roots break"},
    {"block.muddy_mangrove_roots.fall", "Muddy mangrove roots fall"},
    {"block.muddy_mangrove_roots.hit", "Muddy mangrove roots hit"},
    {"block.muddy_mangrove_roots.place", "Muddy mangrove roots placed"},
    {"block.muddy_mangrove_roots.step", "Footsteps on muddy mangrove roots"},
    {"block.packed_mud.break", "Packed mud breaks"},
    {"block.packed_mud.fall", "Packed mud falls"},
    {"block.packed_mud.hit", "Packed mud hit"},
    {"block.packed_mud.place", "Packed mud placed"},
    {"block.packed_mud.step", "Footsteps on packed mud"},
    {"block.pale_hanging_moss.ambient", "Eerie noise"},
    {"block.resin.break", "Resin breaks"},
    {"block.resin.fall", "Resin falls"},
    {"block.resin.hit", "Resin hit"},
    {"block.resin.place", "Resin placed"},
    {"block.resin.step", "Footsteps on resin"},
    {"block.resin_brick.break", "Resin brick breaks"},
    {"block.resin_brick.fall", "Resin brick falls"},
    {"block.resin_brick.hit", "Resin brick hit"},
    {"block.resin_brick.place", "Resin brick placed"},
    {"block.resin_brick.step", "Footsteps on resin brick"},
    {"block.sand.ambient", "Sandy sounds"},
    {"block.scaffolding.break", "Scaffolding breaks"},
    {"block.scaffolding.climb", "Climbing scaffolding"},
    {"block.scaffolding.fall", "Scaffolding falls"},
    {"block.scaffolding.hit", "Scaffolding hit"},
    {"block.scaffolding.place", "Scaffolding placed"},
    {"block.scaffolding.step", "Footsteps on scaffolding"},
    {"block.sign.waxed_interact_fail", "Sign wobbles"},
    {"block.smoker.smoke", "Smoker smokes"},
    {"block.sniffer_egg.crack", "Sniffer egg cracks"},
    {"block.sniffer_egg.hatch", "Sniffer egg hatches"},
    {"block.stonecutter.use", "Stonecutter used"},
    {"block.sweet_berry_bush.break", "Sweet berry bush breaks"},
    {"block.sweet_berry_bush.hurt", "Berry bush rustles"},
    {"block.sweet_berry_bush.pick", "Berries pop"},
    {"block.sweet_berry_bush.place", "Sweet berry bush placed"},
    {"block.turtle_egg.break", "Turtle egg breaks"},
    {"block.turtle_egg.crack", "Turtle egg cracks"},
    {"block.turtle_egg.drop", "Turtle egg drops"},
    {"block.weeping_vines.break", "Weeping vines break"},
    {"block.weeping_vines.fall", "Weeping vines fall"},
    {"block.weeping_vines.hit", "Weeping vines hit"},
    {"block.weeping_vines.jump", "Jumping on weeping vines"},
    {"block.weeping_vines.land", "Landing on weeping vines"},
    {"block.weeping_vines.place", "Weeping vines placed"},
    {"block.weeping_vines.step", "Footsteps on weeping vines"},
    {"block.weeping_vines.use", "Weeping vines used"},
    {"bloom.sculk_catalyst", "Sculk catalyst blooms"},
    {"bottle.dragonbreath", "Dragon breath bottles"},
    {"bottle.empty", "Bottle empties"},
    {"bottle.fill", "Bottle fills"},
    {"break.amethyst_block", "Amethyst block breaks"},
    {"break.amethyst_cluster", "Amethyst cluster breaks"},
    {"break.azalea", "Azalea breaks"},
    {"break.bamboo_wood", "Bamboo wood breaks"},
    {"break.bamboo_wood_hanging_sign", "Bamboo hanging sign breaks"},
    {"break.big_dripleaf", "Big dripleaf breaks"},
    {"break.calcite", "Calcite breaks"},
    {"break.cherry_leaves", "Cherry leaves break"},
    {"break.cherry_wood", "Cherry wood breaks"},
    {"break.cherry_wood_hanging_sign", "Cherry hanging sign breaks"},
    {"break.chiseled_bookshelf", "Chiseled bookshelf breaks"},
    {"break.copper_bulb", "Copper bulb breaks"},
    {"break.copper_grate", "Copper grate breaks"},
    {"break.decorated_pot", "Decorated pot breaks"},
    {"break.dirt_with_roots", "Dirt with roots breaks"},
    {"break.dripstone_block", "Dripstone block breaks"},
    {"break.frog_spawn", "Frog spawn breaks"},
    {"break.froglight", "Froglight breaks"},
    {"break.hanging_roots", "Hanging roots break"},
    {"break.hanging_sign", "Hanging sign breaks"},
    {"break.heavy_core", "Heavy core breaks"},
    {"break.iron", "Iron breaks"},
    {"break.large_amethyst_bud", "Large amethyst bud breaks"},
    {"break.medium_amethyst_bud", "Medium amethyst bud breaks"},
    {"break.nether_wood", "Nether wood breaks"},
    {"break.nether_wood_hanging_sign", "Nether hanging sign breaks"},
    {"break.pink_petals", "Pink petals break"},
    {"break.pointed_dripstone", "Pointed dripstone breaks"},
    {"break.sculk", "Sculk breaks"},
    {"break.sculk_catalyst", "Sculk catalyst breaks"},
    {"break.sculk_sensor", "Sculk sensor breaks"},
    {"break.sculk_shrieker", "Sculk shrieker breaks"},
    {"break.sculk_vein", "Sculk vein breaks"},
    {"break.small_amethyst_bud", "Small amethyst bud breaks"},
    {"break.sponge", "Sponge breaks"},
    {"break.spore_blossom", "Spore blossom breaks"},
    {"break.suspicious_gravel", "Suspicious gravel breaks"},
    {"break.suspicious_sand", "Suspicious sand breaks"},
    {"break.tuff", "Tuff breaks"},
    {"break.web", "Web breaks"},
    {"break.wet_sponge", "Wet sponge breaks"},
    {"breeze_wind_charge.burst", "Wind charge bursts"},
    {"brush.generic", "Brushing"},
    {"brush.suspicious_gravel", "Brushing gravel"},
    {"brush.suspicious_sand", "Brushing sand"},
    {"brush_completed.suspicious_gravel", "Brushing gravel completed"},
    {"brush_completed.suspicious_sand", "Brushing sand completed"},
    {"bubble.down", "Bubbles sink"},
    {"bubble.downinside", "Bubbles inside"},
    {"bubble.pop", "Bubbles pop"},
    {"bubble.up", "Bubbles rise"},
    {"bubble.upinside", "Bubbles inside"},
    {"bucket.empty_fish", "Fish released"},
    {"bucket.empty_lava", "Lava bucket empties"},
    {"bucket.empty_powder_snow", "Powder snow bucket empties"},
    {"bucket.empty_water", "Water bucket empties"},
    {"bucket.fill_fish", "Fish captured"},
    {"bucket.fill_lava", "Lava bucket fills"},
    {"bucket.fill_powder_snow", "Powder snow bucket fills"},
    {"bucket.fill_water", "Water bucket fills"},
    {"bundle.drop_contents", "Bundle empties"},
    {"bundle.insert", "Item packed"},
    {"bundle.insert_fail", "Bundle full"},
    {"bundle.remove_one", "Item unpacked"},
    {"cake.add_candle", "Cake squishes"},
    {"camera.take_picture", "Camera clicks"},
    {"cauldron.adddye", "Dye added to cauldron"},
    {"cauldron.cleanarmor", "Armor cleaned in cauldron"},
    {"cauldron.cleanbanner", "Banner cleaned in cauldron"},
    {"cauldron.dyearmor", "Armor dyed in cauldron"},
    {"cauldron.explode", "Cauldron explodes"},
    {"cauldron.fillpotion", "Potion filled in cauldron"},
    {"cauldron.fillwater", "Water filled in cauldron"},
    {"cauldron.takepotion", "Potion taken from cauldron"},
    {"cauldron.takewater", "Water taken from cauldron"},
    {"cauldron_drip.lava.pointed_dripstone", "Lava drips into cauldron"},
    {"cauldron_drip.water.pointed_dripstone", "Water drips into cauldron"},
    {"charge.sculk", "Sculk bubbles"},
    {"chime.amethyst_block", "Amethyst chimes"},
    {"click_off.bamboo_wood_button", "Bamboo button clicks"},
    {"click_off.bamboo_wood_pressure_plate", "Bamboo pressure plate clicks"},
    {"click_off.cherry_wood_button", "Cherry button clicks"},
    {"click_off.cherry_wood_pressure_plate", "Cherry pressure plate clicks"},
    {"click_off.metal_pressure_plate", "Metal pressure plate clicks"},
    {"click_off.nether_wood_button", "Nether button clicks"},
    {"click_off.nether_wood_pressure_plate", "Nether pressure plate clicks"},
    {"click_off.stone_pressure_plate", "Stone pressure plate clicks"},
    {"click_off.wooden_pressure_plate", "Wooden pressure plate clicks"},
    {"click_on.bamboo_wood_button", "Bamboo button clicks"},
    {"click_on.bamboo_wood_pressure_plate", "Bamboo pressure plate clicks"},
    {"click_on.cherry_wood_button", "Cherry button clicks"},
    {"click_on.cherry_wood_pressure_plate", "Cherry pressure plate clicks"},
    {"click_on.metal_pressure_plate", "Metal pressure plate clicks"},
    {"click_on.nether_wood_button", "Nether button clicks"},
    {"click_on.nether_wood_pressure_plate", "Nether pressure plate clicks"},
    {"click_on.stone_pressure_plate", "Stone pressure plate clicks"},
    {"click_on.wooden_pressure_plate", "Wooden pressure plate clicks"},
    {"close.bamboo_wood_door", "Bamboo door closes"},
    {"close.bamboo_wood_fence_gate", "Bamboo fence gate closes"},
    {"close.bamboo_wood_trapdoor", "Bamboo trapdoor closes"},
    {"close.cherry_wood_door", "Cherry door closes"},
    {"close.cherry_wood_fence_gate", "Cherry fence gate closes"},
    {"close.cherry_wood_trapdoor", "Cherry trapdoor closes"},
    {"close.fence_gate", "Fence gate closes"},
    {"close.iron_door", "Iron door closes"},
    {"close.iron_trapdoor", "Iron trapdoor closes"},
    {"close.nether_wood_door", "Nether door closes"},
    {"close.nether_wood_fence_gate", "Nether fence gate closes"},
    {"close.nether_wood_trapdoor", "Nether trapdoor closes"},
    {"close.wooden_door", "Wooden door closes"},
    {"close.wooden_trapdoor", "Wooden trapdoor closes"},
    {"close_door.copper", "Copper door closes"},
    {"component.jump_to_block", "Jumping to block"},
    {"conduit.activate", "Conduit activates"},
    {"conduit.ambient", "Conduit pulses"},
    {"conduit.attack", "Conduit attacks"},
    {"conduit.deactivate", "Conduit deactivates"},
    {"conduit.short", "Conduit shorts"},
    {"copper.wax.off", "Wax removed"},
    {"copper.wax.on", "Wax applied"},
    {"crafter.craft", "Crafter crafts"},
    {"crafter.disable_slot", "Crafter slot disabled"},
    {"crafter.fail", "Crafter fails"},
    {"crossbow.loading.end", "Crossbow loaded"},
    {"crossbow.loading.middle", "Crossbow loading"},
    {"crossbow.loading.start", "Crossbow loading"},
    {"crossbow.quick_charge.end", "Quick charge completed"},
    {"crossbow.quick_charge.middle", "Quick charging"},
    {"crossbow.quick_charge.start", "Quick charge started"},
    {"crossbow.shoot", "Crossbow fires"},
    {"damage.fallbig", "Heavy fall damage"},
    {"damage.fallsmall", "Light fall damage"},
    {"damage.thorns", "Thorns prick"},
    {"dig.ancient_debris", "Digging ancient debris"},
    {"dig.azalea_leaves", "Digging azalea leaves"},
    {"dig.basalt", "Digging basalt"},
    {"dig.bone_block", "Digging bone block"},
    {"dig.candle", "Digging candle"},
    {"dig.cave_vines", "Digging cave vines"},
    {"dig.chain", "Digging chain"},
    {"dig.cloth", "Digging cloth"},
    {"dig.copper", "Digging copper"},
    {"dig.coral", "Digging coral"},
    {"dig.deepslate", "Digging deepslate"},
    {"dig.deepslate_bricks", "Digging deepslate bricks"},
    {"dig.fungus", "Digging fungus"},
    {"dig.grass", "Digging grass"},
    {"dig.gravel", "Digging gravel"},
    {"dig.honey_block", "Digging honey block"},
    {"dig.lodestone", "Digging lodestone"},
    {"dig.moss", "Digging moss"},
    {"dig.nether_brick", "Digging nether brick"},
    {"dig.nether_gold_ore", "Digging nether gold ore"},
    {"dig.nether_sprouts", "Digging nether sprouts"},
    {"dig.nether_wart", "Digging nether wart"},
    {"dig.netherite", "Digging netherite"},
    {"dig.netherrack", "Digging netherrack"},
    {"dig.nylium", "Digging nylium"},
    {"dig.powder_snow", "Digging powder snow"},
    {"dig.roots", "Digging roots"},
    {"dig.sand", "Digging sand"},
    {"dig.shroomlight", "Digging shroomlight"},
    {"dig.snow", "Digging snow"},
    {"dig.soul_sand", "Digging soul sand"},
    {"dig.soul_soil", "Digging soul soil"},
    {"dig.stem", "Digging stem"},
    {"dig.stone", "Digging stone"},
    {"dig.vines", "Digging vines"},
    {"dig.wood", "Digging wood"},
    {"drip.lava.pointed_dripstone", "Lava drips"},
    {"drip.water.pointed_dripstone", "Water drips"},
    {"elemconstruct.active", "Element construct active"},
    {"elytra.loop", "Elytra flying"},
    {"entity.generic.splash", "Splashing"},
    {"entity.wither_skeleton.ambient", "Wither skeleton rattles"},
    {"entity.wither_skeleton.death", "Wither skeleton dies"},
    {"entity.wither_skeleton.hurt", "Wither skeleton hurts"},
    {"entity.wither_skeleton.step", "Wither skeleton steps"},
    {"entity.zombie.converted_to_drowned", "Zombie converts to drowned"},
    {"extinguish.candle", "Candle extinguishes"},
    {"fall.amethyst_block", "Falling on amethyst block"},
    {"fall.amethyst_cluster", "Falling on amethyst cluster"},
    {"fall.ancient_debris", "Falling on ancient debris"},
    {"fall.azalea", "Falling on azalea"},
    {"fall.azalea_leaves", "Falling on azalea leaves"},
    {"fall.bamboo_wood", "Falling on bamboo wood"},
    {"fall.basalt", "Falling on basalt"},
    {"fall.big_dripleaf", "Falling on big dripleaf"},
    {"fall.bone_block", "Falling on bone block"},
    {"fall.calcite", "Falling on calcite"},
    {"fall.cave_vines", "Falling on cave vines"},
    {"fall.chain", "Falling on chain"},
    {"fall.cherry_leaves", "Falling on cherry leaves"},
    {"fall.cherry_wood", "Falling on cherry wood"},
    {"fall.cloth", "Falling on cloth"},
    {"fall.copper", "Falling on copper"},
    {"fall.copper_bulb", "Falling on copper bulb"},
    {"fall.coral", "Falling on coral"},
    {"fall.deepslate", "Falling on deepslate"},
    {"fall.deepslate_bricks", "Falling on deepslate bricks"},
    {"fall.dirt_with_roots", "Falling on dirt with roots"},
    {"fall.dripstone_block", "Falling on dripstone block"},
    {"fall.egg", "Egg falls"},
    {"fall.grass", "Falling on grass"},
    {"fall.gravel", "Falling on gravel"},
    {"fall.hanging_roots", "Falling on hanging roots"},
    {"fall.honey_block", "Falling on honey block"},
    {"fall.ladder", "Falling on ladder"},
    {"fall.moss", "Falling on moss"},
    {"fall.nether_brick", "Falling on nether brick"},
    {"fall.nether_gold_ore", "Falling on nether gold ore"},
    {"fall.nether_sprouts", "Falling on nether sprouts"},
    {"fall.nether_wart", "Falling on nether wart"},
    {"fall.nether_wood", "Falling on nether wood"},
    {"fall.netherite", "Falling on netherite"},
    {"fall.netherrack", "Falling on netherrack"},
    {"fall.nylium", "Falling on nylium"},
    {"fall.pink_petals", "Falling on pink petals"},
    {"fall.pointed_dripstone", "Falling on pointed dripstone"},
    {"fall.powder_snow", "Falling on powder snow"},
    {"fall.roots", "Falling on roots"},
    {"fall.sand", "Falling on sand"},
    {"fall.sculk_sensor", "Falling on sculk sensor"},
    {"fall.sculk_shrieker", "Falling on sculk shrieker"},
    {"fall.shroomlight", "Falling on shroomlight"},
    {"fall.slime", "Falling on slime"},
    {"fall.snow", "Falling on snow"},
    {"fall.soul_sand", "Falling on soul sand"},
    {"fall.soul_soil", "Falling on soul soil"},
    {"fall.spore_blossom", "Falling on spore blossom"},
    {"fall.stem", "Falling on stem"},
    {"fall.stone", "Falling on stone"},
    {"fall.tuff", "Falling on tuff"},
    {"fall.vines", "Falling on vines"},
    {"fall.wood", "Falling on wood"},
    {"fire.fire", "Fire crackles"},
    {"fire.ignite", "Fire ignites"},
    {"firework.blast", "Firework blasts"},
    {"firework.large_blast", "Large firework blast"},
    {"firework.launch", "Firework launches"},
    {"firework.shoot", "Firework shoots"},
    {"firework.twinkle", "Firework twinkles"},
    {"game.player.attack.nodamage", "Weak attack"},
    {"game.player.attack.strong", "Strong attack"},
    {"game.player.die", "Player dies"},
    {"game.player.hurt", "Player hurts"},
    {"hatch.frog_spawn", "Tadpole hatches"},
    {"hit.amethyst_block", "Amethyst block hit"},
    {"hit.amethyst_cluster", "Amethyst cluster hit"},
    {"hit.ancient_debris", "Ancient debris hit"},
    {"hit.anvil", "Anvil hit"},
    {"hit.azalea", "Azalea hit"},
    {"hit.azalea_leaves", "Azalea leaves hit"},
    {"hit.bamboo_wood", "Bamboo wood hit"},
    {"hit.basalt", "Basalt hit"},
    {"hit.big_dripleaf", "Big dripleaf hit"},
    {"hit.bone_block", "Bone block hit"},
    {"hit.calcite", "Calcite hit"},
    {"hit.candle", "Candle hit"},
    {"hit.cave_vines", "Cave vines hit"},
    {"hit.chain", "Chain hit"},
    {"hit.cherry_leaves", "Cherry leaves hit"},
    {"hit.cherry_wood", "Cherry wood hit"},
    {"hit.chiseled_bookshelf", "Chiseled bookshelf hit"},
    {"hit.cloth", "Cloth hit"},
    {"hit.copper", "Copper hit"},
    {"hit.copper_bulb", "Copper bulb hit"},
    {"hit.coral", "Coral hit"},
    {"hit.deepslate", "Deepslate hit"},
    {"hit.deepslate_bricks", "Deepslate bricks hit"},
    {"hit.dirt_with_roots", "Dirt with roots hit"},
    {"hit.dripstone_block", "Dripstone block hit"},
    {"hit.grass", "Grass hit"},
    {"hit.gravel", "Gravel hit"},
    {"hit.hanging_roots", "Hanging roots hit"},
    {"hit.honey_block", "Honey block hit"},
    {"hit.iron", "Iron hit"},
    {"hit.ladder", "Ladder hit"},
    {"hit.moss", "Moss hit"},
    {"hit.nether_brick", "Nether brick hit"},
    {"hit.nether_gold_ore", "Nether gold ore hit"},
    {"hit.nether_sprouts", "Nether sprouts hit"},
    {"hit.nether_wart", "Nether wart hit"},
    {"hit.nether_wood", "Nether wood hit"},
    {"hit.netherite", "Netherite hit"},
    {"hit.netherrack", "Netherrack hit"},
    {"hit.nylium", "Nylium hit"},
    {"hit.pink_petals", "Pink petals hit"},
    {"hit.pointed_dripstone", "Pointed dripstone hit"},
    {"hit.powder_snow", "Powder snow hit"},
    {"hit.roots", "Roots hit"},
    {"hit.sand", "Sand hit"},
    {"hit.sculk", "Sculk hit"},
    {"hit.sculk_catalyst", "Sculk catalyst hit"},
    {"hit.sculk_sensor", "Sculk sensor hit"},
    {"hit.sculk_shrieker", "Sculk shrieker hit"},
    {"hit.shroomlight", "Shroomlight hit"},
    {"hit.slime", "Slime hit"},
    {"hit.snow", "Snow hit"},
    {"hit.soul_sand", "Soul sand hit"},
    {"hit.soul_soil", "Soul soil hit"},
    {"hit.sponge", "Sponge hit"},
    {"hit.spore_blossom", "Spore blossom hit"},
    {"hit.stem", "Stem hit"},
    {"hit.stone", "Stone hit"},
    {"hit.suspicious_gravel", "Suspicious gravel hit"},
    {"hit.suspicious_sand", "Suspicious sand hit"},
    {"hit.tuff", "Tuff hit"},
    {"hit.vines", "Vines hit"},
    {"hit.wet_sponge", "Wet sponge hit"},
    {"hit.wood", "Wood hit"},
    {"horn.call.0", "Goat horn plays"},
    {"horn.call.1", "Goat horn plays"},
    {"horn.call.2", "Goat horn plays"},
    {"horn.call.3", "Goat horn plays"},
    {"horn.call.4", "Goat horn plays"},
    {"horn.call.5", "Goat horn plays"},
    {"horn.call.6", "Goat horn plays"},
    {"horn.call.7", "Goat horn plays"},
    {"hud.bubble.pop", "Breath meter dropping"},
    {"insert.chiseled_bookshelf", "Book placed"},
    {"insert_enchanted.chiseled_bookshelf", "Enchanted book placed"},
    {"item.bone_meal.use", "Bone meal crinkles"},
    {"item.book.page_turn", "Page rustles"},
    {"item.book.put", "Book thumps"},
    {"item.shield.block", "Shield blocks"},
    {"item.spyglass.stop_using", "Spyglass retracts"},
    {"item.spyglass.use", "Spyglass expands"},
    {"item.trident.hit", "Trident stabs"},
    {"item.trident.hit_ground", "Trident vibrates"},
    {"item.trident.return", "Trident returns"},
    {"item.trident.riptide_1", "Trident zooms"},
    {"item.trident.riptide_2", "Trident zooms"},
    {"item.trident.riptide_3", "Trident zooms"},
    {"item.trident.throw", "Trident clangs"},
    {"item.trident.thunder", "Trident thunder cracks"},
    {"jump.ancient_debris", "Jumping on ancient debris"},
    {"jump.azalea", "Jumping on azalea"},
    {"jump.basalt", "Jumping on basalt"},
    {"jump.big_dripleaf", "Jumping on big dripleaf"},
    {"jump.bone_block", "Jumping on bone block"},
    {"jump.cave_vines", "Jumping on cave vines"},
    {"jump.chain", "Jumping on chain"},
    {"jump.cloth", "Jumping on cloth"},
    {"jump.coral", "Jumping on coral"},
    {"jump.deepslate", "Jumping on deepslate"},
    {"jump.deepslate_bricks", "Jumping on deepslate bricks"},
    {"jump.dirt_with_roots", "Jumping on dirt with roots"},
    {"jump.dripstone_block", "Jumping on dripstone block"},
    {"jump.grass", "Jumping on grass"},
    {"jump.gravel", "Jumping on gravel"},
    {"jump.hanging_roots", "Jumping on hanging roots"},
    {"jump.honey_block", "Jumping on honey block"},
    {"jump.moss", "Jumping on moss"},
    {"jump.nether_brick", "Jumping on nether brick"},
    {"jump.nether_gold_ore", "Jumping on nether gold ore"},
    {"jump.nether_sprouts", "Jumping on nether sprouts"},
    {"jump.nether_wart", "Jumping on nether wart"},
    {"jump.netherite", "Jumping on netherite"},
    {"jump.netherrack", "Jumping on netherrack"},
    {"jump.nylium", "Jumping on nylium"},
    {"jump.pointed_dripstone", "Jumping on pointed dripstone"},
    {"jump.roots", "Jumping on roots"},
    {"jump.sand", "Jumping on sand"},
    {"jump.sculk_sensor", "Jumping on sculk sensor"},
    {"jump.shroomlight", "Jumping on shroomlight"},
    {"jump.slime", "Jumping on slime"},
    {"jump.snow", "Jumping on snow"},
    {"jump.soul_sand", "Jumping on soul sand"},
    {"jump.soul_soil", "Jumping on soul soil"},
    {"jump.spore_blossom", "Jumping on spore blossom"},
    {"jump.stem", "Jumping on stem"},
    {"jump.stone", "Jumping on stone"},
    {"jump.vines", "Jumping on vines"},
    {"jump.wood", "Jumping on wood"},
    {"land.ancient_debris", "Landing on ancient debris"},
    {"land.azalea", "Landing on azalea"},
    {"land.basalt", "Landing on basalt"},
    {"land.big_dripleaf", "Landing on big dripleaf"},
    {"land.bone_block", "Landing on bone block"},
    {"land.cave_vines", "Landing on cave vines"},
    {"land.chain", "Landing on chain"},
    {"land.cloth", "Landing on cloth"},
    {"land.coral", "Landing on coral"},
    {"land.deepslate", "Landing on deepslate"},
    {"land.deepslate_bricks", "Landing on deepslate bricks"},
    {"land.dirt_with_roots", "Landing on dirt with roots"},
    {"land.dripstone_block", "Landing on dripstone block"},
    {"land.grass", "Landing on grass"},
    {"land.gravel", "Landing on gravel"},
    {"land.hanging_roots", "Landing on hanging roots"},
    {"land.honey_block", "Landing on honey block"},
    {"land.moss", "Landing on moss"},
    {"land.nether_brick", "Landing on nether brick"},
    {"land.nether_gold_ore", "Landing on nether gold ore"},
    {"land.nether_sprouts", "Landing on nether sprouts"},
    {"land.nether_wart", "Landing on nether wart"},
    {"land.netherite", "Landing on netherite"},
    {"land.netherrack", "Landing on netherrack"},
    {"land.nylium", "Landing on nylium"},
    {"land.pointed_dripstone", "Landing on pointed dripstone"},
    {"land.roots", "Landing on roots"},
    {"land.sand", "Landing on sand"},
    {"land.sculk_sensor", "Landing on sculk sensor"},
    {"land.shroomlight", "Landing on shroomlight"},
    {"land.slime", "Landing on slime"},
    {"land.snow", "Landing on snow"},
    {"land.soul_sand", "Landing on soul sand"},
    {"land.soul_soil", "Landing on soul soil"},
    {"land.spore_blossom", "Landing on spore blossom"},
    {"land.stem", "Landing on stem"},
    {"land.stone", "Landing on stone"},
    {"land.vines", "Landing on vines"},
    {"land.wood", "Landing on wood"},
    {"lead.break", "Lead snaps"},
    {"leashknot.break", "Leash knot broken"},
    {"leashknot.place", "Leash knot tied"},
    {"liquid.lava", "Lava pops"},
    {"liquid.lavapop", "Lava pops"},
    {"liquid.water", "Water flows"},
    {"lodestone_compass.link_compass_to_lodestone", "Lodestone compass locks onto lodestone"},
    {"lt.reaction.fire", "Fire reaction"},
    {"mace.heavy_smash_ground", "Mace smashes heavily"},
    {"mace.smash_air", "Mace smashes"},
    {"mace.smash_ground", "Mace smashes ground"},
    {"minecart.base", "Minecart rolls"},
    {"minecart.inside", "Minecart jangles"},
    {"mob.agent.spawn", "Agent spawns"},
    {"mob.allay.death", "Allay dies"},
    {"mob.allay.hurt", "Allay hurts"},
    {"mob.allay.idle", "Allay yearns"},
    {"mob.allay.idle_holding", "Allay seeks"},
    {"mob.allay.item_given", "Allay chortles"},
    {"mob.allay.item_taken", "Allay allays"},
    {"mob.allay.item_thrown", "Allay tosses"},
    {"mob.armadillo.ambient", "Armadillo grunts"},
    {"mob.armadillo.brush", "Scute is brushed off"},
    {"mob.armadillo.death", "Armadillo dies"},
    {"mob.armadillo.eat", "Armadillo eats"},
    {"mob.armadillo.hurt", "Armadillo hurts"},
    {"mob.armadillo.hurt_reduced", "Armadillo shields itself"},
    {"mob.armadillo.land", "Armadillo lands"},
    {"mob.armadillo.peek", "Armadillo peeks"},
    {"mob.armadillo.roll", "Armadillo rolls up"},
    {"mob.armadillo.scute_drop", "Armadillo sheds scute"},
    {"mob.armadillo.step", "Armadillo steps"},
    {"mob.armadillo.unroll_finish", "Armadillo unrolls"},
    {"mob.armadillo.unroll_start", "Armadillo peeks"},
    {"mob.armor_stand.break", "Armor stand broken"},
    {"mob.armor_stand.hit", "Armor stand hit"},
    {"mob.armor_stand.land", "Something fell"},
    {"mob.armor_stand.place", "Armor stand placed"},
    {"mob.axolotl.attack", "Axolotl attacks"},
    {"mob.axolotl.death", "Axolotl dies"},
    {"mob.axolotl.hurt", "Axolotl hurts"},
    {"mob.axolotl.idle", "Axolotl chirps"},
    {"mob.axolotl.idle_water", "Axolotl chirps"},
    {"mob.axolotl.splash", "Axolotl splashes"},
    {"mob.axolotl.swim", "Axolotl swims"},
    {"mob.bat.death", "Bat dies"},
    {"mob.bat.hurt", "Bat hurts"},
    {"mob.bat.idle", "Bat screeches"},
    {"mob.bat.takeoff", "Bat takes off"},
    {"mob.bee.aggressive", "Bee buzzes angrily"},
    {"mob.bee.death", "Bee dies"},
    {"mob.bee.hurt", "Bee hurts"},
    {"mob.bee.loop", "Bee buzzes"},
    {"mob.bee.pollinate", "Bee buzzes happily"},
    {"mob.bee.sting", "Bee stings"},
    {"mob.blaze.breathe", "Blaze breathes"},
    {"mob.blaze.death", "Blaze dies"},
    {"mob.blaze.hit", "Blaze hurts"},
    {"mob.blaze.shoot", "Blaze shoots"},
    {"mob.bogged.ambient", "Bogged rattles"},
    {"mob.bogged.death", "Bogged dies"},
    {"mob.bogged.hurt", "Bogged hurts"},
    {"mob.bogged.step", "Bogged steps"},
    {"mob.breeze.charge", "Breeze charges"},
    {"mob.breeze.death", "Breeze dies"},
    {"mob.breeze.deflect", "Breeze deflects"},
    {"mob.breeze.hurt", "Breeze hurts"},
    {"mob.breeze.idle_air", "Breeze flies"},
    {"mob.breeze.idle_ground", "Breeze whirs"},
    {"mob.breeze.inhale", "Breeze inhales"},
    {"mob.breeze.jump", "Breeze jumps"},
    {"mob.breeze.land", "Breeze lands"},
    {"mob.breeze.shoot", "Breeze shoots"},
    {"mob.breeze.slide", "Breeze slides"},
    {"mob.breeze.whirl", "Breeze whirls"},
    {"mob.camel.ambient", "Camel grunts"},
    {"mob.camel.dash", "Camel yeets"},
    {"mob.camel.dash_ready", "Camel recovers"},
    {"mob.camel.death", "Camel dies"},
    {"mob.camel.eat", "Camel eats"},
    {"mob.camel.hurt", "Camel hurts"},
    {"mob.camel.sit", "Camel sits down"},
    {"mob.camel.stand", "Camel stands up"},
    {"mob.camel.step", "Camel steps"},
    {"mob.camel.step_sand", "Camel sands"},
    {"mob.cat.beg", "Cat begs"},
    {"mob.cat.beg_for_food", "Cat begs"},
    {"mob.cat.eat", "Cat eats"},
    {"mob.cat.hiss", "Cat hisses"},
    {"mob.cat.hit", "Cat hurts"},
    {"mob.cat.meow", "Cat meows"},
    {"mob.cat.purr", "Cat purrs"},
    {"mob.cat.purreow", "Cat meows"},
    {"mob.cat.straymeow", "Cat meows"},
    {"mob.chicken.hurt", "Chicken hurts"},
    {"mob.chicken.plop", "Chicken plops"},
    {"mob.chicken.say", "Chicken clucks"},
    {"mob.chicken.step", "Chicken steps"},
    {"mob.cow.hurt", "Cow hurts"},
    {"mob.cow.milk", "Cow gets milked"},
    {"mob.cow.say", "Cow moos"},
    {"mob.cow.step", "Cow steps"},
    {"mob.creaking.activate", "Creaking watches"},
    {"mob.creaking.ambient", "Creaking creaks"},
    {"mob.creaking.attack", "Creaking attacks"},
    {"mob.creaking.deactivate", "Creaking calms"},
    {"mob.creaking.death", "Creaking crumbles"},
    {"mob.creaking.freeze", "Creaking stops"},
    {"mob.creaking.spawn", "Creaking manifests"},
    {"mob.creaking.step", "Creaking steps"},
    {"mob.creaking.sway", "Creaking is hit"},
    {"mob.creaking.twitch", "Creaking twitches"},
    {"mob.creaking.unfreeze", "Creaking moves"},
    {"mob.creeper.death", "Creeper dies"},
    {"mob.creeper.say", "Creeper hisses"},
    {"mob.dolphin.attack", "Dolphin attacks"},
    {"mob.dolphin.blowhole", "Dolphin breathes"},
    {"mob.dolphin.death", "Dolphin dies"},
    {"mob.dolphin.eat", "Dolphin eats"},
    {"mob.dolphin.hurt", "Dolphin hurts"},
    {"mob.dolphin.idle", "Dolphin chirps"},
    {"mob.dolphin.idle_water", "Dolphin whistles"},
    {"mob.dolphin.jump", "Dolphin jumps"},
    {"mob.dolphin.play", "Dolphin plays"},
    {"mob.dolphin.splash", "Dolphin splashes"},
    {"mob.dolphin.swim", "Dolphin swims"},
    {"mob.drowned.death", "Drowned dies"},
    {"mob.drowned.death_water", "Drowned dies"},
    {"mob.drowned.hurt", "Drowned hurts"},
    {"mob.drowned.hurt_water", "Drowned hurts"},
    {"mob.drowned.say", "Drowned gurgles"},
    {"mob.drowned.say_water", "Drowned gurgles"},
    {"mob.drowned.shoot", "Drowned throws trident"},
    {"mob.drowned.step", "Drowned steps"},
    {"mob.drowned.swim", "Drowned swims"},
    {"mob.elderguardian.curse", "Elder guardian curses"},
    {"mob.elderguardian.death", "Elder guardian dies"},
    {"mob.elderguardian.hit", "Elder guardian hurts"},
    {"mob.elderguardian.idle", "Elder guardian moans"},
    {"mob.enderdragon.death", "Dragon dies"},
    {"mob.enderdragon.flap", "Dragon flaps"},
    {"mob.enderdragon.growl", "Dragon growls"},
    {"mob.enderdragon.hit", "Dragon hurts"},
    {"mob.endermen.death", "Enderman dies"},
    {"mob.endermen.hit", "Enderman hurts"},
    {"mob.endermen.idle", "Enderman vwoops"},
    {"mob.endermen.portal", "Enderman teleports"},
    {"mob.endermen.scream", "Enderman screams"},
    {"mob.endermen.stare", "Enderman cries out"},
    {"mob.endermite.hit", "Endermite hurts"},
    {"mob.endermite.kill", "Endermite dies"},
    {"mob.endermite.say", "Endermite scuttles"},
    {"mob.endermite.step", "Endermite steps"},
    {"mob.evocation_fangs.attack", "Fangs snap"},
    {"mob.evocation_illager.ambient", "Evoker murmurs"},
    {"mob.evocation_illager.cast_spell", "Evoker casts spell"},
    {"mob.evocation_illager.celebrate", "Evoker cheers"},
    {"mob.evocation_illager.death", "Evoker dies"},
    {"mob.evocation_illager.hurt", "Evoker hurts"},
    {"mob.evocation_illager.prepare_attack", "Evoker prepares attack"},
    {"mob.evocation_illager.prepare_summon", "Evoker prepares summoning"},
    {"mob.evocation_illager.prepare_wololo", "Evoker prepares charming"},
    {"mob.fish.flop", "Fish flops"},
    {"mob.fish.hurt", "Fish hurts"},
    {"mob.fish.step", "Fish flops"},
    {"mob.fox.aggro", "Fox angers"},
    {"mob.fox.ambient", "Fox squeaks"},
    {"mob.fox.bite", "Fox bites"},
    {"mob.fox.death", "Fox dies"},
    {"mob.fox.eat", "Fox eats"},
    {"mob.fox.hurt", "Fox hurts"},
    {"mob.fox.screech", "Fox screeches"},
    {"mob.fox.sleep", "Fox snores"},
    {"mob.fox.sniff", "Fox sniffs"},
    {"mob.fox.spit", "Fox spits"},
    {"mob.frog.ambient", "Frog croaks"},
    {"mob.frog.death", "Frog dies"},
    {"mob.frog.eat", "Frog eats"},
    {"mob.frog.hurt", "Frog hurts"},
    {"mob.frog.jump_to_block", "Frog jumps"},
    {"mob.frog.lay_spawn", "Frog lays spawn"},
    {"mob.frog.step", "Frog steps"},
    {"mob.frog.tongue", "Frog tongue snaps"},
    {"mob.ghast.affectionate_scream", "Ghast cries lovingly"},
    {"mob.ghast.charge", "Ghast charges"},
    {"mob.ghast.death", "Ghast dies"},
    {"mob.ghast.fireball", "Ghast shoots"},
    {"mob.ghast.moan", "Ghast cries"},
    {"mob.ghast.scream", "Ghast cries"},
    {"mob.ghastling.ambient", "Ghastling coos"},
    {"mob.ghastling.death", "Ghastling dies"},
    {"mob.ghastling.hurt", "Ghastling hurts"},
    {"mob.ghastling.spawn", "Ghastling appears"},
    {"mob.glow_squid.ambient", "Glow squid swims"},
    {"mob.glow_squid.death", "Glow squid dies"},
    {"mob.glow_squid.hurt", "Glow squid hurts"},
    {"mob.glow_squid.ink_squirt", "Glow squid shoots ink"},
    {"mob.goat.ambient", "Goat bleats"},
    {"mob.goat.ambient.screamer", "Goat bellows"},
    {"mob.goat.death", "Goat dies"},
    {"mob.goat.death.screamer", "Goat dies"},
    {"mob.goat.eat", "Goat eats"},
    {"mob.goat.horn_break", "Goat horn breaks off"},
    {"mob.goat.hurt", "Goat hurts"},
    {"mob.goat.hurt.screamer", "Goat hurts"},
    {"mob.goat.milk.screamer", "Goat gets milked"},
    {"mob.goat.prepare_ram", "Goat stomps"},
    {"mob.goat.prepare_ram.screamer", "Goat stomps"},
    {"mob.goat.ram_impact", "Goat rams"},
    {"mob.goat.ram_impact.screamer", "Goat rams"},
    {"mob.goat.step", "Goat steps"},
    {"mob.guardian.ambient", "Guardian moans"},
    {"mob.guardian.attack_loop", "Guardian shoots"},
    {"mob.guardian.death", "Guardian dies"},
    {"mob.guardian.flop", "Guardian flops"},
    {"mob.guardian.hit", "Guardian hurts"},
    {"mob.guardian.land_death", "Guardian dies"},
    {"mob.guardian.land_hit", "Guardian hurts"},
    {"mob.guardian.land_idle", "Guardian flaps"},
    {"mob.happy_ghast.ambient", "Happy ghast croons"},
    {"mob.happy_ghast.death", "Happy ghast dies"},
    {"mob.happy_ghast.goggles_down", "Happy ghast is ready"},
    {"mob.happy_ghast.goggles_up", "Happy ghast stops"},
    {"mob.happy_ghast.harness_equip", "Harness equips"},
    {"mob.happy_ghast.harness_unequip", "Harness unequips"},
    {"mob.happy_ghast.hurt", "Happy ghast hurts"},
    {"mob.happy_ghast.ride", "Happy ghast flies"},
    {"mob.hoglin.ambient", "Hoglin growls"},
    {"mob.hoglin.angry", "Hoglin growls angrily"},
    {"mob.hoglin.attack", "Hoglin attacks"},
    {"mob.hoglin.converted_to_zombified", "Hoglin converts to zoglin"},
    {"mob.hoglin.death", "Hoglin dies"},
    {"mob.hoglin.howl", "Hoglin howls"},
    {"mob.hoglin.hurt", "Hoglin hurts"},
    {"mob.hoglin.retreat", "Hoglin retreats"},
    {"mob.hoglin.step", "Hoglin steps"},
    {"mob.horse.angry", "Horse neighs"},
    {"mob.horse.armor", "Horse armor equips"},
    {"mob.horse.breathe", "Horse breathes"},
    {"mob.horse.death", "Horse dies"},
    {"mob.horse.donkey.angry", "Donkey neighs"},
    {"mob.horse.donkey.death", "Donkey dies"},
    {"mob.horse.donkey.hit", "Donkey hurts"},
    {"mob.horse.donkey.idle", "Donkey hee-haws"},
    {"mob.horse.eat", "Horse eats"},
    {"mob.horse.gallop", "Horse gallops"},
    {"mob.horse.hit", "Horse hurts"},
    {"mob.horse.horse_armor_unequip", "Horse armor snips away"},
    {"mob.horse.idle", "Horse neighs"},
    {"mob.horse.jump", "Horse jumps"},
    {"mob.horse.land", "Horse lands"},
    {"mob.horse.leather", "Leather rustles"},
    {"mob.horse.skeleton.death", "Skeleton horse dies"},
    {"mob.horse.skeleton.hit", "Skeleton horse hurts"},
    {"mob.horse.skeleton.idle", "Skeleton horse cries"},
    {"mob.horse.soft", "Horse breathes softly"},
    {"mob.horse.wood", "Horse steps on wood"},
    {"mob.horse.zombie.death", "Zombie horse dies"},
    {"mob.horse.zombie.hit", "Zombie horse hurts"},
    {"mob.horse.zombie.idle", "Zombie horse cries"},
    {"mob.husk.ambient", "Husk groans"},
    {"mob.husk.convert_to_zombie", "Husk converts to zombie"},
    {"mob.husk.death", "Husk dies"},
    {"mob.husk.hurt", "Husk hurts"},
    {"mob.husk.step", "Husk steps"},
    {"mob.irongolem.crack", "Iron golem breaks"},
    {"mob.irongolem.death", "Iron golem dies"},
    {"mob.irongolem.hit", "Iron golem hurts"},
    {"mob.irongolem.repair", "Iron golem repaired"},
    {"mob.irongolem.throw", "Iron golem attacks"},
    {"mob.irongolem.walk", "Iron golem walks"},
    {"mob.llama.angry", "Llama bleats angrily"},
    {"mob.llama.carpet_unequip", "Carpet snips away"},
    {"mob.llama.death", "Llama dies"},
    {"mob.llama.eat", "Llama eats"},
    {"mob.llama.hurt", "Llama hurts"},
    {"mob.llama.idle", "Llama bleats"},
    {"mob.llama.spit", "Llama spits"},
    {"mob.llama.step", "Llama steps"},
    {"mob.llama.swag", "Llama is decorated"},
    {"mob.magmacube.big", "Magma cube squishes"},
    {"mob.magmacube.jump", "Magma cube jumps"},
    {"mob.magmacube.small", "Magma cube squishes"},
    {"mob.mooshroom.convert", "Mooshroom transforms"},
    {"mob.mooshroom.eat", "Mooshroom eats"},
    {"mob.mooshroom.suspicious_milk", "Mooshroom gets milked suspiciously"},
    {"mob.ocelot.death", "Ocelot dies"},
    {"mob.ocelot.idle", "Ocelot purrs"},
    {"mob.panda.bite", "Panda bites"},
    {"mob.panda.cant_breed", "Panda bleats"},
    {"mob.panda.death", "Panda dies"},
    {"mob.panda.eat", "Panda eats"},
    {"mob.panda.hurt", "Panda hurts"},
    {"mob.panda.idle", "Panda pants"},
    {"mob.panda.idle.aggressive", "Panda huffs"},
    {"mob.panda.idle.worried", "Panda whimpers"},
    {"mob.panda.presneeze", "Panda's nose tickles"},
    {"mob.panda.sneeze", "Panda sneezes"},
    {"mob.panda.step", "Panda steps"},
    {"mob.panda_baby.idle", "Baby panda squeaks"},
    {"mob.parrot.death", "Parrot dies"},
    {"mob.parrot.eat", "Parrot eats"},
    {"mob.parrot.fly", "Parrot flutters"},
    {"mob.parrot.hurt", "Parrot hurts"},
    {"mob.parrot.idle", "Parrot talks"},
    {"mob.parrot.imitate_creaking", "Parrot creaks"},
    {"mob.parrot.step", "Parrot steps"},
    {"mob.phantom.bite", "Phantom bites"},
    {"mob.phantom.death", "Phantom dies"},
    {"mob.phantom.flap", "Phantom flaps"},
    {"mob.phantom.hurt", "Phantom hurts"},
    {"mob.phantom.idle", "Phantom screeches"},
    {"mob.phantom.swoop", "Phantom swoops"},
    {"mob.pig.boost", "Pig boosts"},
    {"mob.pig.death", "Pig dies"},
    {"mob.pig.say", "Pig oinks"},
    {"mob.pig.step", "Pig steps"},
    {"mob.piglin.admiring_item", "Piglin admires item"},
    {"mob.piglin.ambient", "Piglin snorts"},
    {"mob.piglin.angry", "Piglin snorts angrily"},
    {"mob.piglin.celebrate", "Piglin celebrates"},
    {"mob.piglin.converted_to_zombified", "Piglin converts to zombified piglin"},
    {"mob.piglin.death", "Piglin dies"},
    {"mob.piglin.hurt", "Piglin hurts"},
    {"mob.piglin.jealous", "Piglin snorts enviously"},
    {"mob.piglin.retreat", "Piglin retreats"},
    {"mob.piglin.step", "Piglin steps"},
    {"mob.piglin_brute.ambient", "Piglin brute snorts"},
    {"mob.piglin_brute.angry", "Piglin brute snorts angrily"},
    {"mob.piglin_brute.converted_to_zombified", "Piglin brute converts to zombified piglin"},
    {"mob.piglin_brute.death", "Piglin brute dies"},
    {"mob.piglin_brute.hurt", "Piglin brute hurts"},
    {"mob.piglin_brute.step", "Piglin brute steps"},
    {"mob.pillager.celebrate", "Pillager cheers"},
    {"mob.pillager.death", "Pillager dies"},
    {"mob.pillager.hurt", "Pillager hurts"},
    {"mob.pillager.idle", "Pillager murmurs"},
    {"mob.player.hurt_drown", "Player drowning"},
    {"mob.player.hurt_freeze", "Player freezes"},
    {"mob.player.hurt_on_fire", "Player burns"},
    {"mob.polarbear.death", "Polar bear dies"},
    {"mob.polarbear.hurt", "Polar bear hurts"},
    {"mob.polarbear.idle", "Polar bear groans"},
    {"mob.polarbear.step", "Polar bear steps"},
    {"mob.polarbear.warning", "Polar bear roars"},
    {"mob.polarbear_baby.idle", "Baby polar bear hums"},
    {"mob.rabbit.death", "Rabbit dies"},
    {"mob.rabbit.hop", "Rabbit hops"},
    {"mob.rabbit.hurt", "Rabbit hurts"},
    {"mob.rabbit.idle", "Rabbit squeaks"},
    {"mob.ravager.ambient", "Ravager grunts"},
    {"mob.ravager.bite", "Ravager bites"},
    {"mob.ravager.celebrate", "Ravager cheers"},
    {"mob.ravager.death", "Ravager dies"},
    {"mob.ravager.hurt", "Ravager hurts"},
    {"mob.ravager.roar", "Ravager roars"},
    {"mob.ravager.step", "Ravager steps"},
    {"mob.ravager.stun", "Ravager stunned"},
    {"mob.sheep.say", "Sheep baahs"},
    {"mob.sheep.shear", "Sheep shears"},
    {"mob.sheep.step", "Sheep steps"},
    {"mob.shulker.ambient", "Shulker lurks"},
    {"mob.shulker.bullet.hit", "Shulker bullet explodes"},
    {"mob.shulker.close", "Shulker closes"},
    {"mob.shulker.close.hurt", "Shulker closes hurt"},
    {"mob.shulker.death", "Shulker dies"},
    {"mob.shulker.hurt", "Shulker hurts"},
    {"mob.shulker.open", "Shulker opens"},
    {"mob.shulker.shoot", "Shulker shoots"},
    {"mob.shulker.teleport", "Shulker teleports"},
    {"mob.silverfish.hit", "Silverfish hurts"},
    {"mob.silverfish.kill", "Silverfish dies"},
    {"mob.silverfish.say", "Silverfish hisses"},
    {"mob.silverfish.step", "Silverfish steps"},
    {"mob.skeleton.convert_to_stray", "Skeleton converts to stray"},
    {"mob.skeleton.death", "Skeleton dies"},
    {"mob.skeleton.hurt", "Skeleton hurts"},
    {"mob.skeleton.say", "Skeleton rattles"},
    {"mob.skeleton.step", "Skeleton steps"},
    {"mob.slime.attack", "Slime attacks"},
    {"mob.slime.big", "Slime squishes"},
    {"mob.slime.death", "Slime dies"},
    {"mob.slime.hurt", "Slime hurts"},
    {"mob.slime.jump", "Slime jumps"},
    {"mob.slime.small", "Slime squishes"},
    {"mob.slime.squish", "Slime squishes"},
    {"mob.sniffer.death", "Sniffer dies"},
    {"mob.sniffer.digging", "Sniffer digs"},
    {"mob.sniffer.drop_seed", "Sniffer drops seed"},
    {"mob.sniffer.eat", "Sniffer eats"},
    {"mob.sniffer.happy", "Sniffer delights"},
    {"mob.sniffer.hurt", "Sniffer hurts"},
    {"mob.sniffer.idle", "Sniffer grunts"},
    {"mob.sniffer.long_sniff", "Sniffer scents"},
    {"mob.sniffer.plop", "Sniffer plops"},
    {"mob.sniffer.searching", "Sniffer searches"},
    {"mob.sniffer.sniffsniff", "Sniffer sniffs"},
    {"mob.sniffer.stand_up", "Sniffer stands up"},
    {"mob.sniffer.step", "Sniffer steps"},
    {"mob.snowgolem.death", "Snow golem dies"},
    {"mob.snowgolem.hurt", "Snow golem hurts"},
    {"mob.snowgolem.shoot", "Snow golem shoots"},
    {"mob.spider.death", "Spider dies"},
    {"mob.spider.say", "Spider hisses"},
    {"mob.spider.step", "Spider steps"},
    {"mob.squid.ambient", "Squid swims"},
    {"mob.squid.death", "Squid dies"},
    {"mob.squid.hurt", "Squid hurts"},
    {"mob.squid.ink_squirt", "Squid shoots ink"},
    {"mob.stray.ambient", "Stray rattles"},
    {"mob.stray.death", "Stray dies"},
    {"mob.stray.hurt", "Stray hurts"},
    {"mob.stray.step", "Stray steps"},
    {"mob.strider.death", "Strider dies"},
    {"mob.strider.eat", "Strider eats"},
    {"mob.strider.hurt", "Strider hurts"},
    {"mob.strider.idle", "Strider chirps"},
    {"mob.strider.panic", "Strider retreats"},
    {"mob.strider.step", "Strider steps"},
    {"mob.strider.step_lava", "Strider steps in lava"},
    {"mob.strider.tempt", "Strider warbles"},
    {"mob.tadpole.convert_to_frog", "Tadpole grows up"},
    {"mob.tadpole.death", "Tadpole dies"},
    {"mob.tadpole.hurt", "Tadpole hurts"},
    {"mob.turtle.ambient", "Turtle chirps"},
    {"mob.turtle.death", "Turtle dies"},
    {"mob.turtle.hurt", "Turtle hurts"},
    {"mob.turtle.step", "Turtle shambles"},
    {"mob.turtle.swim", "Turtle swims"},
    {"mob.turtle_baby.born", "Baby turtle born"},
    {"mob.turtle_baby.death", "Baby turtle dies"},
    {"mob.turtle_baby.hurt", "Baby turtle hurts"},
    {"mob.turtle_baby.step", "Baby turtle shambles"},
    {"mob.unsaddle", "Saddle snips away"},
    {"mob.vex.ambient", "Vex vexes"},
    {"mob.vex.charge", "Vex shrieks"},
    {"mob.vex.death", "Vex dies"},
    {"mob.vex.hurt", "Vex hurts"},
    {"mob.villager.death", "Villager dies"},
    {"mob.villager.haggle", "Villager trades"},
    {"mob.villager.hit", "Villager hurts"},
    {"mob.villager.idle", "Villager mumbles"},
    {"mob.villager.no", "Villager disagrees"},
    {"mob.villager.yes", "Villager agrees"},
    {"mob.vindicator.celebrate", "Vindicator cheers"},
    {"mob.vindicator.death", "Vindicator dies"},
    {"mob.vindicator.hurt", "Vindicator hurts"},
    {"mob.vindicator.idle", "Vindicator mutters"},
    {"mob.wanderingtrader.death", "Wandering trader dies"},
    {"mob.wanderingtrader.disappeared", "Wandering trader disappears"},
    {"mob.wanderingtrader.drink_milk", "Wandering trader drinks milk"},
    {"mob.wanderingtrader.drink_potion", "Wandering trader drinks potion"},
    {"mob.wanderingtrader.haggle", "Wandering trader trades"},
    {"mob.wanderingtrader.hurt", "Wandering trader hurts"},
    {"mob.wanderingtrader.idle", "Wandering trader mumbles"},
    {"mob.wanderingtrader.no", "Wandering trader disagrees"},
    {"mob.wanderingtrader.reappeared", "Wandering trader appears"},
    {"mob.wanderingtrader.yes", "Wandering trader agrees"},
    {"mob.warden.agitated", "Warden groans angrily"},
    {"mob.warden.angry", "Warden rages"},
    {"mob.warden.attack", "Warden lands hit"},
    {"mob.warden.clicking", "Warden's tendrils click"},
    {"mob.warden.death", "Warden dies"},
    {"mob.warden.dig", "Warden digs"},
    {"mob.warden.emerge", "Warden emerges"},
    {"mob.warden.heartbeat", "Warden's heart beats"},
    {"mob.warden.hurt", "Warden hurts"},
    {"mob.warden.idle", "Warden whines"},
    {"mob.warden.listening", "Warden takes notice"},
    {"mob.warden.listening_angry", "Warden takes notice angrily"},
    {"mob.warden.nearby_close", "Warden approaches"},
    {"mob.warden.nearby_closer", "Warden advances"},
    {"mob.warden.nearby_closest", "Warden draws close"},
    {"mob.warden.roar", "Warden roars"},
    {"mob.warden.sniff", "Warden sniffs"},
    {"mob.warden.sonic_boom", "Warden booms"},
    {"mob.warden.sonic_charge", "Warden charges"},
    {"mob.warden.step", "Warden steps"},
    {"mob.witch.ambient", "Witch giggles"},
    {"mob.witch.celebrate", "Witch cheers"},
    {"mob.witch.death", "Witch dies"},
    {"mob.witch.drink", "Witch drinks"},
    {"mob.witch.hurt", "Witch hurts"},
    {"mob.witch.throw", "Witch throws"},
    {"mob.wither.ambient", "Wither angers"},
    {"mob.wither.break_block", "Wither breaks block"},
    {"mob.wither.death", "Wither dies"},
    {"mob.wither.hurt", "Wither hurts"},
    {"mob.wither.shoot", "Wither attacks"},
    {"mob.wither.spawn", "Wither released"},
    {"mob.wolf.bark", "Wolf barks"},
    {"mob.wolf.big.bark", "Big wolf barks"},
    {"mob.wolf.big.death", "Big wolf dies"},
    {"mob.wolf.big.growl", "Big wolf growls"},
    {"mob.wolf.big.hurt", "Big wolf hurts"},
    {"mob.wolf.big.panting", "Big wolf pants"},
    {"mob.wolf.big.whine", "Big wolf whines"},
    {"mob.wolf.cute.bark", "Cute wolf barks"},
    {"mob.wolf.cute.death", "Cute wolf dies"},
    {"mob.wolf.cute.growl", "Cute wolf growls"},
    {"mob.wolf.cute.hurt", "Cute wolf hurts"},
    {"mob.wolf.cute.panting", "Cute wolf pants"},
    {"mob.wolf.cute.whine", "Cute wolf whines"},
    {"mob.wolf.death", "Wolf dies"},
    {"mob.wolf.growl", "Wolf growls"},
    {"mob.wolf.grumpy.bark", "Grumpy wolf barks"},
    {"mob.wolf.grumpy.death", "Grumpy wolf dies"},
    {"mob.wolf.grumpy.growl", "Grumpy wolf growls"},
    {"mob.wolf.grumpy.hurt", "Grumpy wolf hurts"},
    {"mob.wolf.grumpy.panting", "Grumpy wolf pants"},
    {"mob.wolf.grumpy.whine", "Grumpy wolf whines"},
    {"mob.wolf.hurt", "Wolf hurts"},
    {"mob.wolf.mad.bark", "Mad wolf barks"},
    {"mob.wolf.mad.death", "Mad wolf dies"},
    {"mob.wolf.mad.growl", "Mad wolf growls"},
    {"mob.wolf.mad.hurt", "Mad wolf hurts"},
    {"mob.wolf.mad.panting", "Mad wolf pants"},
    {"mob.wolf.mad.whine", "Mad wolf whines"},
    {"mob.wolf.panting", "Wolf pants"},
    {"mob.wolf.puglin.bark", "Puglin wolf barks"},
    {"mob.wolf.puglin.death", "Puglin wolf dies"},
    {"mob.wolf.puglin.growl", "Puglin wolf growls"},
    {"mob.wolf.puglin.hurt", "Puglin wolf hurts"},
    {"mob.wolf.puglin.panting", "Puglin wolf pants"},
    {"mob.wolf.puglin.whine", "Puglin wolf whines"},
    {"mob.wolf.sad.bark", "Sad wolf barks"},
    {"mob.wolf.sad.death", "Sad wolf dies"},
    {"mob.wolf.sad.growl", "Sad wolf growls"},
    {"mob.wolf.sad.hurt", "Sad wolf hurts"},
    {"mob.wolf.sad.panting", "Sad wolf pants"},
    {"mob.wolf.sad.whine", "Sad wolf whines"},
    {"mob.wolf.shake", "Wolf shakes"},
    {"mob.wolf.step", "Wolf steps"},
    {"mob.wolf.whine", "Wolf whines"},
    {"mob.zoglin.angry", "Zoglin growls angrily"},
    {"mob.zoglin.attack", "Zoglin attacks"},
    {"mob.zoglin.death", "Zoglin dies"},
    {"mob.zoglin.hurt", "Zoglin hurts"},
    {"mob.zoglin.idle", "Zoglin growls"},
    {"mob.zoglin.step", "Zoglin steps"},
    {"mob.zombie.death", "Zombie dies"},
    {"mob.zombie.hurt", "Zombie hurts"},
    {"mob.zombie.remedy", "Zombie cures"},
    {"mob.zombie.say", "Zombie groans"},
    {"mob.zombie.step", "Zombie steps"},
    {"mob.zombie.unfect", "Zombie cures"},
    {"mob.zombie.wood", "Zombie steps on wood"},
    {"mob.zombie.woodbreak", "Door breaks"},
    {"mob.zombie_villager.death", "Zombie villager dies"},
    {"mob.zombie_villager.hurt", "Zombie villager hurts"},
    {"mob.zombie_villager.say", "Zombie villager groans"},
    {"mob.zombiepig.zpig", "Zombified piglin grunts"},
    {"mob.zombiepig.zpigangry", "Zombified piglin grunts angrily"},
    {"mob.zombiepig.zpigdeath", "Zombified piglin dies"},
    {"mob.zombiepig.zpighurt", "Zombified piglin hurts"},
    {"music.game", "Music plays"},
    {"music.game.basalt_deltas", "Basalt deltas music"},
    {"music.game.creative", "Creative music"},
    {"music.game.credits", "Credits music"},
    {"music.game.crimson_forest", "Crimson forest music"},
    {"music.game.deep_dark", "Deep dark music"},
    {"music.game.dripstone_caves", "Dripstone caves music"},
    {"music.game.end", "End music"},
    {"music.game.endboss", "End boss music"},
    {"music.game.frozen_peaks", "Frozen peaks music"},
    {"music.game.grove", "Grove music"},
    {"music.game.jagged_peaks", "Jagged peaks music"},
    {"music.game.lush_caves", "Lush caves music"},
    {"music.game.meadow", "Meadow music"},
    {"music.game.nether", "Nether music"},
    {"music.game.nether_wastes", "Nether wastes music"},
    {"music.game.snowy_slopes", "Snowy slopes music"},
    {"music.game.soulsand_valley", "Soul sand valley music"},
    {"music.game.stony_peaks", "Stony peaks music"},
    {"music.game.swamp_music", "Swamp music"},
    {"music.game.warped_forest", "Warped forest music"},
    {"music.game.water", "Underwater music"},
    {"music.game_and_wild_equal_chance", "Game and wild music"},
    {"music.game_and_wild_favor_game", "Game music favored"},
    {"music.menu", "Menu music"},
    {"music.overworld.bamboo_jungle", "Bamboo jungle music"},
    {"music.overworld.cherry_grove", "Cherry grove music"},
    {"music.overworld.deep_dark", "Deep dark music"},
    {"music.overworld.desert", "Desert music"},
    {"music.overworld.dripstone_caves", "Dripstone caves music"},
    {"music.overworld.flower_forest", "Flower forest music"},
    {"music.overworld.forest", "Forest music"},
    {"music.overworld.grove", "Grove music"},
    {"music.overworld.jagged_peaks", "Jagged peaks music"},
    {"music.overworld.jungle", "Jungle music"},
    {"music.overworld.jungle_edge", "Jungle edge music"},
    {"music.overworld.lush_caves", "Lush caves music"},
    {"music.overworld.mesa", "Mesa music"},
    {"music.overworld.snowy_slopes", "Snowy slopes music"},
    {"music.overworld.stony_peaks", "Stony peaks music"},
    {"note.banjo", "Banjo plays"},
    {"note.bass", "Bass plays"},
    {"note.bassattack", "Bass attack"},
    {"note.bd", "Bass drum plays"},
    {"note.bell", "Bell plays"},
    {"note.bit", "Bit plays"},
    {"note.chime", "Chime plays"},
    {"note.cow_bell", "Cow bell plays"},
    {"note.creeper", "Creeper note"},
    {"note.didgeridoo", "Didgeridoo plays"},
    {"note.enderdragon", "Ender dragon note"},
    {"note.flute", "Flute plays"},
    {"note.guitar", "Guitar plays"},
    {"note.harp", "Harp plays"},
    {"note.hat", "Hi-hat plays"},
    {"note.iron_xylophone", "Iron xylophone plays"},
    {"note.piglin", "Piglin note"},
    {"note.pling", "Pling plays"},
    {"note.skeleton", "Skeleton note"},
    {"note.snare", "Snare drum plays"},
    {"note.witherskeleton", "Wither skeleton note"},
    {"note.xylophone", "Xylophone plays"},
    {"note.zombie", "Zombie note"},
    {"ominous_bottle.end_use", "Bottle breaks"},
    {"ominous_item_spawner.about_to_spawn_item", "Ominous item prepares"},
    {"ominous_item_spawner.spawn_item", "Ominous item drops"},
    {"ominous_item_spawner.spawn_item_begin", "Ominous item appears"},
    {"open.bamboo_wood_door", "Bamboo door opens"},
    {"open.bamboo_wood_fence_gate", "Bamboo fence gate opens"},
    {"open.bamboo_wood_trapdoor", "Bamboo trapdoor opens"},
    {"open.cherry_wood_door", "Cherry door opens"},
    {"open.cherry_wood_fence_gate", "Cherry fence gate opens"},
    {"open.cherry_wood_trapdoor", "Cherry trapdoor opens"},
    {"open.fence_gate", "Fence gate opens"},
    {"open.iron_door", "Iron door opens"},
    {"open.iron_trapdoor", "Iron trapdoor opens"},
    {"open.nether_wood_door", "Nether door opens"},
    {"open.nether_wood_fence_gate", "Nether fence gate opens"},
    {"open.nether_wood_trapdoor", "Nether trapdoor opens"},
    {"open.wooden_door", "Wooden door opens"},
    {"open.wooden_trapdoor", "Wooden trapdoor opens"},
    {"open_door.copper", "Copper door opens"},
    {"open_trapdoor.copper", "Copper trapdoor opens"},
    {"particle.soul_escape", "Soul escapes"},
    {"pick_berries.cave_vines", "Berries picked"},
    {"pickup.chiseled_bookshelf", "Book taken"},
    {"pickup_enchanted.chiseled_bookshelf", "Enchanted book taken"},
    {"place.amethyst_block", "Amethyst block placed"},
    {"place.amethyst_cluster", "Amethyst cluster placed"},
    {"place.azalea", "Azalea placed"},
    {"place.azalea_leaves", "Azalea leaves placed"},
    {"place.bamboo_wood", "Bamboo wood placed"},
    {"place.big_dripleaf", "Big dripleaf placed"},
    {"place.calcite", "Calcite placed"},
    {"place.cherry_leaves", "Cherry leaves placed"},
    {"place.cherry_wood", "Cherry wood placed"},
    {"place.chiseled_bookshelf", "Chiseled bookshelf placed"},
    {"place.copper", "Copper placed"},
    {"place.copper_bulb", "Copper bulb placed"},
    {"place.deepslate", "Deepslate placed"},
    {"place.deepslate_bricks", "Deepslate bricks placed"},
    {"place.dirt_with_roots", "Dirt with roots placed"},
    {"place.dripstone_block", "Dripstone block placed"},
    {"place.hanging_roots", "Hanging roots placed"},
    {"place.iron", "Iron placed"},
    {"place.large_amethyst_bud", "Large amethyst bud placed"},
    {"place.medium_amethyst_bud", "Medium amethyst bud placed"},
    {"place.moss", "Moss placed"},
    {"place.nether_wood", "Nether wood placed"},
    {"place.pink_petals", "Pink petals placed"},
    {"place.pointed_dripstone", "Pointed dripstone placed"},
    {"place.powder_snow", "Powder snow placed"},
    {"place.sculk", "Sculk placed"},
    {"place.sculk_catalyst", "Sculk catalyst placed"},
    {"place.sculk_sensor", "Sculk sensor placed"},
    {"place.sculk_shrieker", "Sculk shrieker placed"},
    {"place.small_amethyst_bud", "Small amethyst bud placed"},
    {"place.sponge", "Sponge placed"},
    {"place.spore_blossom", "Spore blossom placed"},
    {"place.suspicious_gravel", "Suspicious gravel placed"},
    {"place.suspicious_sand", "Suspicious sand placed"},
    {"place.tuff", "Tuff placed"},
    {"place.tuff_bricks", "Tuff bricks placed"},
    {"place.wet_sponge", "Wet sponge placed"},
    {"portal.portal", "Portal whooshes"},
    {"portal.travel", "Portal noise fades"},
    {"portal.trigger", "Portal noise intensifies"},
    {"power.off.sculk_sensor", "Sculk sensor stops clicking"},
    {"power.on.sculk_sensor", "Sculk sensor clicks"},
    {"pumpkin.carve", "Shears carve"},
    {"raid.horn", "Ominous horn blares"},
    {"random.anvil_break", "Anvil destroyed"},
    {"random.anvil_land", "Anvil landed"},
    {"random.anvil_use", "Anvil used"},
    {"random.bow", "Arrow fired"},
    {"random.bowhit", "Arrow hits"},
    {"random.break", "Item breaks"},
    {"random.burp", "Burp"},
    {"random.chestclosed", "Chest closes"},
    {"random.chestopen", "Chest opens"},
    {"random.click", "Click"},
    {"random.door_close", "Door closes"},
    {"random.door_open", "Door opens"},
    {"random.drink", "Sipping"},
    {"random.drink_honey", "Gulping"},
    {"random.eat", "Eating"},
    {"random.enderchestclosed", "Ender chest closes"},
    {"random.enderchestopen", "Ender chest opens"},
    {"random.explode", "Explosion"},
    {"random.fizz", "Fizzing"},
    {"random.fuse", "TNT fizzes"},
    {"random.glass", "Glass breaks"},
    {"random.hurt", "Something hurts"},
    {"random.levelup", "Player dings"},
    {"random.lever_click", "Lever clicks"},
    {"random.orb", "Experience gained"},
    {"random.pop", "Item plops"},
    {"random.pop2", "Pop"},
    {"random.potion.brewed", "Brewing stand bubbles"},
    {"random.screenshot", "Camera clicks"},
    {"random.shulkerboxclosed", "Shulker box closes"},
    {"random.shulkerboxopen", "Shulker box opens"},
    {"random.splash", "Splashing"},
    {"random.stone_click", "Stone clicks"},
    {"random.swim", "Swimming"},
    {"random.toast", "Achievement toast"},
    {"random.toast_recipe_unlocking_in", "Recipe unlocked"},
    {"random.toast_recipe_unlocking_out", "Recipe appears"},
    {"random.totem", "Totem activates"},
    {"random.wood_click", "Wood clicks"},
    {"record.11", "Music disc plays"},
    {"record.13", "Music disc plays"},
    {"record.5", "Music disc plays"},
    {"record.blocks", "Music disc plays"},
    {"record.cat", "Music disc plays"},
    {"record.chirp", "Music disc plays"},
    {"record.creator", "Music disc plays"},
    {"record.creator_music_box", "Music box plays"},
    {"record.far", "Music disc plays"},
    {"record.lava_chicken", "Music disc plays"},
    {"record.mall", "Music disc plays"},
    {"record.mellohi", "Music disc plays"},
    {"record.otherside", "Music disc plays"},
    {"record.pigstep", "Music disc plays"},
    {"record.precipice", "Music disc plays"},
    {"record.relic", "Music disc plays"},
    {"record.stal", "Music disc plays"},
    {"record.strad", "Music disc plays"},
    {"record.tears", "Music disc plays"},
    {"record.wait", "Music disc plays"},
    {"record.ward", "Music disc plays"},
    {"resonate.amethyst_block", "Amethyst resonates"},
    {"respawn_anchor.ambient", "Respawn anchor whooshes"},
    {"respawn_anchor.charge", "Respawn anchor is charged"},
    {"respawn_anchor.deplete", "Respawn anchor depletes"},
    {"respawn_anchor.set_spawn", "Respawn anchor sets spawn"},
    {"scrape", "Axe scrapes"},
    {"shatter.decorated_pot", "Decorated pot shatters"},
    {"shriek.sculk_shrieker", "Sculk shrieker shrieks"},
    {"sign.dye.use", "Dye stains"},
    {"sign.ink_sac.use", "Ink sac splotches"},
    {"smithing_table.use", "Smithing table used"},
    {"sparkler.active", "Sparkler crackles"},
    {"sponge.absorb", "Sponge sucks"},
    {"spread.sculk", "Sculk spreads"},
    {"step.amethyst_block", "Footsteps on amethyst block"},
    {"step.amethyst_cluster", "Footsteps on amethyst cluster"},
    {"step.ancient_debris", "Footsteps on ancient debris"},
    {"step.azalea", "Footsteps on azalea"},
    {"step.azalea_leaves", "Footsteps on azalea leaves"},
    {"step.bamboo_wood", "Footsteps on bamboo wood"},
    {"step.bamboo_wood_hanging_sign", "Footsteps on bamboo hanging sign"},
    {"step.basalt", "Footsteps on basalt"},
    {"step.big_dripleaf", "Footsteps on big dripleaf"},
    {"step.bone_block", "Footsteps on bone block"},
    {"step.calcite", "Footsteps on calcite"},
    {"step.candle", "Footsteps on candle"},
    {"step.cave_vines", "Footsteps on cave vines"},
    {"step.chain", "Footsteps on chain"},
    {"step.cherry_leaves", "Footsteps on cherry leaves"},
    {"step.cherry_wood", "Footsteps on cherry wood"},
    {"step.cherry_wood_hanging_sign", "Footsteps on cherry hanging sign"},
    {"step.chiseled_bookshelf", "Footsteps on chiseled bookshelf"},
    {"step.cloth", "Footsteps on cloth"},
    {"step.copper", "Footsteps on copper"},
    {"step.copper_bulb", "Footsteps on copper bulb"},
    {"step.copper_grate", "Footsteps on copper grate"},
    {"step.coral", "Footsteps on coral"},
    {"step.decorated_pot", "Footsteps on decorated pot"},
    {"step.deepslate", "Footsteps on deepslate"},
    {"step.deepslate_bricks", "Footsteps on deepslate bricks"},
    {"step.dirt_with_roots", "Footsteps on dirt with roots"},
    {"step.dripstone_block", "Footsteps on dripstone block"},
    {"step.frog_spawn", "Footsteps on frog spawn"},
    {"step.froglight", "Footsteps on froglight"},
    {"step.grass", "Footsteps on grass"},
    {"step.gravel", "Footsteps on gravel"},
    {"step.hanging_roots", "Footsteps on hanging roots"},
    {"step.hanging_sign", "Footsteps on hanging sign"},
    {"step.heavy_core", "Footsteps on heavy core"},
    {"step.honey_block", "Footsteps on honey block"},
    {"step.iron", "Footsteps on iron"},
    {"step.ladder", "Footsteps on ladder"},
    {"step.moss", "Footsteps on moss"},
    {"step.nether_brick", "Footsteps on nether brick"},
    {"step.nether_gold_ore", "Footsteps on nether gold ore"},
    {"step.nether_sprouts", "Footsteps on nether sprouts"},
    {"step.nether_wart", "Footsteps on nether wart"},
    {"step.nether_wood", "Footsteps on nether wood"},
    {"step.nether_wood_hanging_sign", "Footsteps on nether hanging sign"},
    {"step.netherite", "Footsteps on netherite"},
    {"step.netherrack", "Footsteps on netherrack"},
    {"step.nylium", "Footsteps on nylium"},
    {"step.pink_petals", "Footsteps on pink petals"},
    {"step.pointed_dripstone", "Footsteps on pointed dripstone"},
    {"step.powder_snow", "Footsteps on powder snow"},
    {"step.roots", "Footsteps on roots"},
    {"step.sand", "Footsteps on sand"},
    {"step.sculk", "Footsteps on sculk"},
    {"step.sculk_catalyst", "Footsteps on sculk catalyst"},
    {"step.sculk_sensor", "Footsteps on sculk sensor"},
    {"step.sculk_shrieker", "Footsteps on sculk shrieker"},
    {"step.sculk_vein", "Footsteps on sculk vein"},
    {"step.shroomlight", "Footsteps on shroomlight"},
    {"step.slime", "Footsteps on slime"},
    {"step.snow", "Footsteps on snow"},
    {"step.soul_sand", "Footsteps on soul sand"},
    {"step.soul_soil", "Footsteps on soul soil"},
    {"step.sponge", "Footsteps on sponge"},
    {"step.spore_blossom", "Footsteps on spore blossom"},
    {"step.stem", "Footsteps on stem"},
    {"step.stone", "Footsteps on stone"},
    {"step.suspicious_gravel", "Footsteps on suspicious gravel"},
    {"step.suspicious_sand", "Footsteps on suspicious sand"},
    {"step.tuff", "Footsteps on tuff"},
    {"step.tuff_bricks", "Footsteps on tuff bricks"},
    {"step.vines", "Footsteps on vines"},
    {"step.web", "Footsteps on web"},
    {"step.wet_sponge", "Footsteps on wet sponge"},
    {"step.wood", "Footsteps on wood"},
    {"tile.piston.in", "Piston retracts"},
    {"tile.piston.out", "Piston extends"},
    {"tilt_down.big_dripleaf", "Dripleaf tilts down"},
    {"tilt_up.big_dripleaf", "Dripleaf tilts up"},
    {"tokens.vanilla.modal_hide", "UI modal hides"},
    {"tokens.vanilla.release", "UI release sound"},
    {"tokens.vanilla.snes_pop", "UI pop sound"},
    {"trial_spawner.ambient", "Trial spawner crackles"},
    {"trial_spawner.ambient_ominous", "Ominous crackling"},
    {"trial_spawner.break", "Trial spawner breaks"},
    {"trial_spawner.charge_activate", "Omen engulfs trial spawner"},
    {"trial_spawner.close_shutter", "Trial spawner closes"},
    {"trial_spawner.detect_player", "Trial spawner charges up"},
    {"trial_spawner.eject_item", "Trial spawner ejects items"},
    {"trial_spawner.hit", "Trial spawner hit"},
    {"trial_spawner.open_shutter", "Trial spawner opens"},
    {"trial_spawner.place", "Trial spawner placed"},
    {"trial_spawner.spawn_mob", "Trial spawner spawns a mob"},
    {"trial_spawner.step", "Footsteps on trial spawner"},
    {"ui.cartography_table.take_result", "Map drawn"},
    {"ui.drawer_close", "Drawer closes"},
    {"ui.drawer_open", "Drawer opens"},
    {"ui.hardcore_disable", "Hardcore disabled"},
    {"ui.hardcore_enable", "Hardcore enabled"},
    {"ui.hardcore_toggle_press", "Hardcore toggle pressed"},
    {"ui.loom.select_pattern", "Pattern selected"},
    {"ui.loom.take_result", "Loom used"},
    {"ui.stonecutter.take_result", "Stonecutter used"},
    {"use.ancient_debris", "Using ancient debris"},
    {"use.basalt", "Using basalt"},
    {"use.bone_block", "Using bone block"},
    {"use.candle", "Using candle"},
    {"use.cave_vines", "Using cave vines"},
    {"use.chain", "Using chain"},
    {"use.cloth", "Using cloth"},
    {"use.copper", "Using copper"},
    {"use.coral", "Using coral"},
    {"use.deepslate", "Using deepslate"},
    {"use.deepslate_bricks", "Using deepslate bricks"},
    {"use.dirt_with_roots", "Using dirt with roots"},
    {"use.dripstone_block", "Using dripstone block"},
    {"use.grass", "Using grass"},
    {"use.gravel", "Using gravel"},
    {"use.hanging_roots", "Using hanging roots"},
    {"use.honey_block", "Using honey block"},
    {"use.ladder", "Using ladder"},
    {"use.moss", "Using moss"},
    {"use.nether_brick", "Using nether brick"},
    {"use.nether_gold_ore", "Using nether gold ore"},
    {"use.nether_sprouts", "Using nether sprouts"},
    {"use.nether_wart", "Using nether wart"},
    {"use.netherite", "Using netherite"},
    {"use.netherrack", "Using netherrack"},
    {"use.nylium", "Using nylium"},
    {"use.pointed_dripstone", "Using pointed dripstone"},
    {"use.roots", "Using roots"},
    {"use.sand", "Using sand"},
    {"use.sculk_sensor", "Using sculk sensor"},
    {"use.shroomlight", "Using shroomlight"},
    {"use.slime", "Using slime"},
    {"use.snow", "Using snow"},
    {"use.soul_sand", "Using soul sand"},
    {"use.soul_soil", "Using soul soil"},
    {"use.spore_blossom", "Using spore blossom"},
    {"use.stem", "Using stem"},
    {"use.stone", "Using stone"},
    {"use.vines", "Using vines"},
    {"use.wood", "Using wood"},
    {"vault.activate", "Vault ignites"},
    {"vault.ambient", "Vault crackles"},
    {"vault.break", "Vault breaks"},
    {"vault.close_shutter", "Vault closes"},
    {"vault.deactivate", "Vault extinguishes"},
    {"vault.eject_item", "Vault ejects item"},
    {"vault.hit", "Vault hit"},
    {"vault.insert_item", "Vault unlocks"},
    {"vault.insert_item_fail", "Vault rejects item"},
    {"vault.open_shutter", "Vault opens"},
    {"vault.place", "Vault placed"},
    {"vault.reject_rewarded_player", "Vault rejects player"},
    {"vault.step", "Footsteps on vault"},
    {"vr.stutterturn", "VR stutter turn"},
    {"wind_charge.burst", "Wind charge bursts"}
};

std::string SoundDescriptions::getSoundDescription(const std::string& soundName) {
    auto it = soundDescriptions.find(soundName);
    if (it != soundDescriptions.end()) {
        return it->second;
    }
    return "Unknown sound";
}