#define IDR_4D_PNG                     101
#define IDR_ANIMATIONS_PNG             102
#define IDR_ARROW_PNG                  103
#define IDR_AUTO_SPRINT_PNG            104
#define IDR_AUTOGG_PNG                 105
#define IDR_BLOCK_PNG                  106
#define IDR_BLOCK_BREAK_INDICATOR_PNG  107
#define IDR_BLUR_PNG                   108
#define IDR_CHESTPLATE_PNG             109
#define IDR_CLICKGUI_PNG               110
#define IDR_CLOUDY_PNG                 111
#define IDR_COMBO_PNG                  112
#define IDR_COORDINATES_PNG            113
#define IDR_CURSOR_PNG                 114
#define IDR_DOWN_PNG                   115
#define IDR_DVDLOGO_01_PNG             116
#define IDR_DVDLOGO_02_PNG             117
#define IDR_DVDLOGO_03_PNG             118
#define IDR_DVDLOGO_04_PNG             119
#define IDR_DVDLOGO_05_PNG             120
#define IDR_DVDLOGO_06_PNG             121
#define IDR_DVDLOGO_07_PNG             122
#define IDR_DVDLOGO_08_PNG             123
#define IDR_EYE_PNG                    124
#define IDR_FIELD_OF_VIEW_PNG          125
#define IDR_FLARIAL_TITLE_PNG          126
#define IDR_FPS_PNG                    127
#define IDR_FREELOOK_PNG               128
#define IDR_FRYING_PAN_PNG             129
#define IDR_FULLBRIGHT_PNG             130
#define IDR_GEAR_PNG                   131
#define IDR_HURT_PNG                   132
#define IDR_ICOGNITO_PNG               133
#define IDR_KEYBOARD_PNG               134
#define IDR_LIKE_PNG                   135
#define IDR_LIST_PNG                   136
#define IDR_LOGO_PNG                   137
#define IDR_MAGNIFY_PNG                138
#define IDR_MAN_PNG                    139
#define IDR_MEMORY_PNG                 140
#define IDR_MODULES_PNG                141
#define IDR_NAMETAG_PNG                142
#define IDR_PENCIL_PNG                 143
#define IDR_PING_PNG                   144
#define IDR_POTION_PNG                 145
#define IDR_RE_Q_PNG                   146
#define IDR_REACH_PNG                  147
#define IDR_RENDEROPTIONS_PNG          148
#define IDR_RGB_PNG                    149
#define IDR_SEARCH_PNG                 150
#define IDR_SERVER_IP_PNG              151
#define IDR_SKULL_PNG                  152
#define IDR_SLOWLY_PNG                 153
#define IDR_SMOKE_PNG                  154
#define IDR_SNAP_PNG                   155
#define IDR_SPEED_PNG                  156
#define IDR_STOP_PNG                   157
#define IDR_TEXT_BOX_PNG               158
#define IDR_TIME_PNG                   159
#define IDR_TRANSPARENT_PNG            160
#define IDR_UPSIDE_DOWN_PNG            161
#define IDR_FONT_TTF                   162
#define IDR_FONT_BOLD_TTF              163
#define IDR_MINECRAFTIA_TTF            164
#define IDR_PATAR_JPG                  165
#define IDR_FOLDER_PNG                 166
#define IDR_FOLDER_WHITE_PNG           167
#define IDR_STYLUS_PNG                 168
#define IDR_STYLUS_WHITE_PNG           169
#define IDR_SETTINGS_PNG               170
#define IDR_SETTINGS_WHITE_PNG         171
#define IDR_ITEM_PHYSICS_PNG           172
#define IDR_CYAN_LOGO_PNG              173
#define IDR_RED_LOGO_PNG               175
#define IDR_WHITE_LOGO_PNG             176
#define IDR_YELLOW_LOGO_PNG            177
#define IDR_WAYPOINTS_PNG              178
#define IDR_MOVABLE_PNG                179
#define IDR_AUTORQ_PNG                 180
#define IDR_INVENTORY_PNG              181
#define IDR_SCALE_PNG                  182
#define IDR_ENTITYCOUNTER_PNG          183
#define IDR_01_JPG                     184
#define IDR_02_JPG                     185
#define IDR_03_JPG                     186
#define IDR_04_JPG                     187
#define IDR_05_JPG                     188
#define IDR_06_JPG                     189
#define IDR_07_JPG                     190
#define IDR_08_JPG                     191
#define IDR_09_JPG                     192
#define IDR_10_JPG                     193
#define IDR_11_JPG                     194
#define IDR_12_JPG                     195
#define IDR_13_JPG                     196
#define IDR_14_JPG                     197
#define IDR_15_JPG                     198
#define IDR_16_JPG                     199
#define IDR_17_JPG                     200
#define IDR_18_JPG                     201
#define IDR_19_JPG                     202
#define IDR_20_JPG                     203
#define IDR_21_JPG                     204
#define IDR_22_JPG                     205
#define IDR_23_JPG                     206
#define IDR_24_JPG                     207
#define IDR_25_JPG                     208
#define IDR_26_JPG                     209
#define IDR_27_JPG                     210
#define IDR_28_JPG                     211
#define IDR_29_JPG                     212
#define IDR_30_JPG                     213
#define IDR_31_JPG                     214
#define IDR_32_JPG                     215
#define IDR_CHYVES_JPG                 216
#define IDR_TREEGFX_JPG                217
#define IDR_NIKITA_01                  218
#define IDR_NIKITA_02                  219
#define IDR_NIKITA_03                  220
#define IDR_NIKITA_04                  221
#define IDR_NIKITA_05                  222
#define IDR_NIKITA_06                  223
#define IDR_NIKITA_07                  224
#define IDR_NIKITA_08                  225
#define IDR_NIKITA_09                  226
#define IDR_NIKITA_10                  227
#define IDR_NIKITA_11                  228
#define IDR_NIKITA_12                  229
#define IDR_NIKITA_13                  230
#define IDR_NIKITA_14                  231
#define IDR_NIKITA_15                  232
#define IDR_NIKITA_16                  233
#define IDR_GAMER_LOGO_PNG             234
#define IDR_BOOSTER_LOGO_PNG           235
#define IDR_HIVE_PNG                   236
#define IDR_HIVE_STATS_PNG             237
#define IDR_FREEZEENGINE_PNG           238
#define IDR_STONEHUNTER_PNG            239
#define IDR_SCRIPTING_PNG              240
#define IDR_SCRIPTING_WHITE_PNG        241
#define IDR_SCRIPT_PNG                 242
#define IDR_SWORD_PNG                  243
#define IDR_PERSPECTIVE_PNG            244
#define IDR_ZEQA_PNG                   245
#define IDR_BEAVER_PNG                 246
#define IDR_WAILA_PNG                  247
#define IDR_HEART_PNG                  248
#define IDR_SPOTIFY_PNG                249
#define IDR_MUMBLE_PNG                 250
#define IDR_ORANGE_LOGO_PNG            251
#define IDR_LEWIS_PNG                  252
#define IDR_LEWIS_MP3                  253
#define IDR_SUPPORTER_LOGO_PNG         254
#define IDR_F3_PNG                     255
#define IDR_DELETE_PNG                 256
#define IDR_RENDER_DRAGON_PNG          257
#define IDR_SKINSTEALER_PNG            263
#define IDR_CINEMATICCAMERA_PNG        264
#define IDR_DEATHLOGGER_PNG            265
#define IDR_TWERK_PNG                  266
#define IDR_CHUNKBORDER_PNG            267
#define IDR_COMPACTCHAT_PNG            268
#define IDR_KEYSTROKES_PNG             269
#define IDR_SUBTITLES_PNG              270
#define IDR_TOTEM_PNG                  271

// MAKE SURE YOU ALWAYS UPDATE THIS!

#define MAX_IMAGE_ID                   262

#define IDR_PING_AMAZING               258
#define IDR_PING_GOOD                  259
#define IDR_PING_OKAY                  260
#define IDR_PING_BAD                   261
#define IDR_PING_QUIT                  262
